import React, { useMemo, useRef, useState } from 'react';
import * as I from 'lucide-react';
import { Heading, Stats, Toast } from '../shared/CmsShared';

const menuSeed=[
  {name:'Main Menu',description:'Primary navigation menu',location:'Primary Navigation',items:10,status:'Published',updated:'May 21, 2024 10:30 AM'},
  {name:'Footer Menu',description:'Footer navigation links',location:'Footer',items:8,status:'Published',updated:'May 20, 2024 09:15 AM'},
  {name:'Top Bar Menu',description:'Top bar utility links',location:'Top Bar',items:6,status:'Published',updated:'May 19, 2024 04:45 PM'}
];
const initialStructure=[
  {title:'Home',kind:'Custom',url:'/'},{title:'About Us',kind:'Page',url:'/about-us'},{title:'Services',kind:'Page',url:'/services'},
  {title:'Web Development',kind:'Page',url:'/services/web-development',child:true},{title:'Mobile App Development',kind:'Page',url:'/services/mobile-app-development',child:true}
];

export function MenusPage(){
  const [menus,setMenus]=useState(menuSeed),[location,setLocation]=useState('All Locations'),[structure,setStructure]=useState(initialStructure),[toast,setToast]=useState(''),[form,setForm]=useState({menu:'Main Menu',parent:'None (Top Level)',title:'',url:'',target:'Same Window',icon:'',order:'0',published:true});
  const titleRef=useRef(null); const flash=t=>{setToast(t);setTimeout(()=>setToast(''),2200)};
  const filtered=menus.filter(m=>location==='All Locations'||m.location===location);
  const addMenu=()=>{const name=`New Menu ${menus.length+1}`;setMenus([...menus,{name,description:'Custom navigation menu',location:'Footer',items:0,status:'Published',updated:'Just now'}]);flash(`${name} added`)};
  const saveItem=e=>{e.preventDefault();if(!form.title.trim()||!form.url.trim()){flash('Title and URL are required');return}setStructure([...structure,{title:form.title,kind:'Custom',url:form.url,child:form.parent!=='None (Top Level)'}]);setForm({...form,title:'',url:'',order:String(structure.length+1)});flash('Menu item saved')};
  return <div className="users-page menus-page"><Heading title="Menus" action="Add New Menu" onAction={addMenu}/><div className="cms-split"><div><Stats items={[["Total Menus","3","All menu locations",I.MenuSquare,"blue"],["Published","3","Active menus",I.PanelTop,"green"],["Menu Items","28","Total items in all menus",I.ListPlus,"orange"],["Hidden Items","2","Not visible in frontend",I.ListTree,"purple"]]}/><div className="card menu-list"><div className="cms-list-toolbar"><b>Menu Locations</b><select value={location} onChange={e=>setLocation(e.target.value)}><option>All Locations</option><option>Primary Navigation</option><option>Footer</option><option>Top Bar</option></select><span/><button><I.ListFilter/>Filter</button><button onClick={()=>flash('Menu list exported')}><I.Download/>Export</button></div><div className="users-table-wrap"><table className="users-table menus-table"><thead><tr><th/><th>Menu Name</th><th>Location</th><th>Items</th><th>Status</th><th>Last Updated <I.RotateCw/></th><th>Actions</th></tr></thead><tbody>{filtered.map(m=><tr key={m.name}><td><input type="checkbox"/></td><td><span className="cms-name"><b>{m.name}</b><small>{m.description}</small></span></td><td><span className="menu-location">{m.location}</span></td><td>{m.items}</td><td><span className="page-status published">{m.status}</span></td><td><span className="cms-name">{m.updated}<small>Super Admin</small></span></td><td><div className="user-actions"><button onClick={()=>flash(`Editing ${m.name}`)}><I.Pencil/></button><button className="more"><I.EllipsisVertical/></button></div></td></tr>)}</tbody></table></div><div className="cms-result">Showing 1 to {filtered.length} of 3 results</div></div></div>
    <aside className="card menu-builder"><h3>Add New Menu Item <I.ChevronUp/></h3><form onSubmit={saveItem}><label>Menu<select value={form.menu} onChange={e=>setForm({...form,menu:e.target.value})}>{menus.map(m=><option key={m.name}>{m.name}</option>)}</select></label><label>Parent Item<select value={form.parent} onChange={e=>setForm({...form,parent:e.target.value})}><option>None (Top Level)</option>{structure.filter(x=>!x.child).map(x=><option key={x.title}>{x.title}</option>)}</select></label><label>Title *<input ref={titleRef} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Enter menu title"/></label><label>URL *<input value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="Enter URL or select page"/></label><label>Target<select value={form.target} onChange={e=>setForm({...form,target:e.target.value})}><option>Same Window</option><option>New Window</option></select></label><label>Icon (Optional)<span className="input-icon"><input value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})} placeholder="Select icon"/><I.LayoutGrid/></span></label><label>Order<input type="number" min="0" value={form.order} onChange={e=>setForm({...form,order:e.target.value})}/></label><label className="cms-toggle"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/><i/> Published</label><div className="cms-form-actions"><button type="button" onClick={()=>setForm({...form,title:'',url:''})}>Cancel</button><button>Save Item</button></div></form><div className="menu-structure"><b>Menu Structure: Main Menu</b>{structure.map((item,index)=><div className={item.child?'child':''} key={`${item.title}-${index}`}><I.GripVertical/><span><b>{item.title}</b><small>{item.url}</small></span><em>{item.kind}</em><button onClick={()=>flash(`Editing ${item.title}`)}><I.Pencil/></button><I.EllipsisVertical/></div>)}</div><p className="cms-tip"><I.Lightbulb/> Tip: Drag and drop to reorder menu items</p></aside></div><Toast text={toast}/></div>
}
