import React,{useEffect,useMemo,useState} from 'react';
import * as I from 'lucide-react';
import { createProduct,deleteProduct,getProduct,getProducts,updateProduct,uploadProductImage } from '../../../services/admin/admin-api';

const categories=['Restaurant & Hospitality','Education & Verification','Business Platform','E-commerce','Healthcare','Finance','Booking & Reservation','Mobile Application','Developer Tool'];
const types=['Web Application','Mobile Application','SaaS Platform','Business Management System','Verification Platform','Booking System','E-commerce Platform'];
const platforms=['Web','Android','iOS','Web & Mobile','Cross-platform'];
const statuses={PUBLISHED:'Published',DRAFT:'Draft',ARCHIVED:'Archived'};
const emptyForm={name:'',slug:'',description:'',category:'Restaurant & Hospitality',type:'Web Application',platform:'Web',features:'',techStack:'',imageUrl:'',productUrl:'',status:'PUBLISHED',featured:false,order:0};
const formatDate=value=>new Date(value).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'});

function ProductModal({product,onClose,onSave,saving}){
  const [form,setForm]=useState(product?{...product,features:(product.features||[]).join(', '),techStack:(product.techStack||[]).join(', ')}:emptyForm);
  const [uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState('');
  const change=event=>{const {name,value}=event.target;setForm(current=>({...current,[name]:name==='featured'?value==='true':value}))};
  const upload=async event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){setUploadError('Product image must be 5 MB or smaller');return}setUploading(true);setUploadError('');try{const data=await uploadProductImage(file);setForm(current=>({...current,imageUrl:data.imageUrl}))}catch(error){setUploadError(error.message)}finally{setUploading(false);event.target.value=''}};
  const submit=event=>{event.preventDefault();onSave({...form,order:Number(form.order),features:form.features.split(',').map(item=>item.trim()).filter(Boolean),techStack:form.techStack.split(',').map(item=>item.trim()).filter(Boolean)})};
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal product-modal developed-product-modal" onMouseDown={event=>event.stopPropagation()} onSubmit={submit}><div className="modal-head"><div><h2>{product?'Edit Developed Product':'Add Developed Product'}</h2><p>Add software such as an online restaurant reservation app, certificate verification website, CRM, booking system, or mobile app.</p></div><button type="button" onClick={onClose}><I.X/></button></div><div className="client-form-grid">
    <label className="wide">Product name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. Online Restaurant Reservation App"/></label><label className="wide">Slug (optional)<input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={form.slug||''} onChange={change} placeholder="online-restaurant-reservation"/></label>
    <label className="wide">Product description<textarea name="description" required minLength="10" value={form.description} onChange={change} placeholder="Explain what the developed product does and who it helps."/></label>
    <label>Solution category<select name="category" value={form.category} onChange={change}>{categories.map(value=><option key={value}>{value}</option>)}</select></label><label>Product type<select name="type" value={form.type} onChange={change}>{types.map(value=><option key={value}>{value}</option>)}</select></label>
    <label>Platform<select name="platform" value={form.platform} onChange={change}>{platforms.map(value=><option key={value}>{value}</option>)}</select></label><label>Publication status<select name="status" value={form.status} onChange={change}>{Object.entries(statuses).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>
    <label className="wide">Main features<input name="features" value={form.features} onChange={change} placeholder="Table booking, Time-slot availability, Customer notifications"/></label><label className="wide">Technology stack<input name="techStack" value={form.techStack} onChange={change} placeholder="React, Node.js, PostgreSQL"/></label>
    <label className="wide">Published product URL<input name="productUrl" type="url" value={form.productUrl} onChange={change} placeholder="https://product.example.com"/></label>
    <label className="wide project-image-upload">Product image<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={upload} disabled={uploading}/><span className="project-upload-box">{form.imageUrl?<img src={form.imageUrl} alt="Product preview"/>:<I.ImagePlus/>}<b>{uploading?'Uploading image...':form.imageUrl?'Choose another image':'Upload product screenshot'}</b><small>JPG, PNG, WebP or GIF · maximum 5 MB</small></span>{uploadError&&<em>{uploadError}</em>}</label>
    <label className="wide">External image URL (optional)<input name="imageUrl" type="url" value={form.imageUrl} onChange={change}/></label><label>Featured on website<select name="featured" value={String(form.featured)} onChange={change}><option value="false">No</option><option value="true">Yes</option></select></label><label>Display order<input name="order" type="number" min="0" max="999" value={form.order} onChange={change}/></label>
  </div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving||uploading}>{saving||uploading?<I.LoaderCircle className="spin"/>:product?<I.Save/>:<I.Plus/>}{uploading?'Uploading...':saving?'Saving...':product?'Save Changes':'Add Product'}</button></div></form></div>
}

function ProductDetails({product,onClose,onEdit}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal product-modal" onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><h2>{product.name}</h2><p>{product.description}</p></div><button onClick={onClose}><I.X/></button></div><div className="user-detail-list">{[['Category',product.category],['Type',product.type],['Platform',product.platform],['Status',statuses[product.status]],['Features',product.features.join(', ')||'—'],['Technology',product.techStack.join(', ')||'—'],['Live URL',product.productUrl||'—'],['Featured',product.featured?'Yes':'No']].map(([label,value])=><p key={label}><span>{label}</span><b>{value}</b></p>)}</div><div className="modal-actions"><button onClick={onClose}>Close</button><button className="primary" onClick={()=>onEdit(product)}><I.Pencil/> Edit Product</button></div></div></div>}

export function ProductsAdminPage(){
  const [products,setProducts]=useState([]),[stats,setStats]=useState({total:0,published:0,draft:0,archived:0,featured:0}),[query,setQuery]=useState(''),[category,setCategory]=useState('All Categories'),[status,setStatus]=useState('All Status'),[modal,setModal]=useState(null),[details,setDetails]=useState(null),[toast,setToast]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const load=async()=>{setLoading(true);setError('');try{const data=await getProducts();setProducts(data.products);setStats(data.stats)}catch(err){setError(err.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>products.filter(product=>[product.name,product.description,product.category,product.type,product.platform].join(' ').toLowerCase().includes(query.toLowerCase())&&(category==='All Categories'||product.category===category)&&(status==='All Status'||statuses[product.status]===status)),[products,query,category,status]);
  const statItems=[['Developed Products',stats.total,I.Box,'blue'],['Published',stats.published,I.CircleCheckBig,'green'],['Draft',stats.draft,I.CirclePause,'orange'],['Featured',stats.featured,I.Star,'purple']];
  const save=async form=>{setSaving(true);setError('');try{if(modal?.id)await updateProduct(modal.id,form);else await createProduct(form);const editing=Boolean(modal?.id);setModal(null);flash(editing?'Product updated successfully':form.status==='PUBLISHED'?'Product created and published successfully':'Product created successfully');await load()}catch(err){setError(err.message)}finally{setSaving(false)}};
  const view=async id=>{try{setDetails((await getProduct(id)).product)}catch(err){setError(err.message)}};
  const remove=async product=>{if(!window.confirm(`Delete ${product.name}? It will be removed from public pages.`))return;try{await deleteProduct(product.id);flash('Product deleted successfully');await load()}catch(err){setError(err.message)}};
  const exportProducts=()=>{const header='Product,Category,Type,Platform,Status,Featured,URL';const rows=filtered.map(product=>[product.name,product.category,product.type,product.platform,statuses[product.status],product.featured?'Yes':'No',product.productUrl].map(value=>`"${String(value).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='mikenium-developed-products.csv';anchor.click();URL.revokeObjectURL(url)};
  return <div className="users-page products-admin-page"><div className="users-heading"><div><h1>Developed Products</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Products</span></div></div><button className="users-add" onClick={()=>setModal({})}><I.Plus/> Add Developed Product</button></div>
    <div className="product-stats">{statItems.map(([title,value,Icon,color])=><div className="card product-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{Number(value).toLocaleString()}</b><p>Live database total</p></div></div>)}</div>
    {error&&<div className="admin-inline-error"><I.CircleAlert/>{error}<button onClick={()=>setError('')}><I.X/></button></div>}
    <div className="card product-list-card"><div className="product-toolbar"><div className="users-search"><I.Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search developed products..."/></div><select value={category} onChange={event=>setCategory(event.target.value)}><option>All Categories</option>{categories.map(value=><option key={value}>{value}</option>)}</select><select value={status} onChange={event=>setStatus(event.target.value)}><option>All Status</option>{Object.values(statuses).map(value=><option key={value}>{value}</option>)}</select><button onClick={load}><I.RefreshCw/> Refresh</button><button onClick={exportProducts}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table products-table developed-products-table"><thead><tr><th>Product</th><th>Category</th><th>Type</th><th>Platform</th><th>Status</th><th>Featured</th><th>Created</th><th>Actions</th></tr></thead><tbody>{filtered.map(product=><tr key={product.id}><td><div className="product-identity">{product.imageUrl?<img className="developed-product-thumb" src={product.imageUrl} alt=""/>:<span className="product-thumb blue"><I.AppWindow/></span>}<span><b>{product.name}</b><small>{product.description}</small></span></div></td><td>{product.category}</td><td>{product.type}</td><td>{product.platform}</td><td><span className={`product-status ${statuses[product.status].toLowerCase()}`}>{statuses[product.status]}</span></td><td><I.Star className={product.featured?'feature-star active':'feature-star'} fill={product.featured?'currentColor':'none'}/></td><td>{formatDate(product.createdAt)}</td><td><div className="user-actions"><button className="edit-user" onClick={()=>setModal(product)}><I.Pencil/><span>Edit</span></button><button onClick={()=>view(product.id)}><I.Eye/></button><button className="danger" onClick={()=>remove(product)}><I.Trash2/></button></div></td></tr>)}</tbody></table>{loading?<div className="empty"><I.LoaderCircle className="spin"/><b>Loading products...</b></div>:!filtered.length&&<div className="empty"><I.SearchX/><b>No developed products found</b><span>Add products such as reservation apps or verification platforms.</span></div>}</div><div className="users-footer"><span>Showing {filtered.length} of {stats.total} database products</span></div>
    </div>
    {modal&&<ProductModal product={modal.id?modal:null} onClose={()=>setModal(null)} onSave={save} saving={saving}/>} {details&&<ProductDetails product={details} onClose={()=>setDetails(null)} onEdit={product=>{setDetails(null);setModal(product)}}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}
