import React, { useMemo, useState } from 'react';
import * as I from 'lucide-react';

const productSeed=[
  {name:'iPhone 15 Pro Max',sku:'iphone-15-pro-max',category:'Smartphones',price:1199,stock:45,status:'Published',featured:true,created:'May 21, 2024',time:'10:30 AM',Icon:I.Smartphone,tone:'slate'},
  {name:'MacBook Air M3',sku:'macbook-air-m3',category:'Laptops',price:1099,stock:32,status:'Published',featured:true,created:'May 20, 2024',time:'09:15 AM',Icon:I.Laptop,tone:'cyan'},
  {name:'Sony WH-1000XM5',sku:'sony-wh-1000xm5',category:'Headphones',price:399,stock:0,status:'Out of Stock',featured:false,created:'May 19, 2024',time:'02:45 PM',Icon:I.Headphones,tone:'dark'},
  {name:'Canon EOS R50',sku:'canon-eos-r50',category:'Cameras',price:679,stock:18,status:'Published',featured:true,created:'May 18, 2024',time:'11:20 AM',Icon:I.Camera,tone:'dark'},
  {name:'Apple Watch Series 9',sku:'apple-watch-series-9',category:'Smart Watch',price:429,stock:25,status:'Published',featured:false,created:'May 17, 2024',time:'04:10 PM',Icon:I.Watch,tone:'slate'},
  {name:'JBL Charge 5',sku:'jbl-charge-5',category:'Speakers',price:179,stock:8,status:'Draft',featured:false,created:'May 16, 2024',time:'03:30 PM',Icon:I.Speaker,tone:'dark'},
  {name:'iPad Air 5th Gen',sku:'ipad-air-5th-gen',category:'Tablets',price:599,stock:21,status:'Published',featured:true,created:'May 15, 2024',time:'01:25 PM',Icon:I.Tablet,tone:'blue'},
  {name:'Dell 27” 4K Monitor',sku:'dell-27-4k-monitor',category:'Monitors',price:349,stock:14,status:'Draft',featured:false,created:'May 14, 2024',time:'10:05 AM',Icon:I.Monitor,tone:'cyan'},
  {name:'Secretlab Titan Evo',sku:'secretlab-titan-evo',category:'Accessories',price:499,stock:7,status:'Out of Stock',featured:false,created:'May 13, 2024',time:'09:40 AM',Icon:I.Armchair,tone:'dark'},
  {name:'Logitech MX Keys',sku:'logitech-mx-keys',category:'Accessories',price:129,stock:36,status:'Published',featured:true,created:'May 12, 2024',time:'08:20 AM',Icon:I.Keyboard,tone:'slate'}
];

const productStats=[['Total Products','128','All products',I.Box,'blue'],['Published','98','Active products',I.CircleCheckBig,'green'],['Draft','15','Unpublished products',I.CirclePause,'orange'],['Out of Stock','12','Unavailable products',I.Archive,'purple']];

function ProductModal({onClose,onSave}){const [form,setForm]=useState({name:'',sku:'',category:'Accessories',price:'',stock:'',status:'Published'});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal product-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Product</h2><p>Create a product and set its inventory details.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label className="wide">Product name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. Wireless Mouse"/></label><label className="wide">SKU<input name="sku" required value={form.sku} onChange={change} placeholder="wireless-mouse-01"/></label><label>Category<select name="category" value={form.category} onChange={change}>{[...new Set(productSeed.map(p=>p.category))].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select name="status" value={form.status} onChange={change}><option>Published</option><option>Draft</option><option>Out of Stock</option></select></label><label>Price<input name="price" required type="number" min="0" step="0.01" value={form.price} onChange={change} placeholder="0.00"/></label><label>Stock<input name="stock" required type="number" min="0" value={form.stock} onChange={change} placeholder="0"/></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Product</button></div></form></div>}

export function ProductsAdminPage(){
  const [products,setProducts]=useState(productSeed),[query,setQuery]=useState(''),[sideQuery,setSideQuery]=useState(''),[category,setCategory]=useState('All Categories'),[status,setStatus]=useState('All Status'),[stockStatus,setStockStatus]=useState('All Stock Status'),[featured,setFeatured]=useState('All'),[minPrice,setMinPrice]=useState(''),[maxPrice,setMaxPrice]=useState(''),[view,setView]=useState('list'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]);
  const filtered=useMemo(()=>products.filter(p=>{const haystack=[p.name,p.sku,p.category].join(' ').toLowerCase();return haystack.includes(query.toLowerCase())&&haystack.includes(sideQuery.toLowerCase())&&(category==='All Categories'||p.category===category)&&(status==='All Status'||p.status===status)&&(stockStatus==='All Stock Status'||(stockStatus==='In Stock'?p.stock>0:p.stock===0))&&(featured==='All'||(featured==='Featured'?p.featured:!p.featured))&&(!minPrice||p.price>=Number(minPrice))&&(!maxPrice||p.price<=Number(maxPrice))}),[products,query,sideQuery,category,status,stockStatus,featured,minPrice,maxPrice]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addProduct=form=>{setProducts([{...form,price:Number(form.price),stock:Number(form.stock),featured:false,created:'Jul 14, 2026',time:'Just now',Icon:I.Package,tone:'blue'},...products]);setModal(false);flash('Product added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(p=>selected.includes(p.sku))?selected.filter(id=>!filtered.some(p=>p.sku===id)):[...new Set([...selected,...filtered.map(p=>p.sku)])]);
  const reset=()=>{setSideQuery('');setCategory('All Categories');setStatus('All Status');setStockStatus('All Stock Status');setFeatured('All');setMinPrice('');setMaxPrice('')};
  const exportProducts=()=>{const header='Product,SKU,Category,Price,Stock,Status,Featured,Created At';const rows=filtered.map(p=>[p.name,p.sku,p.category,p.price,p.stock,p.status,p.featured?'Yes':'No',`${p.created} ${p.time}`].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-products.csv';a.click();URL.revokeObjectURL(url);flash('Product list exported')};
  return <div className="users-page products-admin-page">
    <div className="users-heading"><div><h1>Products</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Products</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Product</button></div>
    <div className="product-stats">{productStats.map(([title,value,note,Icon,color])=><div className="card product-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p>{note}</p></div></div>)}</div>
    <div className="products-layout"><div className="card product-list-card"><div className="product-toolbar"><div className="users-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..."/></div><button><I.ListFilter/> Filter</button><button onClick={exportProducts}><I.Download/> Export</button><span className="view-switch"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')} title="Grid view"><I.LayoutGrid/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')} title="List view"><I.List/></button></span></div>
      {view==='list'?<div className="users-table-wrap"><table className="users-table products-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(p=>selected.includes(p.sku))} onChange={toggleAll}/></th><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th>Featured</th><th>Created At</th><th>Actions</th></tr></thead><tbody>{filtered.map(p=>{const Icon=p.Icon;return <tr key={p.sku}><td><input type="checkbox" checked={selected.includes(p.sku)} onChange={()=>toggle(p.sku)}/></td><td><div className="product-identity"><span className={`product-thumb ${p.tone}`}><Icon/></span><span><b>{p.name}</b><small>{p.sku}</small></span></div></td><td>{p.category}</td><td>${p.price.toLocaleString(undefined,{minimumFractionDigits:2})}</td><td className={p.stock===0?'stock-zero':p.stock<10?'stock-low':'stock-good'}>{p.stock}</td><td><span className={`product-status ${p.status.toLowerCase().replaceAll(' ','-')}`}>{p.status}</span></td><td><button className={`feature-star ${p.featured?'active':''}`} onClick={()=>setProducts(products.map(x=>x.sku===p.sku?{...x,featured:!x.featured}:x))}>{p.featured?<I.Star fill="currentColor"/>:<I.Star/>}</button></td><td><span className="created-date">{p.created}<small>{p.time}</small></span></td><td><div className="user-actions"><button title="Edit product" onClick={()=>flash(`Editing ${p.name}`)}><I.Pencil/></button><button className="more"><I.EllipsisVertical/></button></div></td></tr>})}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No products found</b><span>Try changing the search or filters.</span></div>}</div>:<div className="product-grid">{filtered.map(p=>{const Icon=p.Icon;return <article key={p.sku}><span className={`product-thumb ${p.tone}`}><Icon/></span><button className={`feature-star ${p.featured?'active':''}`}><I.Star fill={p.featured?'currentColor':'none'}/></button><h3>{p.name}</h3><small>{p.category} · {p.sku}</small><div><b>${p.price.toFixed(2)}</b><span>{p.stock} in stock</span></div></article>})}</div>}
      <div className="users-footer"><span>Showing 1 to {filtered.length} of 128 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>13</button><button aria-label="Next"><I.ChevronRight/></button></div></div></div>
      <aside className="product-side"><section className="card product-filters"><h3><I.Triangle/> Filters <I.ChevronUp/></h3><label>Search<input value={sideQuery} onChange={e=>setSideQuery(e.target.value)} placeholder="Search by name or SKU..."/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>All Categories</option>{[...new Set(productSeed.map(p=>p.category))].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Published</option><option>Draft</option><option>Out of Stock</option></select></label><label>Stock Status<select value={stockStatus} onChange={e=>setStockStatus(e.target.value)}><option>All Stock Status</option><option>In Stock</option><option>Out of Stock</option></select></label><label>Price Range<span className="price-range"><i>$<input type="number" min="0" value={minPrice} onChange={e=>setMinPrice(e.target.value)} placeholder="Min"/></i><em>to</em><i>$<input type="number" min="0" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} placeholder="Max"/></i></span></label><label>Featured<select value={featured} onChange={e=>setFeatured(e.target.value)}><option>All</option><option>Featured</option><option>Not Featured</option></select></label><label>Created At<span className="date-input">Select date range <I.CalendarDays/></span></label><div className="filter-actions"><button onClick={()=>flash('Filters applied')}>Apply Filters</button><button onClick={reset}>Reset</button></div></section><section className="card quick-actions"><h3>Quick Actions</h3><button onClick={()=>flash('Import products selected')}><I.Upload/> Import Products <I.ChevronRight/></button><button onClick={()=>flash('Opening product categories')}><I.Folder/> Product Categories <I.ChevronRight/></button></section></aside>
    </div>
    {modal&&<ProductModal onClose={()=>setModal(false)} onSave={addProduct}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}
