import React, { useMemo, useState } from 'react';
import * as I from 'lucide-react';

const configs={
 Users:{icon:I.Users,description:'Manage platform users, roles, and account access.',singular:'User',columns:['Name','Email','Role','Status'],rows:[['John Doe','john.doe@example.com','Editor','Active'],['Sarah Johnson','sarah.j@example.com','Admin','Active'],['Laura Wilson','laura.w@example.com','Author','Active'],['James Taylor','james.t@example.com','Subscriber','Inactive']]},
 Clients:{icon:I.Contact,description:'Manage client organizations and primary contacts.',singular:'Client',columns:['Company','Contact','Email','Status'],rows:[['TechSolutions Inc.','David Smith','david@techsolutions.com','Active'],['EazyStore','Emma Lewis','emma@eazystore.com','Active'],['CloudPeak Labs','Mark Chen','mark@cloudpeak.io','Pending']]},
 Projects:{icon:I.BriefcaseBusiness,description:'Track project delivery, clients, and progress.',singular:'Project',columns:['Project','Client','Progress','Status'],rows:[['Ecommerce Platform','EazyStore','72%','In Progress'],['Corporate Website','TechSolutions Inc.','100%','Completed'],['Mobile Banking App','CloudPeak Labs','34%','In Progress']]},
 Services:{icon:I.BadgeCheck,description:'Create and organize services offered by Mikenium.',singular:'Service',columns:['Service','Category','Projects','Status'],rows:[['Web Development','Development','45','Active'],['Mobile Development','Development','38','Active'],['UI/UX Design','Design','29','Active'],['Cloud Solutions','Infrastructure','24','Active']]},
 Products:{icon:I.Gift,description:'Manage products, pricing, inventory, and visibility.',singular:'Product',columns:['Product','Price','Stock','Status'],rows:[['Mikenium CRM','$49 / month','Unlimited','Published'],['Project Suite','$29 / month','Unlimited','Published'],['Invoice Pro','$19 / month','Unlimited','Draft']]},
 Blogs:{icon:I.NotebookTabs,description:'Write, review, and publish platform articles.',singular:'Blog post',columns:['Title','Author','Published','Status'],rows:[['How AI is Transforming Software','Laura Wilson','May 20, 2024','Published'],['Building Scalable PERN Apps','Sarah Johnson','May 18, 2024','Published'],['Cloud Migration Guide','Laura Wilson','—','Draft']]},
 Testimonials:{icon:I.MessageSquare,description:'Review and publish customer testimonials.',singular:'Testimonial',columns:['Client','Company','Rating','Status'],rows:[['Michael Brown','TechSolutions Inc.','★★★★★','Published'],['Emma Lewis','EazyStore','★★★★★','Published'],['Mark Chen','CloudPeak Labs','★★★★☆','Pending']]},
 'Contact Messages':{icon:I.Mail,description:'Read and respond to messages sent from the website.',singular:'Message',columns:['Sender','Subject','Received','Status'],rows:[['Michael Brown','New project inquiry','2 hours ago','Unread'],['Olivia Martin','Partnership opportunity','Yesterday','Read'],['Noah Davis','Product support','May 19, 2024','Replied']]},
 Pages:{icon:I.File,description:'Manage website pages, metadata, and publishing.',singular:'Page',columns:['Page','Slug','Updated','Status'],rows:[['Home','/','May 21, 2024','Published'],['About Us','/about','May 18, 2024','Published'],['Careers','/careers','May 12, 2024','Draft']]},
 Menus:{icon:I.List,description:'Organize navigation menus and their links.',singular:'Menu',columns:['Menu','Location','Items','Status'],rows:[['Main Navigation','Header','7','Active'],['Company Links','Footer','5','Active'],['Legal Links','Footer','3','Active']]},
 'Media Library':{icon:I.Images,description:'Upload and organize website images and documents.',singular:'Media item',columns:['File','Type','Size','Uploaded'],rows:[['hero-dashboard.png','Image','1.8 MB','May 21, 2024'],['company-profile.pdf','Document','3.2 MB','May 19, 2024'],['team-photo.jpg','Image','2.4 MB','May 17, 2024']]},
 Sliders:{icon:I.GalleryHorizontal,description:'Build and schedule promotional website sliders.',singular:'Slide',columns:['Slide','Position','Schedule','Status'],rows:[['Build Smarter Software','1','Always','Active'],['Launch Your Next Product','2','May 1 – Jun 30','Active'],['Cloud Services','3','Jun 1 – Jul 31','Scheduled']]},
 'Roles & Permissions':{icon:I.ShieldCheck,description:'Control staff roles and access permissions.',singular:'Role',columns:['Role','Users','Permissions','Status'],rows:[['Super Admin','1','All permissions','Locked'],['Admin','3','18 permissions','Active'],['Editor','12','9 permissions','Active'],['Author','28','4 permissions','Active']]},
 'Activity Logs':{icon:I.History,description:'Audit important changes and account activity.',singular:'Log',columns:['User','Action','IP Address','Time'],rows:[['Super Admin','Updated platform settings','192.168.1.10','2 mins ago'],['Sarah Johnson','Published a blog post','192.168.1.24','1 hour ago'],['David Smith','Updated client details','192.168.1.37','3 hours ago']]},
};

function Modal({title,onClose,onSave}){const [values,setValues]=useState({name:'',detail:''});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(values);}}><div className="modal-head"><h2>Add {title}</h2><button type="button" onClick={onClose}><I.X/></button></div><label>Name<input required autoFocus value={values.name} onChange={e=>setValues({...values,name:e.target.value})} placeholder={`${title} name`}/></label><label>Details<input value={values.detail} onChange={e=>setValues({...values,detail:e.target.value})} placeholder="Email, category, or description"/></label><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary">Save {title}</button></div></form></div>}

export function ListingPage({name}){const c=configs[name];const [query,setQuery]=useState('');const [rows,setRows]=useState(c.rows);const [modal,setModal]=useState(false);const [toast,setToast]=useState('');const filtered=useMemo(()=>rows.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase())),[rows,query]);const save=v=>{setRows([[v.name,v.detail||'—',name==='Users'?'Member':'New', 'Active'],...rows]);setModal(false);setToast(`${c.singular} added successfully`);setTimeout(()=>setToast(''),2500)};return <div className="admin-page"><PageHeading name={name} description={c.description} icon={c.icon}/><div className="page-toolbar"><div className="search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${name.toLowerCase()}...`}/></div><button className="filter"><I.ListFilter/> Filter</button><button className="primary" onClick={()=>setModal(true)}><I.Plus/> Add {c.singular}</button></div><div className="card data-card"><div className="table-wrap"><table><thead><tr><th><input type="checkbox"/></th>{c.columns.map(x=><th key={x}>{x}</th>)}<th>Actions</th></tr></thead><tbody>{filtered.map((r,idx)=><tr key={r[0]+idx}><td><input type="checkbox"/></td>{c.columns.map((x,i)=><td key={x}>{i===0?<span className="entity"><i>{r[0].slice(0,2).toUpperCase()}</i><b>{r[i]}</b></span>:i===c.columns.length-1?<span className={'status-pill '+String(r[i]).toLowerCase().replaceAll(' ','-')}>{r[i]}</span>:r[i]}</td>)}<td><button className="row-action" title="Edit"><I.Pencil/></button><button className="row-action danger" title="Delete" onClick={()=>setRows(rows.filter((_,j)=>j!==idx))}><I.Trash2/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No results found</b><span>Try a different search phrase.</span></div>}</div><div className="table-footer"><span>Showing {filtered.length} of {rows.length} entries</span><div><button disabled><I.ChevronLeft/></button><button className="current">1</button><button><I.ChevronRight/></button></div></div></div>{modal&&<Modal title={c.singular} onClose={()=>setModal(false)} onSave={save}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}</div>}

function PageHeading({name,description,icon:Icon}){return <div className="page-heading"><div><span><Icon/></span><div><h1>{name}</h1><p>{description}</p></div></div><div className="breadcrumbs">Dashboard <I.ChevronRight/> {name}</div></div>}

export function SettingsPage(){const [saved,setSaved]=useState(false);const [tab,setTab]=useState('General');return <div className="admin-page"><PageHeading name="Settings" description="Configure company, email, security, and platform preferences." icon={I.Settings}/><div className="settings-layout"><div className="card settings-tabs">{['General','Branding','Email','Notifications','Security'].map(x=><button className={tab===x?'selected':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><form className="card settings-form" onSubmit={e=>{e.preventDefault();setSaved(true);setTimeout(()=>setSaved(false),2500)}}><h2>{tab} Settings</h2><p>Update the platform's {tab.toLowerCase()} configuration.</p><div className="form-grid"><label>Company name<input defaultValue="Mikenium"/></label><label>Contact email<input type="email" defaultValue="hello@mikenium.com"/></label><label>Phone number<input defaultValue="+94 11 234 5678"/></label><label>Timezone<select defaultValue="Asia/Colombo"><option>Asia/Colombo</option><option>UTC</option></select></label><label className="wide">Company address<textarea defaultValue="Colombo, Sri Lanka"/></label><label className="switch-row wide"><span><b>Maintenance mode</b><small>Temporarily hide the public website.</small></span><input type="checkbox"/></label></div><div className="form-actions"><button className="primary"><I.Save/> Save Changes</button></div></form></div>{saved&&<div className="toast"><I.CircleCheck/>Settings saved successfully</div>}</div>}

export function BackupPage(){const [running,setRunning]=useState(false);const [backups,setBackups]=useState([['backup_2024_05_21.sql','May 21, 2024 02:30 AM','256.8 MB','Completed'],['backup_2024_05_20.sql','May 20, 2024 02:30 AM','252.1 MB','Completed'],['backup_2024_05_19.sql','May 19, 2024 02:30 AM','249.4 MB','Completed']]);const create=()=>{setRunning(true);setTimeout(()=>{setBackups([['backup_just_now.sql','Just now','257.1 MB','Completed'],...backups]);setRunning(false)},1200)};return <div className="admin-page"><PageHeading name="System Backup" description="Create, download, and monitor database backups." icon={I.DatabaseBackup}/><div className="backup-stats"><div className="card"><I.Database/><span><small>Database size</small><b>256.8 MB</b></span></div><div className="card"><I.Clock3/><span><small>Next automatic backup</small><b>Tomorrow, 02:30 AM</b></span></div><div className="card"><I.ShieldCheck/><span><small>Backup health</small><b className="success">Healthy</b></span></div></div><div className="card data-card backup-card"><div className="section-head"><div><h2>Backup History</h2><p>Automatic backups are retained for 30 days.</p></div><button className="primary" disabled={running} onClick={create}>{running?<I.LoaderCircle className="spin"/>:<I.DatabaseBackup/>}{running?'Creating backup...':'Create Backup Now'}</button></div><table><thead><tr><th>File</th><th>Created</th><th>Size</th><th>Status</th><th>Actions</th></tr></thead><tbody>{backups.map(b=><tr key={b[0]}>{b.map((x,i)=><td key={x}>{i===3?<span className="status-pill active">{x}</span>:x}</td>)}<td><button className="row-action"><I.Download/></button></td></tr>)}</tbody></table></div></div>}

export function ViewSite(){return <div className="admin-page preview-page"><PageHeading name="Website Preview" description="Preview the public Mikenium website." icon={I.Globe2}/><div className="card preview"><div className="browser"><i/><i/><i/><span>https://mikenium.com</span><I.RotateCw/></div><div className="preview-hero"><div className="preview-logo">MIKENIUM</div><h1>Building Smarter Software</h1><p>We create powerful digital experiences that help modern businesses grow.</p><button>Explore Our Services <I.ArrowRight/></button></div></div></div>}

export const listingNames=Object.keys(configs);
