import React, { useMemo, useState } from 'react';
import * as I from 'lucide-react';

const configs={
 Users:{icon:I.Users,description:'Manage platform users, roles, and account access.',singular:'User',columns:['Name','Email','Role','Status'],rows:[['John Doe','john.doe@example.com','Editor','Active'],['Sarah Johnson','sarah.j@example.com','Admin','Active'],['Laura Wilson','laura.w@example.com','Author','Active'],['James Taylor','james.t@example.com','Subscriber','Inactive']]},
 Clients:{icon:I.Contact,description:'Manage client organizations and primary contacts.',singular:'Client',columns:['Company','Contact','Email','Status'],rows:[['TechSolutions Inc.','David Smith','david@techsolutions.com','Active'],['EazyStore','Emma Lewis','emma@eazystore.com','Active'],['CloudPeak Labs','Mark Chen','mark@cloudpeak.io','Pending']]},
 Projects:{icon:I.BriefcaseBusiness,description:'Track project delivery, clients, and progress.',singular:'Project',columns:['Project','Client','Progress','Status'],rows:[['Ecommerce Platform','EazyStore','72%','In Progress'],['Corporate Website','TechSolutions Inc.','100%','Completed'],['Mobile Banking App','CloudPeak Labs','34%','In Progress']]},
 Services:{icon:I.BadgeCheck,description:'Create and organize services offered by Mikenium.',singular:'Service',columns:['Service','Category','Projects','Status'],rows:[['Web Development','Development','45','Active'],['Mobile Development','Development','38','Active'],['UI/UX Design','Design','29','Active'],['Cloud Solutions','Infrastructure','24','Active']]},
 Products:{icon:I.Gift,description:'Manage products, pricing, inventory, and visibility.',singular:'Product',columns:['Product','Price','Stock','Status'],rows:[['Mikenium CRM','$49 / month','Unlimited','Published'],['Project Suite','$29 / month','Unlimited','Published'],['Invoice Pro','$19 / month','Unlimited','Draft']]},
 Blogs:{icon:I.NotebookTabs,description:'Write, review, and publish platform articles.',singular:'Blog post',columns:['Title','Author','Published','Status'],rows:[['How AI is Transforming Software','Laura Wilson','May 20, 2024','Published'],['Building Scalable PERN Apps','Sarah Johnson','May 18, 2024','Published'],['Cloud Migration Guide','Laura Wilson','—','Draft']]},
 Testimonials:{icon:I.MessageSquare,description:'Review and publish customer testimonials.',singular:'Testimonial',columns:['Client','Company','Rating','Status'],rows:[['Michael Brown','TechSolutions Inc.','★★★★★','Published'],['Emma Lewis','EazyStore','★★★★★','Published'],['Mark Chen','CloudPeak Labs','★★★★☆','Pending']]},
 'Contact Messages':{icon:I.Mail,description:'Read and respond to messages sent from the website.',singular:'Message',columns:['Sender','Subject','Received','Status'],rows:[['Michael Brown','New project inquiry','2 hours ago','Unread'],['Olivia Martin','Partnership opportunity','Yesterday','Read'],['Noah Davis','Product support','May 19, 2024','Replied']]},
 Pages:{icon:I.File,description:'Manage website pages, metadata, and publishing.',singular:'Page',columns:['Page','Slug','Updated','Status'],rows:[['Home','/','May 21, 2024','Published'],['About Us','/about','May 18, 2024','Published'],['Careers','/careers','May 12, 2024','Draft']]},
 Menus:{icon:I.List,description:'Organize navigation menus and their links.',singular:'Menu',columns:['Menu','Location','Items','Status'],rows:[['Main Navigation','Header','7','Active'],['Company Links','Footer','5','Active'],['Legal Links','Footer','3','Active']]},
 'Media Library':{icon:I.Images,description:'Upload and organize website images and documents.',singular:'Media item',columns:['File','Type','Size','Uploaded'],rows:[['hero-dashboard.png','Image','1.8 MB','May 21, 2024'],['company-profile.pdf','Document','3.2 MB','May 19, 2024'],['team-photo.jpg','Image','2.4 MB','May 17, 2024']]},
 Sliders:{icon:I.GalleryHorizontal,description:'Build and schedule promotional website sliders.',singular:'Slide',columns:['Slide','Position','Schedule','Status'],rows:[['Build Smarter Software','1','Always','Active'],['Launch Your Next Product','2','May 1 – Jun 30','Active'],['Cloud Services','3','Jun 1 – Jul 31','Scheduled']]},
 'Roles & Permissions':{icon:I.ShieldCheck,description:'Control staff roles and access permissions.',singular:'Role',columns:['Role','Users','Permissions','Status'],rows:[['Super Admin','1','All permissions','Locked'],['Admin','3','18 permissions','Active'],['Editor','12','9 permissions','Active'],['Author','28','4 permissions','Active']]},
 'Activity Logs':{icon:I.History,description:'Audit important changes and account activity.',singular:'Log',columns:['User','Action','IP Address','Time'],rows:[['Super Admin','Updated platform settings','192.168.1.10','2 mins ago'],['Sarah Johnson','Published a blog post','192.168.1.24','1 hour ago'],['David Smith','Updated client details','192.168.1.37','3 hours ago']]},
};

function Modal({title,onClose,onSave}){const [values,setValues]=useState({name:'',detail:''});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(values);}}><div className="modal-head"><h2>Add {title}</h2><button type="button" onClick={onClose}><I.X/></button></div><label>Name<input required autoFocus value={values.name} onChange={e=>setValues({...values,name:e.target.value})} placeholder={`${title} name`}/></label><label>Details<input value={values.detail} onChange={e=>setValues({...values,detail:e.target.value})} placeholder="Email, category, or description"/></label><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary">Save {title}</button></div></form></div>}

const userSeed=[
  {name:'Super Admin',handle:'superadmin',email:'superadmin@mikenium.com',role:'Super Admin',status:'Active',verified:true,joined:'Jan 01, 2024',login:'May 21, 2024 10:30 AM',tone:'navy'},
  {name:'John Smith',handle:'johnsmith',email:'john.smith@mikenium.com',role:'Administrator',status:'Active',verified:true,joined:'Feb 14, 2024',login:'May 21, 2024 09:15 AM',tone:'amber'},
  {name:'Sarah Johnson',handle:'sarahj',email:'sarah.johnson@example.com',role:'Client',status:'Active',verified:true,joined:'Mar 05, 2024',login:'May 20, 2024 04:45 PM',tone:'rose'},
  {name:'Michael Brown',handle:'michaelb',email:'michael.brown@example.com',role:'Client',status:'Active',verified:false,joined:'Mar 18, 2024',login:'May 19, 2024 11:20 AM',tone:'blue'},
  {name:'Emily Davis',handle:'emilyd',email:'emily.davis@example.com',role:'Subscriber',status:'Active',verified:true,joined:'Apr 02, 2024',login:'May 21, 2024 08:00 AM',tone:'rose'},
  {name:'David Wilson',handle:'davidw',email:'david.wilson@example.com',role:'Client',status:'Inactive',verified:true,joined:'Apr 10, 2024',login:'—',tone:'teal'},
  {name:'Laura Martinez',handle:'lauram',email:'laura.martinez@example.com',role:'Subscriber',status:'Active',verified:true,joined:'Apr 15, 2024',login:'May 18, 2024 02:30 PM',tone:'amber'},
  {name:'James Taylor',handle:'jamest',email:'james.taylor@example.com',role:'Client',status:'Inactive',verified:false,joined:'Apr 22, 2024',login:'—',tone:'navy'},
  {name:'Olivia Anderson',handle:'oliviaa',email:'olivia.anderson@example.com',role:'Subscriber',status:'Active',verified:true,joined:'May 01, 2024',login:'May 21, 2024 07:45 AM',tone:'rose'},
  {name:'Daniel Thomas',handle:'danielt',email:'daniel.thomas@example.com',role:'Client',status:'Active',verified:true,joined:'May 05, 2024',login:'May 20, 2024 06:10 PM',tone:'blue'}
];

const userStats=[
  ['Total Users','1,248','12.5%',I.Users,'blue',true],
  ['Administrators','28','7.1%',I.ShieldCheck,'purple',true],
  ['Clients','342','8.3%',I.BriefcaseBusiness,'green',true],
  ['Subscribers','856','11.4%',I.Mail,'orange',true],
  ['Inactive Users','22','15.2%',I.UserRoundX,'pink',false]
];

function UserModal({onClose,onSave}){const [form,setForm]=useState({name:'',email:'',role:'Client'});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal user-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New User</h2><p>Create an account and assign its access level.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><label>Full name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. Alex Morgan"/></label><label>Email address<input name="email" required type="email" value={form.email} onChange={change} placeholder="alex@example.com"/></label><label>Role<select name="role" value={form.role} onChange={change}><option>Administrator</option><option>Client</option><option>Subscriber</option></select></label><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.UserPlus/> Add User</button></div></form></div>}

export function UsersPage(){
  const [users,setUsers]=useState(userSeed),[query,setQuery]=useState(''),[role,setRole]=useState('All Roles'),[status,setStatus]=useState('All Status'),[verified,setVerified]=useState('Email Verified'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]);
  const filtered=useMemo(()=>users.filter(u=>{
    const matchesQuery=[u.name,u.handle,u.email,u.role].join(' ').toLowerCase().includes(query.toLowerCase());
    return matchesQuery&&(role==='All Roles'||u.role===role)&&(status==='All Status'||u.status===status)&&(verified==='Email Verified'||(verified==='Verified'?u.verified:!u.verified));
  }),[users,query,role,status,verified]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addUser=form=>{const handle=form.name.toLowerCase().replace(/[^a-z0-9]/g,'');setUsers([{...form,handle,status:'Active',verified:false,joined:'Jul 14, 2026',login:'—',tone:'blue'},...users]);setModal(false);flash('User added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(selected.length===filtered.length?[]:filtered.map(u=>u.email));
  const exportUsers=()=>{const header='Name,Username,Email,Role,Status,Email Verified,Joined,Last Login';const rows=filtered.map(u=>[u.name,u.handle,u.email,u.role,u.status,u.verified?'Yes':'No',u.joined,u.login].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-users.csv';a.click();URL.revokeObjectURL(url);flash('User list exported')};
  return <div className="users-page">
    <div className="users-heading"><div><h1>Users</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Users</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New User</button></div>
    <div className="user-stats">{userStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up?'up':'down'}>{up?<I.ArrowUp/>:<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
    <div className="card users-table-card">
      <div className="users-toolbar"><div className="users-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search users..."/></div><select value={role} onChange={e=>setRole(e.target.value)}><option>All Roles</option><option>Super Admin</option><option>Administrator</option><option>Client</option><option>Subscriber</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Active</option><option>Inactive</option></select><select value={verified} onChange={e=>setVerified(e.target.value)}><option>Email Verified</option><option>Verified</option><option>Not Verified</option></select><div className="toolbar-spacer"/><button className="date-button"><I.CalendarDays/> May 15, 2024 - May 21, 2024 <I.ChevronDown/></button><button><I.ListFilter/> Filter</button><button onClick={exportUsers}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&selected.length===filtered.length} onChange={toggleAll}/></th><th>User</th><th>Role</th><th>Email</th><th>Status</th><th>Email Verified</th><th>Joined On <I.RotateCw/></th><th>Last Login <I.RotateCw/></th><th>Actions</th></tr></thead><tbody>{filtered.map(u=><tr key={u.email}><td><input type="checkbox" checked={selected.includes(u.email)} onChange={()=>toggle(u.email)}/></td><td><div className="user-identity"><span className={`user-avatar ${u.tone}`}>{u.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><span><b>{u.name}</b><small>@{u.handle}</small></span></div></td><td><span className={`role-pill ${u.role.toLowerCase().replace(' ','-')}`}>{u.role}</span></td><td className="user-email">{u.email}</td><td><span className={`user-status ${u.status.toLowerCase()}`}>{u.status}</span></td><td><span className={u.verified?'verified-yes':'verified-no'} title={u.verified?'Verified':'Not verified'}>{u.verified?<I.CircleCheck/>:<I.CircleX/>}</span></td><td>{u.joined}</td><td>{u.login}</td><td><div className="user-actions"><button title="Edit user" onClick={()=>flash(`Editing ${u.name}`)}><I.Pencil/></button><button title="View user" onClick={()=>flash(`Viewing ${u.name}`)}><I.Eye/></button><button className="more" title="More actions"><I.EllipsisVertical/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No users found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer"><span>Showing 1 to {filtered.length} of 1,248 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>125</button><button aria-label="Next"><I.ChevronRight/></button></div></div>
    </div>
    {modal&&<UserModal onClose={()=>setModal(false)} onSave={addUser}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}

export function ListingPage({name}){const c=configs[name];const [query,setQuery]=useState('');const [rows,setRows]=useState(c.rows);const [modal,setModal]=useState(false);const [toast,setToast]=useState('');const filtered=useMemo(()=>rows.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase())),[rows,query]);const save=v=>{setRows([[v.name,v.detail||'—',name==='Users'?'Member':'New', 'Active'],...rows]);setModal(false);setToast(`${c.singular} added successfully`);setTimeout(()=>setToast(''),2500)};return <div className="admin-page"><PageHeading name={name} description={c.description} icon={c.icon}/><div className="page-toolbar"><div className="search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${name.toLowerCase()}...`}/></div><button className="filter"><I.ListFilter/> Filter</button><button className="primary" onClick={()=>setModal(true)}><I.Plus/> Add {c.singular}</button></div><div className="card data-card"><div className="table-wrap"><table><thead><tr><th><input type="checkbox"/></th>{c.columns.map(x=><th key={x}>{x}</th>)}<th>Actions</th></tr></thead><tbody>{filtered.map((r,idx)=><tr key={r[0]+idx}><td><input type="checkbox"/></td>{c.columns.map((x,i)=><td key={x}>{i===0?<span className="entity"><i>{r[0].slice(0,2).toUpperCase()}</i><b>{r[i]}</b></span>:i===c.columns.length-1?<span className={'status-pill '+String(r[i]).toLowerCase().replaceAll(' ','-')}>{r[i]}</span>:r[i]}</td>)}<td><button className="row-action" title="Edit"><I.Pencil/></button><button className="row-action danger" title="Delete" onClick={()=>setRows(rows.filter((_,j)=>j!==idx))}><I.Trash2/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No results found</b><span>Try a different search phrase.</span></div>}</div><div className="table-footer"><span>Showing {filtered.length} of {rows.length} entries</span><div><button disabled><I.ChevronLeft/></button><button className="current">1</button><button><I.ChevronRight/></button></div></div></div>{modal&&<Modal title={c.singular} onClose={()=>setModal(false)} onSave={save}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}</div>}

const clientSeed=[
  {name:'TechSolutions Inc.',location:'New York, USA',contact:'John Smith',title:'CEO',email:'john.smith@techsolutions.com',phone:'+1 (555) 123-4567',industry:'Technology',status:'Active',joined:'Jan 15, 2024',tone:'blue'},
  {name:'HealthCare Plus',location:'Los Angeles, USA',contact:'Sarah Johnson',title:'Manager',email:'sarah.johnson@healthcareplus.com',phone:'+1 (555) 987-6543',industry:'Healthcare',status:'Active',joined:'Feb 10, 2024',tone:'green'},
  {name:'MarketHub Ltd.',location:'London, UK',contact:'Michael Brown',title:'Director',email:'michael.brown@markethub.co.uk',phone:'+44 20 7946 0958',industry:'E-commerce',status:'Active',joined:'Mar 05, 2024',tone:'purple'},
  {name:'EduTech Solutions',location:'Toronto, Canada',contact:'Emily Davis',title:'Co-founder',email:'emily.davis@edutech.ca',phone:'+1 (416) 555-0198',industry:'Education',status:'Inactive',joined:'Mar 18, 2024',tone:'orange'},
  {name:'FinSoft Systems',location:'Sydney, Australia',contact:'David Wilson',title:'CTO',email:'david.wilson@finsoft.com.au',phone:'+61 2 9123 4567',industry:'Finance',status:'Active',joined:'Apr 01, 2024',tone:'blue'},
  {name:'CloudNova',location:'Berlin, Germany',contact:'Laura Martinez',title:'Product Head',email:'laura.martinez@cloudnova.de',phone:'+49 30 12345678',industry:'Technology',status:'Active',joined:'Apr 12, 2024',tone:'cyan'},
  {name:'DesignHub Studio',location:'San Francisco, USA',contact:'James Taylor',title:'Creative Director',email:'james.taylor@designhub.com',phone:'+1 (415) 555-2671',industry:'Design',status:'Active',joined:'Apr 20, 2024',tone:'pink'},
  {name:'RetailPro Group',location:'Dubai, UAE',contact:'Olivia Anderson',title:'Operations Manager',email:'olivia.anderson@retailpro.ae',phone:'+971 50 123 4567',industry:'Retail',status:'Inactive',joined:'May 02, 2024',tone:'brown'},
  {name:'Wellness Life',location:'Singapore',contact:'Daniel Thomas',title:'Founder',email:'daniel.thomas@wellnesslife.sg',phone:'+65 9123 4567',industry:'Wellness',status:'Active',joined:'May 10, 2024',tone:'green'},
  {name:'AutoDrive Co.',location:'Tokyo, Japan',contact:'Sophia Lee',title:'CEO',email:'sophia.lee@autodrive.co.jp',phone:'+81 90 1234 5678',industry:'Automotive',status:'Active',joined:'May 14, 2024',tone:'purple'}
];

const clientStats=[['Total Clients','342','8.3%',I.Users,'blue',true],['Active Clients','245','10.6%',I.Building2,'green',true],['Inactive Clients','22','15.4%',I.Clock3,'orange',false],['Projects','156','12.5%',I.Folder,'purple',true],['Total Revenue','$256,540','9.7%',I.CircleDollarSign,'pink',true]];

function ClientModal({onClose,onSave}){const [form,setForm]=useState({name:'',contact:'',email:'',industry:'Technology',location:''});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal client-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Client</h2><p>Add a company and its primary contact.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label>Company name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. Acme Inc."/></label><label>Contact person<input name="contact" required value={form.contact} onChange={change} placeholder="Full name"/></label><label className="wide">Email address<input name="email" required type="email" value={form.email} onChange={change} placeholder="contact@company.com"/></label><label>Industry<select name="industry" value={form.industry} onChange={change}><option>Technology</option><option>Healthcare</option><option>E-commerce</option><option>Education</option><option>Finance</option><option>Design</option><option>Retail</option><option>Wellness</option><option>Automotive</option></select></label><label>Location<input name="location" required value={form.location} onChange={change} placeholder="City, Country"/></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Client</button></div></form></div>}

export function ClientsPage(){
  const [clients,setClients]=useState(clientSeed),[query,setQuery]=useState(''),[status,setStatus]=useState('All Status'),[industry,setIndustry]=useState('All Industries'),[country,setCountry]=useState('All Countries'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]);
  const filtered=useMemo(()=>clients.filter(c=>{const searchable=[c.name,c.location,c.contact,c.email,c.industry].join(' ').toLowerCase();const clientCountry=c.location.split(', ').at(-1);return searchable.includes(query.toLowerCase())&&(status==='All Status'||c.status===status)&&(industry==='All Industries'||c.industry===industry)&&(country==='All Countries'||clientCountry===country)}),[clients,query,status,industry,country]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addClient=form=>{setClients([{...form,title:'Primary Contact',phone:'—',status:'Active',joined:'Jul 14, 2026',tone:'blue'},...clients]);setModal(false);flash('Client added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(c=>selected.includes(c.email))?selected.filter(id=>!filtered.some(c=>c.email===id)):[...new Set([...selected,...filtered.map(c=>c.email)])]);
  const exportClients=()=>{const header='Client,Location,Contact Person,Title,Email,Phone,Industry,Status,Joined';const rows=filtered.map(c=>[c.name,c.location,c.contact,c.title,c.email,c.phone,c.industry,c.status,c.joined].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-clients.csv';a.click();URL.revokeObjectURL(url);flash('Client list exported')};
  return <div className="users-page clients-page">
    <div className="users-heading"><div><h1>Clients</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Clients</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Client</button></div>
    <div className="user-stats">{clientStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up?'up':'down'}>{up?<I.ArrowUp/>:<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
    <div className="card users-table-card">
      <div className="users-toolbar"><div className="users-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search clients..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Active</option><option>Inactive</option></select><select value={industry} onChange={e=>setIndustry(e.target.value)}><option>All Industries</option>{[...new Set(clientSeed.map(c=>c.industry))].map(x=><option key={x}>{x}</option>)}</select><select value={country} onChange={e=>setCountry(e.target.value)}><option>All Countries</option>{[...new Set(clientSeed.map(c=>c.location.split(', ').at(-1)))].map(x=><option key={x}>{x}</option>)}</select><div className="toolbar-spacer"/><button className="date-button"><I.CalendarDays/> May 15, 2024 - May 21, 2024 <I.ChevronDown/></button><button><I.ListFilter/> Filter</button><button onClick={exportClients}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table clients-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(c=>selected.includes(c.email))} onChange={toggleAll}/></th><th>#</th><th>Client</th><th>Contact Person</th><th>Email</th><th>Phone</th><th>Industry</th><th>Status</th><th>Joined On <I.RotateCw/></th><th>Actions</th></tr></thead><tbody>{filtered.map((c,index)=><tr key={c.email}><td><input type="checkbox" checked={selected.includes(c.email)} onChange={()=>toggle(c.email)}/></td><td>{index+1}</td><td><div className="client-identity"><span className={`client-logo ${c.tone}`}>{c.name[0]}</span><span><b>{c.name}</b><small>{c.location}</small></span></div></td><td><span className="client-contact"><b>{c.contact}</b><small>{c.title}</small></span></td><td className="user-email">{c.email}</td><td>{c.phone}</td><td><span className={`industry-pill ${c.industry.toLowerCase().replaceAll(' ','-')}`}>{c.industry}</span></td><td><span className={`user-status ${c.status.toLowerCase()}`}>{c.status}</span></td><td>{c.joined}</td><td><div className="user-actions"><button title="View client" onClick={()=>flash(`Viewing ${c.name}`)}><I.Eye/></button><button title="Edit client" onClick={()=>flash(`Editing ${c.name}`)}><I.Pencil/></button><button className="more" title="More actions"><I.EllipsisVertical/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No clients found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer"><span>Showing 1 to {filtered.length} of 342 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>35</button><button aria-label="Next"><I.ChevronRight/></button></div></div>
    </div>
    {modal&&<ClientModal onClose={()=>setModal(false)} onSave={addClient}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}

const projectSeed=[
  {name:'EazyStore – eCommerce Platform',description:'Custom eCommerce solution',client:'TechSolutions Inc.',category:'Web Development',status:'In Progress',progress:65,start:'May 01, 2024',deadline:'Jun 15, 2024',team:['JS','ED','MB'],extra:2,tone:'blue'},
  {name:'Mikenium Analytics Dashboard',description:'Analytics dashboard for SAAS',client:'DataPro Systems',category:'UI/UX Design',status:'Completed',progress:100,start:'Apr 10, 2024',deadline:'May 05, 2024',team:['LJ','DT','SW'],extra:3,tone:'green'},
  {name:'TaskFlow – Project Management Tool',description:'Project management web app',client:'InnovateX',category:'Web Development',status:'In Progress',progress:40,start:'May 05, 2024',deadline:'Jun 20, 2024',team:['JW','SL','RA'],extra:1,tone:'orange'},
  {name:'HealthCare Plus – Mobile App',description:'Healthcare mobile application',client:'Medicare Group',category:'Mobile Development',status:'Completed',progress:100,start:'Mar 15, 2024',deadline:'Apr 30, 2024',team:['AB','SK','NH'],extra:2,tone:'purple'},
  {name:'CloudNova Website',description:'Corporate website development',client:'CloudNova',category:'Web Development',status:'On Hold',progress:25,start:'May 12, 2024',deadline:'Jun 30, 2024',team:['LM','DW'],extra:0,tone:'blue'},
  {name:'FinSoft – SaaS Platform',description:'SaaS platform for finance',client:'FinSoft Ltd.',category:'Web Development',status:'In Progress',progress:70,start:'Apr 20, 2024',deadline:'Jun 10, 2024',team:['MT','KA','OP'],extra:4,tone:'green'},
  {name:'ShopHub – Marketplace App',description:'Multi-vendor marketplace app',client:'MarketHub',category:'Mobile Development',status:'Cancelled',progress:0,start:'Apr 01, 2024',deadline:'May 01, 2024',team:['JT','SB','KL'],extra:0,tone:'orange'},
  {name:'EduLearn – E-learning Platform',description:'Online learning management system',client:'EduTech Solutions',category:'Web Development',status:'Completed',progress:100,start:'Feb 10, 2024',deadline:'Mar 30, 2024',team:['ED','ML','AR'],extra:1,tone:'purple'}
];

const projectStats=[['Total Projects','156','15.2%',I.Folder,'blue',true],['Completed','78','12.8%',I.SquareCheckBig,'green',true],['In Progress','48','8.4%',I.Clock3,'orange',true],['On Hold','12','3.1%',I.CirclePause,'purple',false],['Cancelled','18','2.6%',I.CircleOff,'pink',false]];

function ProjectModal({onClose,onSave}){const [form,setForm]=useState({name:'',description:'',client:'',category:'Web Development',deadline:''});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal project-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Project</h2><p>Create a project and assign its delivery details.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label className="wide">Project name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. Customer Portal"/></label><label className="wide">Description<input name="description" required value={form.description} onChange={change} placeholder="Short project description"/></label><label>Client<input name="client" required value={form.client} onChange={change} placeholder="Client company"/></label><label>Category<select name="category" value={form.category} onChange={change}><option>Web Development</option><option>Mobile Development</option><option>UI/UX Design</option></select></label><label className="wide">Deadline<input name="deadline" required type="date" value={form.deadline} onChange={change}/></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Project</button></div></form></div>}

export function ProjectsPage(){
  const [projects,setProjects]=useState(projectSeed),[query,setQuery]=useState(''),[client,setClient]=useState('All Clients'),[status,setStatus]=useState('All Status'),[category,setCategory]=useState('All Categories'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]);
  const filtered=useMemo(()=>projects.filter(p=>[p.name,p.description,p.client,p.category].join(' ').toLowerCase().includes(query.toLowerCase())&&(client==='All Clients'||p.client===client)&&(status==='All Status'||p.status===status)&&(category==='All Categories'||p.category===category)),[projects,query,client,status,category]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addProject=form=>{const deadline=form.deadline?new Date(`${form.deadline}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'}):'—';setProjects([{...form,deadline,status:'In Progress',progress:0,start:'Jul 14, 2026',team:['SA'],extra:0,tone:'blue'},...projects]);setModal(false);flash('Project added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(p=>selected.includes(p.name))?selected.filter(id=>!filtered.some(p=>p.name===id)):[...new Set([...selected,...filtered.map(p=>p.name)])]);
  const exportProjects=()=>{const header='Project,Description,Client,Category,Status,Progress,Start Date,Deadline';const rows=filtered.map(p=>[p.name,p.description,p.client,p.category,p.status,`${p.progress}%`,p.start,p.deadline].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-projects.csv';a.click();URL.revokeObjectURL(url);flash('Project list exported')};
  return <div className="users-page projects-page">
    <div className="users-heading"><div><h1>Projects</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Projects</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Project</button></div>
    <div className="user-stats">{projectStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up?'up':'down'}>{up?<I.ArrowUp/>:<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
    <div className="card users-table-card">
      <div className="users-toolbar"><div className="users-search project-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects..."/></div><select value={client} onChange={e=>setClient(e.target.value)}><option>All Clients</option>{[...new Set(projectSeed.map(p=>p.client))].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Completed</option><option>In Progress</option><option>On Hold</option><option>Cancelled</option></select><select value={category} onChange={e=>setCategory(e.target.value)}><option>All Categories</option><option>Web Development</option><option>Mobile Development</option><option>UI/UX Design</option></select><div className="toolbar-spacer"/><button className="date-button"><I.CalendarDays/> May 15, 2024 - May 21, 2024 <I.ChevronDown/></button><button><I.ListFilter/> Filter</button><button onClick={exportProjects}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table projects-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(p=>selected.includes(p.name))} onChange={toggleAll}/></th><th>#</th><th>Project Name</th><th>Client</th><th>Category</th><th>Status</th><th>Progress</th><th>Start Date <I.RotateCw/></th><th>Deadline <I.RotateCw/></th><th>Team</th><th>Actions</th></tr></thead><tbody>{filtered.map((p,index)=><tr key={p.name}><td><input type="checkbox" checked={selected.includes(p.name)} onChange={()=>toggle(p.name)}/></td><td>{index+1}</td><td><span className="project-name"><b>{p.name}</b><small>{p.description}</small></span></td><td><span className="project-client"><i className={p.tone}>{p.client[0]}</i>{p.client}</span></td><td><span className={`category-pill ${p.category.toLowerCase().replaceAll(/[^a-z]+/g,'-')}`}>{p.category}</span></td><td><span className={`project-status ${p.status.toLowerCase().replaceAll(' ','-')}`}>{p.status}</span></td><td><div className="project-progress"><span>{p.progress}%</span><i><b className={p.status==='Completed'?'done':''} style={{width:`${p.progress}%`}}/></i></div></td><td>{p.start}</td><td className={p.status==='Completed'?'deadline-done':'deadline-late'}>{p.deadline}</td><td><div className="project-team">{p.team.map((member,i)=><i className={`face face-${i}`} key={member}>{member}</i>)}{p.extra>0&&<span>+{p.extra}</span>}</div></td><td><button className="project-more" title="Project actions" onClick={()=>flash(`Actions for ${p.name}`)}><I.EllipsisVertical/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No projects found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer"><span>Showing 1 to {filtered.length} of 156 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>20</button><button aria-label="Next"><I.ChevronRight/></button></div></div>
    </div>
    {modal&&<ProjectModal onClose={()=>setModal(false)} onSave={addProject}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}

const serviceSeed=[
  {name:'Web Development',description:'Custom websites and web applications',category:'Development',type:'Core Service',status:'Published',order:1,created:'May 10, 2024',Icon:I.CodeXml,tone:'blue'},
  {name:'Mobile Development',description:'iOS and Android app development',category:'Development',type:'Core Service',status:'Published',order:2,created:'May 11, 2024',Icon:I.Smartphone,tone:'green'},
  {name:'UI/UX Design',description:'User interface and experience design',category:'Design',type:'Core Service',status:'Published',order:3,created:'May 12, 2024',Icon:I.TabletSmartphone,tone:'orange'},
  {name:'Cloud Solutions',description:'Scalable cloud infrastructure',category:'Cloud',type:'Core Service',status:'Published',order:4,created:'May 13, 2024',Icon:I.Cloud,tone:'purple'},
  {name:'E-Commerce Solutions',description:'Online store development',category:'Development',type:'Core Service',status:'Draft',order:5,created:'May 14, 2024',Icon:I.ShoppingCart,tone:'pink'},
  {name:'Maintenance & Support',description:'Ongoing maintenance and support',category:'Support',type:'Support Service',status:'Published',order:6,created:'May 15, 2024',Icon:I.Settings,tone:'cyan'},
  {name:'Digital Marketing',description:'SEO, SEM and social media marketing',category:'Marketing',type:'Support Service',status:'Inactive',order:7,created:'May 16, 2024',Icon:I.ChartNoAxesCombined,tone:'purple'},
  {name:'Cyber Security',description:'Security assessment and protection',category:'Security',type:'Support Service',status:'Published',order:8,created:'May 17, 2024',Icon:I.ShieldCheck,tone:'yellow'}
];

const serviceStats=[['Total Services','24','14.3%',I.Package,'purple',true],['Published','20','11.1%',I.SquareCheckBig,'green',true],['Draft','2','33.3%',I.Clock3,'orange',false],['Inactive','2','0%',I.CirclePause,'blue',null],['Trash','0','0%',I.Trash2,'pink',null]];

function ServiceModal({onClose,onSave}){const [form,setForm]=useState({name:'',description:'',category:'Development',type:'Core Service',status:'Published'});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal service-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Service</h2><p>Create a service and configure its visibility.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label className="wide">Service name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. API Development"/></label><label className="wide">Description<input name="description" required value={form.description} onChange={change} placeholder="Short service description"/></label><label>Category<select name="category" value={form.category} onChange={change}><option>Development</option><option>Design</option><option>Cloud</option><option>Support</option><option>Marketing</option><option>Security</option></select></label><label>Service type<select name="type" value={form.type} onChange={change}><option>Core Service</option><option>Support Service</option></select></label><label className="wide">Status<select name="status" value={form.status} onChange={change}><option>Published</option><option>Draft</option><option>Inactive</option></select></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Service</button></div></form></div>}

export function ServicesPage(){
  const [services,setServices]=useState(serviceSeed),[query,setQuery]=useState(''),[category,setCategory]=useState('All Categories'),[status,setStatus]=useState('All Status'),[type,setType]=useState('All Service Types'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]);
  const filtered=useMemo(()=>services.filter(s=>[s.name,s.description,s.category,s.type].join(' ').toLowerCase().includes(query.toLowerCase())&&(category==='All Categories'||s.category===category)&&(status==='All Status'||s.status===status)&&(type==='All Service Types'||s.type===type)),[services,query,category,status,type]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addService=form=>{setServices([{...form,order:services.length+1,created:'Jul 14, 2026',Icon:I.Box,tone:'blue'},...services]);setModal(false);flash('Service added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(s=>selected.includes(s.name))?selected.filter(id=>!filtered.some(s=>s.name===id)):[...new Set([...selected,...filtered.map(s=>s.name)])]);
  const exportServices=()=>{const header='Service,Description,Category,Type,Status,Order,Created At';const rows=filtered.map(s=>[s.name,s.description,s.category,s.type,s.status,s.order,s.created].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-services.csv';a.click();URL.revokeObjectURL(url);flash('Service list exported')};
  return <div className="users-page services-page">
    <div className="users-heading"><div><h1>Services</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Services</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Service</button></div>
    <div className="user-stats">{serviceStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up===false?'down':'up'}>{up===true&&<I.ArrowUp/>}{up===false&&<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
    <div className="card users-table-card">
      <div className="users-toolbar"><div className="users-search service-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search services..."/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option>All Categories</option>{[...new Set(serviceSeed.map(s=>s.category))].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Published</option><option>Draft</option><option>Inactive</option></select><select value={type} onChange={e=>setType(e.target.value)}><option>All Service Types</option><option>Core Service</option><option>Support Service</option></select><div className="toolbar-spacer"/><button><I.ListFilter/> Filter</button><button onClick={exportServices}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table services-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(s=>selected.includes(s.name))} onChange={toggleAll}/></th><th>#</th><th>Service Name</th><th>Category</th><th>Type</th><th>Status</th><th>Order</th><th>Created At</th><th>Actions</th></tr></thead><tbody>{filtered.map((s,index)=>{const Icon=s.Icon;return <tr key={s.name}><td><input type="checkbox" checked={selected.includes(s.name)} onChange={()=>toggle(s.name)}/></td><td>{index+1}</td><td><div className="service-identity"><span className={`service-icon ${s.tone}`}><Icon/></span><span><b>{s.name}</b><small>{s.description}</small></span></div></td><td><span className={`service-category ${s.category.toLowerCase()}`}>{s.category}</span></td><td><span className={`service-type ${s.type.startsWith('Core')?'core':'support'}`}>{s.type.startsWith('Core')?<I.Box/>:<I.Headphones/>}{s.type}</span></td><td><span className={`service-status ${s.status.toLowerCase()}`}>{s.status}</span></td><td><span className="service-order"><I.GripVertical/>{s.order}</span></td><td>{s.created}</td><td><div className="user-actions"><button title="Edit service" onClick={()=>flash(`Editing ${s.name}`)}><I.Pencil/></button><button title="View service" onClick={()=>flash(`Viewing ${s.name}`)}><I.Eye/></button><button className="more" title="More actions"><I.EllipsisVertical/></button></div></td></tr>})}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No services found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer"><span>Showing 1 to {filtered.length} of 24 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>3</button><button aria-label="Next"><I.ChevronRight/></button></div></div>
    </div>
    {modal&&<ServiceModal onClose={()=>setModal(false)} onSave={addService}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}

const productSeed=[
  {name:'iPhone 15 Pro Max',sku:'iphone-15-pro-max',category:'Smartphones',price:1199,stock:45,status:'Published',featured:true,created:'May 21, 2024',time:'10:30 AM',Icon:I.Smartphone,tone:'slate'},
  {name:'MacBook Air M3',sku:'macbook-air-m3',category:'Laptops',price:1099,stock:32,status:'Published',featured:true,created:'May 20, 2024',time:'09:15 AM',Icon:I.Laptop,tone:'cyan'},
  {name:'Sony WH-1000XM5',sku:'sony-wh-1000xm5',category:'Headphones',price:399,stock:0,status:'Out of Stock',featured:false,created:'May 19, 2024',time:'02:45 PM',Icon:I.Headphones,tone:'dark'},
  {name:'Canon EOS R50',sku:'canon-eos-r50',category:'Cameras',price:679,stock:18,status:'Published',featured:true,created:'May 18, 2024',time:'11:20 AM',Icon:I.Camera,tone:'dark'},
  {name:'Apple Watch Series 9',sku:'apple-watch-series-9',category:'Smart Watch',price:429,stock:25,status:'Published',featured:false,created:'May 17, 2024',time:'04:10 PM',Icon:I.Watch,tone:'slate'},
  {name:'JBL Charge 5',sku:'jbl-charge-5',category:'Speakers',price:179,stock:8,status:'Draft',featured:false,created:'May 16, 2024',time:'03:30 PM',Icon:I.Speaker,tone:'dark'},
  {name:'iPad Air 5th Gen',sku:'ipad-air-5th-gen',category:'Tablets',price:599,stock:21,status:'Published',featured:true,created:'May 15, 2024',time:'01:25 PM',Icon:I.Tablet,tone:'blue'},
  {name:'Dell 27” 4K Monitor',sku:'dell-27-4k-monitor',category:'Monitors',price:349,stock:14,status:'Draft',featured:false,created:'May 14, 2024',time:'10:05 AM',Icon:I.Monitor,tone:'cyan'},
  {name:'Secretlab Titan Evo',sku:'secretlab-titan-evo',category:'Accessories',price:499,stock:7,status:'Out of Stock',featured:false,created:'May 13, 2024',time:'09:40 AM',Icon:I.Armchair,tone:'dark'},
  {name:'Logitech MX Keys',sku:'logitech-mx-keys',category:'Accessories',price:129,stock:36,status:'Published',featured:true,created:'May 12, 2024',time:'08:20 AM',Icon:I.Keyboard,tone:'slate'}
];

const productStats=[['Total Products','128','All products',I.Box,'blue'],['Published','98','Active products',I.CircleCheckBig,'green'],['Draft','15','Unpublished products',I.CirclePause,'orange'],['Out of Stock','12','Unavailable products',I.Archive,'purple']];

function ProductModal({onClose,onSave}){const [form,setForm]=useState({name:'',sku:'',category:'Accessories',price:'',stock:'',status:'Published'});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal product-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Product</h2><p>Create a product and set its inventory details.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label className="wide">Product name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. Wireless Mouse"/></label><label className="wide">SKU<input name="sku" required value={form.sku} onChange={change} placeholder="wireless-mouse-01"/></label><label>Category<select name="category" value={form.category} onChange={change}>{[...new Set(productSeed.map(p=>p.category))].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select name="status" value={form.status} onChange={change}><option>Published</option><option>Draft</option><option>Out of Stock</option></select></label><label>Price<input name="price" required type="number" min="0" step="0.01" value={form.price} onChange={change} placeholder="0.00"/></label><label>Stock<input name="stock" required type="number" min="0" value={form.stock} onChange={change} placeholder="0"/></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Product</button></div></form></div>}

export function ProductsAdminPage(){
  const [products,setProducts]=useState(productSeed),[query,setQuery]=useState(''),[sideQuery,setSideQuery]=useState(''),[category,setCategory]=useState('All Categories'),[status,setStatus]=useState('All Status'),[stockStatus,setStockStatus]=useState('All Stock Status'),[featured,setFeatured]=useState('All'),[minPrice,setMinPrice]=useState(''),[maxPrice,setMaxPrice]=useState(''),[view,setView]=useState('list'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]);
  const filtered=useMemo(()=>products.filter(p=>{const haystack=[p.name,p.sku,p.category].join(' ').toLowerCase();return haystack.includes(query.toLowerCase())&&haystack.includes(sideQuery.toLowerCase())&&(category==='All Categories'||p.category===category)&&(status==='All Status'||p.status===status)&&(stockStatus==='All Stock Status'||(stockStatus==='In Stock'?p.stock>0:p.stock===0))&&(featured==='All'||(featured==='Featured'?p.featured:!p.featured))&&(!minPrice||p.price>=Number(minPrice))&&(!maxPrice||p.price<=Number(maxPrice))}),[products,query,sideQuery,category,status,stockStatus,featured,minPrice,maxPrice]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addProduct=form=>{setProducts([{...form,price:Number(form.price),stock:Number(form.stock),featured:false,created:'Jul 14, 2026',time:'Just now',Icon:I.Package,tone:'blue'},...products]);setModal(false);flash('Product added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(p=>selected.includes(p.sku))?selected.filter(id=>!filtered.some(p=>p.sku===id)):[...new Set([...selected,...filtered.map(p=>p.sku)])]);
  const reset=()=>{setSideQuery('');setCategory('All Categories');setStatus('All Status');setStockStatus('All Stock Status');setFeatured('All');setMinPrice('');setMaxPrice('')};
  const exportProducts=()=>{const header='Product,SKU,Category,Price,Stock,Status,Featured,Created At';const rows=filtered.map(p=>[p.name,p.sku,p.category,p.price,p.stock,p.status,p.featured?'Yes':'No',`${p.created} ${p.time}`].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-products.csv';a.click();URL.revokeObjectURL(url);flash('Product list exported')};
  return <div className="users-page products-admin-page">
    <div className="users-heading"><div><h1>Products</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Products</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Product</button></div>
    <div className="product-stats">{productStats.map(([title,value,note,Icon,color])=><div className="card product-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p>{note}</p></div></div>)}</div>
    <div className="products-layout"><div className="card product-list-card"><div className="product-toolbar"><div className="users-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..."/></div><button><I.ListFilter/> Filter</button><button onClick={exportProducts}><I.Download/> Export</button><span className="view-switch"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')} title="Grid view"><I.LayoutGrid/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')} title="List view"><I.List/></button></span></div>
      {view==='list'?<div className="users-table-wrap"><table className="users-table products-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(p=>selected.includes(p.sku))} onChange={toggleAll}/></th><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th>Featured</th><th>Created At</th><th>Actions</th></tr></thead><tbody>{filtered.map(p=>{const Icon=p.Icon;return <tr key={p.sku}><td><input type="checkbox" checked={selected.includes(p.sku)} onChange={()=>toggle(p.sku)}/></td><td><div className="product-identity"><span className={`product-thumb ${p.tone}`}><Icon/></span><span><b>{p.name}</b><small>{p.sku}</small></span></div></td><td>{p.category}</td><td>${p.price.toLocaleString(undefined,{minimumFractionDigits:2})}</td><td className={p.stock===0?'stock-zero':p.stock<10?'stock-low':'stock-good'}>{p.stock}</td><td><span className={`product-status ${p.status.toLowerCase().replaceAll(' ','-')}`}>{p.status}</span></td><td><button className={`feature-star ${p.featured?'active':''}`} onClick={()=>setProducts(products.map(x=>x.sku===p.sku?{...x,featured:!x.featured}:x))}>{p.featured?<I.Star fill="currentColor"/>:<I.Star/>}</button></td><td><span className="created-date">{p.created}<small>{p.time}</small></span></td><td><div className="user-actions"><button title="Edit product" onClick={()=>flash(`Editing ${p.name}`)}><I.Pencil/></button><button className="more"><I.EllipsisVertical/></button></div></td></tr>})}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No products found</b><span>Try changing the search or filters.</span></div>}</div>:<div className="product-grid">{filtered.map(p=>{const Icon=p.Icon;return <article key={p.sku}><span className={`product-thumb ${p.tone}`}><Icon/></span><button className={`feature-star ${p.featured?'active':''}`}><I.Star fill={p.featured?'currentColor':'none'}/></button><h3>{p.name}</h3><small>{p.category} · {p.sku}</small><div><b>${p.price.toFixed(2)}</b><span>{p.stock} in stock</span></div></article>})}</div>}
      <div className="users-footer"><span>Showing 1 to {filtered.length} of 128 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>13</button><button aria-label="Next"><I.ChevronRight/></button></div></div></div>
      <aside className="product-side"><section className="card product-filters"><h3><I.Triangle/> Filters <I.ChevronUp/></h3><label>Search<input value={sideQuery} onChange={e=>setSideQuery(e.target.value)} placeholder="Search by name or SKU..."/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>All Categories</option>{[...new Set(productSeed.map(p=>p.category))].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Published</option><option>Draft</option><option>Out of Stock</option></select></label><label>Stock Status<select value={stockStatus} onChange={e=>setStockStatus(e.target.value)}><option>All Stock Status</option><option>In Stock</option><option>Out of Stock</option></select></label><label>Price Range<span className="price-range"><i>$<input type="number" min="0" value={minPrice} onChange={e=>setMinPrice(e.target.value)} placeholder="Min"/></i><em>to</em><i>$<input type="number" min="0" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} placeholder="Max"/></i></span></label><label>Featured<select value={featured} onChange={e=>setFeatured(e.target.value)}><option>All</option><option>Featured</option><option>Not Featured</option></select></label><label>Created At<span className="date-input">Select date range <I.CalendarDays/></span></label><div className="filter-actions"><button onClick={()=>flash('Filters applied')}>Apply Filters</button><button onClick={reset}>Reset</button></div></section><section className="card quick-actions"><h3>Quick Actions</h3><button onClick={()=>flash('Import products selected')}><I.Upload/> Import Products <I.ChevronRight/></button><button onClick={()=>flash('Opening product categories')}><I.Folder/> Product Categories <I.ChevronRight/></button></section></aside>
    </div>
    {modal&&<ProductModal onClose={()=>setModal(false)} onSave={addProduct}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}

const blogSeed=[
  {title:'The Future of Web Development in 2024',slug:'/future-of-web-development-2024',author:'John Smith',category:'Technology',status:'Published',views:1245,date:'May 20, 2024',time:'10:30 AM',thumb:0,tone:'amber'},
  {title:'Top 10 Mobile App Design Trends',slug:'/top-10-mobile-app-design-trends',author:'Sarah Johnson',category:'Design',status:'Published',views:987,date:'May 18, 2024',time:'09:15 AM',thumb:1,tone:'rose'},
  {title:'How Digital Marketing Can Grow Your Business',slug:'/digital-marketing-can-grow-your-business',author:'Michael Brown',category:'Marketing',status:'Published',views:2156,date:'May 15, 2024',time:'02:45 PM',thumb:2,tone:'blue'},
  {title:'Understanding Cloud Computing Benefits',slug:'/understanding-cloud-computing-benefits',author:'Emily Davis',category:'Technology',status:'Draft',views:null,date:'—',time:'',thumb:3,tone:'rose'},
  {title:'Best Practices for Remote Team Management',slug:'/best-practices-for-remote-team-management',author:'David Wilson',category:'Business',status:'Scheduled',views:null,date:'May 25, 2024',time:'08:00 AM',thumb:4,tone:'amber'},
  {title:'E-commerce Security: Protecting Your Store',slug:'/ecommerce-security-protecting-your-store',author:'Laura Martinez',category:'E-commerce',status:'Published',views:1673,date:'May 12, 2024',time:'11:20 AM',thumb:5,tone:'rose'},
  {title:'AI in Business: Opportunities and Challenges',slug:'/ai-in-business-opportunities-challenges',author:'James Taylor',category:'Technology',status:'Draft',views:null,date:'—',time:'',thumb:6,tone:'blue'},
  {title:'SEO Tips to Rank Higher in Search Engines',slug:'/seo-tips-rank-higher-search-engines',author:'Olivia Anderson',category:'SEO',status:'Published',views:2834,date:'May 10, 2024',time:'04:10 PM',thumb:7,tone:'rose'}
];

const blogStats=[['Total Blogs','48','14.3%',I.NotebookText,'blue',true],['Published','36','16.7%',I.CircleCheckBig,'green',true],['Draft','8','11.1%',I.Pencil,'orange',false],['Scheduled','2','2.6%',I.CalendarDays,'purple',true],['Trash','2','0%',I.Trash2,'pink',true]];

function BlogModal({onClose,onSave}){const [form,setForm]=useState({title:'',slug:'',author:'John Smith',category:'Technology',status:'Draft'});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal blog-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Blog</h2><p>Create a post and configure its publishing state.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label className="wide">Blog title<input name="title" required autoFocus value={form.title} onChange={change} placeholder="Article title"/></label><label className="wide">Slug<input name="slug" required value={form.slug} onChange={change} placeholder="/article-slug"/></label><label>Author<select name="author" value={form.author} onChange={change}>{[...new Set(blogSeed.map(b=>b.author))].map(x=><option key={x}>{x}</option>)}</select></label><label>Category<select name="category" value={form.category} onChange={change}>{[...new Set(blogSeed.map(b=>b.category))].map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Status<select name="status" value={form.status} onChange={change}><option>Draft</option><option>Published</option><option>Scheduled</option></select></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Blog</button></div></form></div>}

export function BlogsAdminPage(){
  const [blogs,setBlogs]=useState(blogSeed),[query,setQuery]=useState(''),[category,setCategory]=useState('All Categories'),[author,setAuthor]=useState('All Authors'),[status,setStatus]=useState('All Status'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]);
  const filtered=useMemo(()=>blogs.filter(b=>[b.title,b.slug,b.author,b.category].join(' ').toLowerCase().includes(query.toLowerCase())&&(category==='All Categories'||b.category===category)&&(author==='All Authors'||b.author===author)&&(status==='All Status'||b.status===status)),[blogs,query,category,author,status]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addBlog=form=>{setBlogs([{...form,views:null,date:form.status==='Published'?'Jul 14, 2026':'—',time:form.status==='Published'?'Just now':'',thumb:0,tone:'blue'},...blogs]);setModal(false);flash('Blog added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(b=>selected.includes(b.slug))?selected.filter(id=>!filtered.some(b=>b.slug===id)):[...new Set([...selected,...filtered.map(b=>b.slug)])]);
  const exportBlogs=()=>{const header='Title,Slug,Author,Category,Status,Views,Published On';const rows=filtered.map(b=>[b.title,b.slug,b.author,b.category,b.status,b.views??'',`${b.date} ${b.time}`].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-blogs.csv';a.click();URL.revokeObjectURL(url);flash('Blog list exported')};
  return <div className="users-page blogs-admin-page">
    <div className="users-heading"><div><h1>Blogs</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Blogs</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Blog</button></div>
    <div className="user-stats">{blogStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up?'up':'down'}>{up?<I.ArrowUp/>:<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
    <div className="card users-table-card"><div className="users-toolbar"><div className="users-search blog-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search blogs..."/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option>All Categories</option>{[...new Set(blogSeed.map(b=>b.category))].map(x=><option key={x}>{x}</option>)}</select><select value={author} onChange={e=>setAuthor(e.target.value)}><option>All Authors</option>{[...new Set(blogSeed.map(b=>b.author))].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Published</option><option>Draft</option><option>Scheduled</option></select><div className="toolbar-spacer"/><button className="date-button"><I.CalendarDays/> May 15, 2024 - May 21, 2024 <I.ChevronDown/></button><button><I.ListFilter/> Filter</button><button onClick={exportBlogs}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table blogs-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(b=>selected.includes(b.slug))} onChange={toggleAll}/></th><th>Blog</th><th>Author</th><th>Category</th><th>Status</th><th>Views</th><th>Published On <I.RotateCw/></th><th>Actions</th></tr></thead><tbody>{filtered.map(b=><tr key={b.slug}><td><input type="checkbox" checked={selected.includes(b.slug)} onChange={()=>toggle(b.slug)}/></td><td><div className="blog-identity"><span className={`blog-thumb thumb-${b.thumb}`}/><span><b>{b.title}</b><small>{b.slug}</small></span></div></td><td><span className="blog-author"><i className={b.tone}>{b.author.split(' ').map(x=>x[0]).join('')}</i>{b.author}</span></td><td><span className={`blog-category ${b.category.toLowerCase().replaceAll(/[^a-z]+/g,'-')}`}>{b.category}</span></td><td><span className={`blog-status ${b.status.toLowerCase()}`}>{b.status}</span></td><td><span className="blog-views">{b.views?<><I.Eye/>{b.views.toLocaleString()}</>:'—'}</span></td><td><span className="created-date">{b.date}<small>{b.time}</small></span></td><td><div className="user-actions">{b.status!=='Draft'&&<button title="View blog" onClick={()=>flash(`Viewing ${b.title}`)}><I.Eye/></button>}<button title="Edit blog" onClick={()=>flash(`Editing ${b.title}`)}><I.Pencil/></button><button className="more"><I.EllipsisVertical/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No blogs found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer"><span>Showing 1 to {filtered.length} of 48 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>6</button><button aria-label="Next"><I.ChevronRight/></button></div></div>
    </div>{modal&&<BlogModal onClose={()=>setModal(false)} onSave={addBlog}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}

const testimonialSeed=[
  {client:'John Smith',company:'TechSolutions Inc.',text:'Mikenium delivered an exceptional product that exceeded our expectations. Their team was professional, responsive, and highly skilled.',service:'Web Development',rating:5,status:'Published',date:'May 21, 2024',time:'10:30 AM',tone:'amber'},
  {client:'Sarah Johnson',company:'HealthCare Plus',text:'Great experience working with the Mikenium team. They understood our requirements perfectly and delivered on time.',service:'Mobile App',rating:5,status:'Published',date:'May 20, 2024',time:'09:15 AM',tone:'rose'},
  {client:'Michael Brown',company:'MarketHub Ltd.',text:'The design and functionality are outstanding. Mikenium is our go-to partner for all our digital needs.',service:'UI/UX Design',rating:4.5,status:'Published',date:'May 18, 2024',time:'02:45 PM',tone:'blue'},
  {client:'Emily Davis',company:'CloudNova',text:'Very talented team! They provided innovative solutions that helped us grow our business.',service:'Cloud Solutions',rating:5,status:'Published',date:'May 17, 2024',time:'01:20 PM',tone:'rose'},
  {client:'David Wilson',company:'FinSoft Systems',text:'Professional, reliable, and supportive throughout the entire project. Highly recommend Mikenium!',service:'Web Development',rating:5,status:'Pending',date:'—',time:'',tone:'amber'},
  {client:'Laura Martinez',company:'EduTech Solutions',text:'They transformed our ideas into a beautiful product. Excellent communication and support.',service:'E-learning Platform',rating:4.5,status:'Pending',date:'—',time:'',tone:'rose'},
  {client:'James Taylor',company:'DesignHub Studio',text:'Good work and great support. Will definitely work with them again.',service:'UI/UX Design',rating:5,status:'Hidden',date:'May 10, 2024',time:'04:10 PM',tone:'amber'},
  {client:'Olivia Anderson',company:'AutoDrive Co.',text:'Amazing team with strong technical expertise. Very happy with the results!',service:'Mobile App',rating:4.5,status:'Hidden',date:'May 09, 2024',time:'11:30 AM',tone:'rose'}
];

const testimonialStats=[['Total Testimonials','86','12.8%',I.MessageSquareText,'blue',true],['Published','71','14.3%',I.SquareCheckBig,'green',true],['Pending','9','10.0%',I.Clock3,'orange',false],['Hidden','4','0%',I.EyeOff,'purple',null],['Trash','2','33.3%',I.Trash2,'pink',false]];

function TestimonialModal({onClose,onSave}){const [form,setForm]=useState({client:'',company:'',text:'',service:'Web Development',rating:'5',status:'Pending'});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal testimonial-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Testimonial</h2><p>Add client feedback for review or publication.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label>Client name<input name="client" required autoFocus value={form.client} onChange={change} placeholder="Full name"/></label><label>Company<input name="company" required value={form.company} onChange={change} placeholder="Company name"/></label><label className="wide">Testimonial<textarea name="text" required value={form.text} onChange={change} placeholder="Client feedback"/></label><label>Service<select name="service" value={form.service} onChange={change}>{[...new Set(testimonialSeed.map(t=>t.service))].map(x=><option key={x}>{x}</option>)}</select></label><label>Rating<select name="rating" value={form.rating} onChange={change}><option value="5">5 stars</option><option value="4.5">4.5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option></select></label><label className="wide">Status<select name="status" value={form.status} onChange={change}><option>Pending</option><option>Published</option><option>Hidden</option></select></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Testimonial</button></div></form></div>}

export function TestimonialsPage(){
  const [testimonials,setTestimonials]=useState(testimonialSeed),[query,setQuery]=useState(''),[status,setStatus]=useState('All Status'),[rating,setRating]=useState('All Ratings'),[service,setService]=useState('All Services'),[client,setClient]=useState('All Clients'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]);
  const filtered=useMemo(()=>testimonials.filter(t=>[t.client,t.company,t.text,t.service].join(' ').toLowerCase().includes(query.toLowerCase())&&(status==='All Status'||t.status===status)&&(rating==='All Ratings'||t.rating===Number(rating))&&(service==='All Services'||t.service===service)&&(client==='All Clients'||t.client===client)),[testimonials,query,status,rating,service,client]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addTestimonial=form=>{setTestimonials([{...form,rating:Number(form.rating),date:form.status==='Published'?'Jul 14, 2026':'—',time:form.status==='Published'?'Just now':'',tone:'blue'},...testimonials]);setModal(false);flash('Testimonial added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(t=>selected.includes(t.client))?selected.filter(id=>!filtered.some(t=>t.client===id)):[...new Set([...selected,...filtered.map(t=>t.client)])]);
  const exportTestimonials=()=>{const header='Client,Company,Testimonial,Service,Rating,Status,Published On';const rows=filtered.map(t=>[t.client,t.company,t.text,t.service,t.rating,t.status,`${t.date} ${t.time}`].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-testimonials.csv';a.click();URL.revokeObjectURL(url);flash('Testimonial list exported')};
  return <div className="users-page testimonials-page">
    <div className="users-heading"><div><h1>Testimonials</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Testimonials</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Testimonial</button></div>
    <div className="user-stats">{testimonialStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up===false?'down':'up'}>{up===true&&<I.ArrowUp/>}{up===false&&<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
    <div className="card users-table-card"><div className="users-toolbar"><div className="users-search testimonial-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search testimonials..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Published</option><option>Pending</option><option>Hidden</option></select><select value={rating} onChange={e=>setRating(e.target.value)}><option>All Ratings</option><option value="5">5 Stars</option><option value="4.5">4.5 Stars</option></select><select value={service} onChange={e=>setService(e.target.value)}><option>All Services</option>{[...new Set(testimonialSeed.map(t=>t.service))].map(x=><option key={x}>{x}</option>)}</select><select value={client} onChange={e=>setClient(e.target.value)}><option>All Clients</option>{[...new Set(testimonialSeed.map(t=>t.client))].map(x=><option key={x}>{x}</option>)}</select><div className="toolbar-spacer"/><button className="date-button"><I.CalendarDays/> May 15, 2024 - May 21, 2024 <I.ChevronDown/></button><button><I.ListFilter/> Filter</button><button onClick={exportTestimonials}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table testimonials-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(t=>selected.includes(t.client))} onChange={toggleAll}/></th><th>Client</th><th>Testimonial</th><th>Service</th><th>Rating</th><th>Status</th><th>Published On <I.RotateCw/></th><th>Actions</th></tr></thead><tbody>{filtered.map(t=><tr key={t.client}><td><input type="checkbox" checked={selected.includes(t.client)} onChange={()=>toggle(t.client)}/></td><td><div className="testimonial-client"><i className={t.tone}>{t.client.split(' ').map(x=>x[0]).join('')}</i><span><b>{t.client}</b><small>{t.company}</small></span></div></td><td><p className="testimonial-copy">{t.text}</p></td><td><span className={`testimonial-service ${t.service.toLowerCase().replaceAll(/[^a-z]+/g,'-')}`}>{t.service}</span></td><td><span className="testimonial-rating">{Array.from({length:5},(_,i)=>i+.5===t.rating?<I.StarHalf key={i} fill="currentColor"/>:<I.Star key={i} className={i<t.rating?'filled':''} fill={i<t.rating?'currentColor':'none'}/>)}</span></td><td><span className={`testimonial-status ${t.status.toLowerCase()}`}>{t.status}</span></td><td><span className="created-date">{t.date}<small>{t.time}</small></span></td><td><div className="user-actions"><button title="View testimonial" onClick={()=>flash(`Viewing ${t.client}'s testimonial`)}><I.Eye/></button><button title="Edit testimonial" onClick={()=>flash(`Editing ${t.client}'s testimonial`)}><I.Pencil/></button><button className="more"><I.EllipsisVertical/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No testimonials found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer"><span>Showing 1 to {filtered.length} of 86 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>11</button><button aria-label="Next"><I.ChevronRight/></button></div></div>
    </div>{modal&&<TestimonialModal onClose={()=>setModal(false)} onSave={addTestimonial}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}

const messageSeed=[
  {id:1,sender:'John Smith',email:'john.smith@email.com',phone:'+1 (555) 123-4567',location:'New York, USA',subject:'Project Inquiry',preview:'Hello, I am interested in your web development...',status:'New',date:'May 21, 2024',time:'10:30 AM',channel:'Contact Form',ip:'192.168.1.100',tone:'blue',body:['Hello,','I am interested in your web development services for my new project.','Could you please provide more information about your process, timeline and estimated cost?','Looking forward to your response.','Thank you!','John Smith']},
  {id:2,sender:'Sarah Johnson',email:'sarah.johnson@email.com',phone:'+1 (555) 442-9182',location:'Austin, USA',subject:'General Question',preview:'Can you please provide more information about...',status:'New',date:'May 21, 2024',time:'09:15 AM',channel:'Email',ip:'192.168.1.114',tone:'purple',body:['Hello,','Can you please provide more information about your consulting services and availability?','Thank you,','Sarah Johnson']},
  {id:3,sender:'Michael Brown',email:'michael.brown@email.com',phone:'+44 20 7788 1092',location:'London, UK',subject:'Service Support',preview:'I need help with integration of the payment...',status:'Replied',date:'May 20, 2024',time:'04:45 PM',channel:'Contact Form',ip:'172.16.2.41',tone:'orange',body:['Hi Support,','I need help with integration of the payment service in our application.','Please let me know the next steps.','Michael']},
  {id:4,sender:'Emily Davis',email:'emily.davis@email.com',phone:'+1 (416) 555-2210',location:'Toronto, Canada',subject:'Partnership Opportunity',preview:'We are interested in partnership with your company...',status:'Replied',date:'May 20, 2024',time:'11:20 AM',channel:'Email',ip:'10.22.8.90',tone:'green',body:['Hello Mikenium,','We are interested in partnership with your company on an upcoming digital initiative.','I would love to arrange a call.','Emily Davis']},
  {id:5,sender:'David Wilson',email:'david.wilson@email.com',phone:'+61 2 8844 2091',location:'Sydney, Australia',subject:'Custom Development',preview:'Do you develop custom applications? We have...',status:'New',date:'May 19, 2024',time:'03:10 PM',channel:'Live Chat',ip:'192.168.4.20',tone:'red',body:['Hi,','Do you develop custom applications? We have a detailed scope ready for review.','Regards,','David Wilson']},
  {id:6,sender:'Laura Martinez',email:'laura.martinez@email.com',phone:'+49 30 2288 390',location:'Berlin, Germany',subject:'Pricing Information',preview:'Please share the pricing details for your services...',status:'Replied',date:'May 19, 2024',time:'10:05 AM',channel:'Contact Form',ip:'172.18.3.72',tone:'yellow',body:['Hello,','Please share the pricing details for your services and available engagement models.','Laura']},
  {id:7,sender:'James Taylor',email:'james.taylor@email.com',phone:'+1 (415) 555-7731',location:'San Francisco, USA',subject:'Career Inquiry',preview:'I would like to know about job opportunities...',status:'New',date:'May 18, 2024',time:'05:30 PM',channel:'Email',ip:'10.0.1.56',tone:'cyan',body:['Hello,','I would like to know about job opportunities currently available at Mikenium.','Best,','James Taylor']},
  {id:8,sender:'Olivia Anderson',email:'olivia.anderson@email.com',phone:'+81 90 4432 8100',location:'Tokyo, Japan',subject:'Website Feedback',preview:'Your website is amazing! Just wanted to provide...',status:'Replied',date:'May 18, 2024',time:'01:25 PM',channel:'Contact Form',ip:'192.168.8.33',tone:'purple',body:['Hi team,','Your website is amazing! Just wanted to provide some positive feedback on the design and experience.','Olivia Anderson']}
];

const messageStats=[['Total Messages','128','12.5%',I.Mail,'blue',true],['New Messages','18','20.0%',I.MessageSquare,'green',true],['Replied','92','8.3%',I.MailCheck,'orange',true],['Trash','6','14.3%',I.Trash2,'pink',false]];

export function ContactMessagesPage(){
  const [messages,setMessages]=useState(messageSeed),[activeId,setActiveId]=useState(1),[query,setQuery]=useState(''),[status,setStatus]=useState('All Status'),[channel,setChannel]=useState('All Channels'),[selected,setSelected]=useState([]),[reply,setReply]=useState(''),[tab,setTab]=useState('Reply'),[toast,setToast]=useState('');
  const filtered=useMemo(()=>messages.filter(m=>[m.sender,m.email,m.subject,m.preview].join(' ').toLowerCase().includes(query.toLowerCase())&&(status==='All Status'||m.status===status)&&(channel==='All Channels'||m.channel===channel)),[messages,query,status,channel]);
  const active=messages.find(m=>m.id===activeId)||messages[0];
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(m=>selected.includes(m.id))?selected.filter(id=>!filtered.some(m=>m.id===id)):[...new Set([...selected,...filtered.map(m=>m.id)])]);
  const markReplied=()=>{setMessages(messages.map(m=>m.id===active.id?{...m,status:'Replied'}:m));flash('Message marked as replied')};
  const remove=()=>{const remaining=messages.filter(m=>m.id!==active.id);setMessages(remaining);setActiveId(remaining[0]?.id);flash('Message moved to trash')};
  const sendReply=()=>{if(!reply.trim()){flash('Write a reply first');return}setMessages(messages.map(m=>m.id===active.id?{...m,status:'Replied'}:m));setReply('');flash(tab==='Reply'?'Reply sent successfully':'Internal note saved')};
  return <div className="users-page contact-messages-page">
    <div className="users-heading contact-heading"><div><h1>Contact Messages</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Contact Messages</span></div></div></div>
    <div className="contact-layout"><div className="contact-left"><div className="contact-stats">{messageStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up?'up':'down'}>{up?<I.ArrowUp/>:<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
      <div className="card contact-inbox"><div className="contact-toolbar"><div className="users-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search messages..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>New</option><option>Replied</option></select><select value={channel} onChange={e=>setChannel(e.target.value)}><option>All Channels</option><option>Contact Form</option><option>Email</option><option>Live Chat</option></select><div className="toolbar-spacer"/><button className="date-button"><I.CalendarDays/> May 15, 2024 - May 21, 2024 <I.ChevronDown/></button><button><I.ListFilter/> Filter</button></div>
        <div className="contact-table-wrap"><table className="users-table contact-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(m=>selected.includes(m.id))} onChange={toggleAll}/></th><th>Sender</th><th>Subject</th><th>Status</th><th>Received On <I.RotateCw/></th></tr></thead><tbody>{filtered.map(m=><tr key={m.id} className={m.id===activeId?'selected':''} onClick={()=>setActiveId(m.id)}><td><input type="checkbox" checked={selected.includes(m.id)} onClick={e=>e.stopPropagation()} onChange={()=>toggle(m.id)}/></td><td><div className="message-sender"><i className={m.tone}>{m.sender.split(' ').map(x=>x[0]).join('')}</i><span><b>{m.sender}</b><small>{m.email}</small></span></div></td><td><span className="message-subject"><b>{m.subject}</b><small>{m.preview}</small></span></td><td><span className={`message-status ${m.status.toLowerCase()}`}>{m.status}</span></td><td><span className="created-date">{m.date}<small>{m.time}</small></span></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No messages found</b><span>Try changing the search or filters.</span></div>}</div>
        <div className="users-footer"><span>Showing 1 to {filtered.length} of 128 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>16</button><button aria-label="Next"><I.ChevronRight/></button></div></div></div></div>
      {active&&<aside className="card message-detail"><div className="message-detail-head"><h2>{active.subject}</h2><span className={`message-status ${active.status.toLowerCase()}`}>{active.status}</span><div><button title="Mark replied" onClick={markReplied}><I.CircleCheck/></button><button title="Move to trash" onClick={remove}><I.Trash2/></button><button><I.EllipsisVertical/></button></div></div><div className="message-profile"><div className="message-person"><i className={active.tone}>{active.sender.split(' ').map(x=>x[0]).join('')}</i><span><b>{active.sender}</b><small>{active.email}</small><small>{active.phone}</small><small>{active.location}</small></span></div><dl><div><dt>Received On</dt><dd>{active.date} {active.time}</dd></div><div><dt>Channel</dt><dd>{active.channel}</dd></div><div><dt>IP Address</dt><dd>{active.ip}</dd></div></dl></div><div className="message-body">{active.body.map((p,i)=><p key={i}>{p}</p>)}</div><div className="previous-conversation"><h3>Previous Conversations (1) <I.ChevronDown/></h3><div><span className="mini-admin">SA</span><p><b>Super Admin</b><small>May 21, 2024 11:15 AM</small><em>Replied</em><span>Hello {active.sender.split(' ')[0]}, Thank you for reaching out to us. We’d be happy to help...</span></p></div></div><div className="reply-tabs"><button className={tab==='Reply'?'active':''} onClick={()=>setTab('Reply')}>Reply</button><button className={tab==='Internal Note'?'active':''} onClick={()=>setTab('Internal Note')}>Internal Note</button></div><div className="reply-editor"><div><I.Bold/><I.Italic/><I.Underline/><I.List/><I.ListOrdered/><I.Link/><I.Image/><I.SquarePlay/></div><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder={tab==='Reply'?'Type your reply...':'Add an internal note...'}/></div><div className="reply-actions"><button onClick={()=>flash('Attach file selected')}><I.Paperclip/> Attach File</button><button onClick={sendReply}><I.Send/> {tab==='Reply'?'Send Reply':'Save Note'} <I.ChevronDown/></button></div></aside>}
    </div>{toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}

const pageSeed=[
  {name:'Home',description:'Homepage',slug:'/',type:'System',status:'Published',updated:'May 21, 2024 10:30 AM',updater:'Super Admin',tone:'amber'},
  {name:'About Us',description:'About our company',slug:'/about-us',type:'Custom',status:'Published',updated:'May 20, 2024 09:15 AM',updater:'Sarah Johnson',tone:'rose'},
  {name:'Services',description:'Our services',slug:'/services',type:'System',status:'Published',updated:'May 19, 2024 04:45 PM',updater:'Michael Brown',tone:'blue'},
  {name:'Service Details',description:'Single service page',slug:'/services-details',type:'System',status:'Published',updated:'May 18, 2024 11:20 AM',updater:'Super Admin',tone:'amber'},
  {name:'Projects',description:'Our latest projects',slug:'/projects',type:'System',status:'Published',updated:'May 17, 2024 02:30 PM',updater:'Emily Davis',tone:'rose'},
  {name:'Pricing',description:'Pricing plans',slug:'/pricing',type:'Custom',status:'Draft',updated:'May 16, 2024 03:10 PM',updater:'David Wilson',tone:'blue'},
  {name:'Blog',description:'Latest news & insights',slug:'/blog',type:'System',status:'Published',updated:'May 16, 2024 09:00 AM',updater:'Olivia Anderson',tone:'rose'},
  {name:'Contact Us',description:'Get in touch with us',slug:'/contact-us',type:'System',status:'Published',updated:'May 15, 2024 05:20 PM',updater:'James Taylor',tone:'amber'},
  {name:'Careers',description:'Join our team',slug:'/careers',type:'Custom',status:'Hidden',updated:'May 14, 2024 02:15 PM',updater:'Laura Martinez',tone:'rose'},
  {name:'FAQ',description:'Frequently asked questions',slug:'/faq',type:'Custom',status:'Published',updated:'May 14, 2024 10:40 AM',updater:'Super Admin',tone:'amber'}
];

const pageStats=[['Total Pages','24','14.3%',I.Files,'blue',true],['Published','18','12.5%',I.CircleCheckBig,'green',true],['Draft','4','20.0%',I.Clock3,'orange',false],['Hidden','2','0%',I.EyeOff,'purple',null],['Trash','2','33.3%',I.Trash2,'pink',false]];

function PageModal({onClose,onSave}){const [form,setForm]=useState({name:'',description:'',slug:'',type:'Custom',status:'Draft'});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal page-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Page</h2><p>Create a CMS page and configure its visibility.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label className="wide">Page name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. Our Team"/></label><label className="wide">Description<input name="description" required value={form.description} onChange={change} placeholder="Short page description"/></label><label className="wide">Slug<input name="slug" required value={form.slug} onChange={change} placeholder="/our-team"/></label><label>Type<select name="type" value={form.type} onChange={change}><option>Custom</option><option>System</option></select></label><label>Status<select name="status" value={form.status} onChange={change}><option>Draft</option><option>Published</option><option>Hidden</option></select></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Page</button></div></form></div>}

export function PagesAdminPage(){
  const [pages,setPages]=useState(pageSeed),[query,setQuery]=useState(''),[status,setStatus]=useState('All Status'),[type,setType]=useState('All Types'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]),[perPage,setPerPage]=useState('10');
  const filtered=useMemo(()=>pages.filter(p=>[p.name,p.description,p.slug,p.updater].join(' ').toLowerCase().includes(query.toLowerCase())&&(status==='All Status'||p.status===status)&&(type==='All Types'||p.type===type)),[pages,query,status,type]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addPage=form=>{setPages([{...form,updated:'Jul 14, 2026 12:00 PM',updater:'Super Admin',tone:'amber'},...pages]);setModal(false);flash('Page added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(p=>selected.includes(p.slug))?selected.filter(id=>!filtered.some(p=>p.slug===id)):[...new Set([...selected,...filtered.map(p=>p.slug)])]);
  const exportPages=()=>{const header='Page,Description,Slug,Type,Status,Last Updated,Updated By';const rows=filtered.map(p=>[p.name,p.description,p.slug,p.type,p.status,p.updated,p.updater].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-pages.csv';a.click();URL.revokeObjectURL(url);flash('Page list exported')};
  return <div className="users-page pages-admin-page">
    <div className="users-heading"><div><h1>Pages</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Pages</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Page</button></div>
    <div className="user-stats">{pageStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up===false?'down':'up'}>{up===true&&<I.ArrowUp/>}{up===false&&<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
    <div className="card users-table-card"><div className="users-toolbar"><div className="users-search page-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pages..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Published</option><option>Draft</option><option>Hidden</option></select><select value={type} onChange={e=>setType(e.target.value)}><option>All Types</option><option>System</option><option>Custom</option></select><div className="toolbar-spacer"/><button className="date-button"><I.CalendarDays/> May 15, 2024 - May 21, 2024 <I.ChevronDown/></button><button><I.ListFilter/> Filter</button><button onClick={exportPages}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table pages-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(p=>selected.includes(p.slug))} onChange={toggleAll}/></th><th>Page</th><th>Slug</th><th>Type</th><th>Status</th><th>Last Updated <I.RotateCw/></th><th>Updated By <I.RotateCw/></th><th>Actions</th></tr></thead><tbody>{filtered.map(p=><tr key={p.slug}><td><input type="checkbox" checked={selected.includes(p.slug)} onChange={()=>toggle(p.slug)}/></td><td><div className="page-identity"><i><I.FileText/></i><span><b>{p.name}</b><small>{p.description}</small></span></div></td><td className="page-slug">{p.slug}</td><td><span className={`page-type ${p.type.toLowerCase()}`}>{p.type}</span></td><td><span className={`page-status ${p.status.toLowerCase()}`}>{p.status}</span></td><td>{p.updated}</td><td><span className="page-updater"><i className={p.tone}>{p.updater.split(' ').map(x=>x[0]).join('')}</i>{p.updater}</span></td><td><div className="user-actions"><button title="Edit page" onClick={()=>flash(`Editing ${p.name}`)}><I.Pencil/></button><button title="Preview page" onClick={()=>flash(`Previewing ${p.name}`)}><I.Eye/></button><button className="more"><I.EllipsisVertical/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No pages found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer pages-footer"><span>Showing 1 to {Math.min(Number(perPage),filtered.length)} of 24 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button aria-label="Next"><I.ChevronRight/></button><select value={perPage} onChange={e=>setPerPage(e.target.value)}><option value="10">10 / page</option><option value="20">20 / page</option><option value="50">50 / page</option></select></div></div>
    </div>{modal&&<PageModal onClose={()=>setModal(false)} onSave={addPage}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}

function PageHeading({name,description,icon:Icon}){return <div className="page-heading"><div><span><Icon/></span><div><h1>{name}</h1><p>{description}</p></div></div><div className="breadcrumbs">Dashboard <I.ChevronRight/> {name}</div></div>}

export function SettingsPage(){const [saved,setSaved]=useState(false);const [tab,setTab]=useState('General');return <div className="admin-page"><PageHeading name="Settings" description="Configure company, email, security, and platform preferences." icon={I.Settings}/><div className="settings-layout"><div className="card settings-tabs">{['General','Branding','Email','Notifications','Security'].map(x=><button className={tab===x?'selected':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><form className="card settings-form" onSubmit={e=>{e.preventDefault();setSaved(true);setTimeout(()=>setSaved(false),2500)}}><h2>{tab} Settings</h2><p>Update the platform's {tab.toLowerCase()} configuration.</p><div className="form-grid"><label>Company name<input defaultValue="Mikenium"/></label><label>Contact email<input type="email" defaultValue="hello@mikenium.com"/></label><label>Phone number<input defaultValue="+94 11 234 5678"/></label><label>Timezone<select defaultValue="Asia/Colombo"><option>Asia/Colombo</option><option>UTC</option></select></label><label className="wide">Company address<textarea defaultValue="Colombo, Sri Lanka"/></label><label className="switch-row wide"><span><b>Maintenance mode</b><small>Temporarily hide the public website.</small></span><input type="checkbox"/></label></div><div className="form-actions"><button className="primary"><I.Save/> Save Changes</button></div></form></div>{saved&&<div className="toast"><I.CircleCheck/>Settings saved successfully</div>}</div>}

export function BackupPage(){const [running,setRunning]=useState(false);const [backups,setBackups]=useState([['backup_2024_05_21.sql','May 21, 2024 02:30 AM','256.8 MB','Completed'],['backup_2024_05_20.sql','May 20, 2024 02:30 AM','252.1 MB','Completed'],['backup_2024_05_19.sql','May 19, 2024 02:30 AM','249.4 MB','Completed']]);const create=()=>{setRunning(true);setTimeout(()=>{setBackups([['backup_just_now.sql','Just now','257.1 MB','Completed'],...backups]);setRunning(false)},1200)};return <div className="admin-page"><PageHeading name="System Backup" description="Create, download, and monitor database backups." icon={I.DatabaseBackup}/><div className="backup-stats"><div className="card"><I.Database/><span><small>Database size</small><b>256.8 MB</b></span></div><div className="card"><I.Clock3/><span><small>Next automatic backup</small><b>Tomorrow, 02:30 AM</b></span></div><div className="card"><I.ShieldCheck/><span><small>Backup health</small><b className="success">Healthy</b></span></div></div><div className="card data-card backup-card"><div className="section-head"><div><h2>Backup History</h2><p>Automatic backups are retained for 30 days.</p></div><button className="primary" disabled={running} onClick={create}>{running?<I.LoaderCircle className="spin"/>:<I.DatabaseBackup/>}{running?'Creating backup...':'Create Backup Now'}</button></div><table><thead><tr><th>File</th><th>Created</th><th>Size</th><th>Status</th><th>Actions</th></tr></thead><tbody>{backups.map(b=><tr key={b[0]}>{b.map((x,i)=><td key={x}>{i===3?<span className="status-pill active">{x}</span>:x}</td>)}<td><button className="row-action"><I.Download/></button></td></tr>)}</tbody></table></div></div>}

export function ViewSite(){return <div className="admin-page preview-page"><PageHeading name="Website Preview" description="Preview the public Mikenium website." icon={I.Globe2}/><div className="card preview"><div className="browser"><i/><i/><i/><span>https://mikenium.com</span><I.RotateCw/></div><div className="preview-hero"><div className="preview-logo">MIKENIUM</div><h1>Building Smarter Software</h1><p>We create powerful digital experiences that help modern businesses grow.</p><button>Explore Our Services <I.ArrowRight/></button></div></div></div>}

export const listingNames=Object.keys(configs);
