import React, { useEffect, useState } from 'react';
import * as I from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import { ListingPage, UsersPage, ClientsPage, ProjectsPage, ServicesPage as AdminServicesPage, ProductsAdminPage, PricingAdminPage, BlogsAdminPage, TestimonialsPage, PartnersPage, ContactMessagesPage, PagesAdminPage, SettingsPage, BackupPage, ViewSite, listingNames } from './pages/admin/AdminPages';
import { MenusPage, MediaLibraryPage, SlidersPage } from './pages/admin/CmsPages';
import { RolesPermissionsPage, SettingsAdminPage, ActivityLogsPage, SystemBackupAdminPage } from './pages/admin/SystemAdminPages';
import PublicHome from './pages/website/PublicHome';
import AboutPage from './pages/website/AboutPage';
import ServicesPage from './pages/website/ServicesPage';
import PortfolioPage from './pages/website/PortfolioPage';
import ProductsPage from './pages/website/ProductsPage';
import PricingPage from './pages/website/PricingPage';
import BlogPage from './pages/website/BlogPage';
import SingleBlogPage from './pages/website/SingleBlogPage';
import ContactPage from './pages/website/ContactPage';
import AdminLogin from './pages/admin/AdminLogin';
import { getAdminSession, getDashboard, logoutAdmin } from './services/admin/admin-api';

const navGroups = [
  { label: '', items: [['Dashboard', I.LayoutDashboard]] },
  { label: 'MANAGEMENT', items: [['Users', I.Users], ['Clients', I.Contact], ['Projects', I.BriefcaseBusiness], ['Services', I.BadgeCheck], ['Products', I.Gift], ['Pricing', I.BadgeDollarSign], ['Blogs', I.NotebookTabs], ['Testimonials', I.MessageSquare], ['Partners', I.Handshake], ['Contact Messages', I.Mail]] },
  { label: 'CMS', items: [['Pages', I.File], ['Menus', I.List], ['Media Library', I.Images], ['Sliders', I.GalleryHorizontal]] },
  { label: 'SYSTEM', items: [['Roles & Permissions', I.ShieldCheck], ['Settings', I.Settings], ['Activity Logs', I.History], ['System Backup', I.DatabaseBackup]] }
];

const statConfig=[
  ['users','Total Users',I.Users,'blue'],['clients','Total Clients',I.Building2,'green'],
  ['projects','Total Projects',I.Folder,'purple'],['products','Total Products',I.ShoppingBag,'orange'],
  ['blogs','Total Blogs',I.NotebookText,'pink']
];
const relativeTime=value=>{const seconds=Math.max(1,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return `${seconds}s ago`;if(seconds<3600)return `${Math.floor(seconds/60)} mins ago`;if(seconds<86400)return `${Math.floor(seconds/3600)} hours ago`;return `${Math.floor(seconds/86400)} days ago`};
const formatRange=range=>range?`${new Date(range.from).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})} - ${new Date(range.to).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}`:'Last 7 days';

function Logo(){return <div className="logo"><div className="mark"><i/><b/></div><div><strong>MIKENIUM</strong><small>Building Smarter Software</small></div></div>}
function Sidebar({open,setOpen,active,onSelect}) { const go=n=>{onSelect(n);setOpen(false)};return <aside className={open?'sidebar open':'sidebar'}>
  <Logo/><nav>{navGroups.map((g,gi)=><section key={gi}>{g.label&&<label>{g.label}</label>}{g.items.map(([n,Icon])=><button onClick={()=>go(n)} className={n===active?'active':''} key={n}><Icon size={18}/><span>{n}</span></button>)}</section>)}</nav>
  <button className="visit" onClick={()=>{window.location.href='/'}}><I.Globe2 size={18}/> View Site <I.ExternalLink size={16}/></button><footer>© 2024 Mikenium<br/><span>All Rights Reserved.</span></footer>
  <button className="mobile-close" onClick={()=>setOpen(false)}><I.X/></button>
  </aside> }
function Header({toggle,title,user,onLogout,dark,onThemeChange}) { return <header><button className="icon-button" onClick={toggle}><I.Menu/></button><b>{title}</b><div className="header-actions"><button className="header-icon" onClick={onThemeChange} title={dark?'Use light theme':'Use dark theme'} aria-label={dark?'Use light theme':'Use dark theme'} aria-pressed={dark}>{dark?<I.Sun/>:<I.Moon/>}</button><span className="bell"><I.Bell/><i>5</i></span><div className="avatar">SA</div><div className="admin"><b>{user?.name||'Super Admin'}</b><small>{user?.email}</small></div><button className="header-icon" onClick={onLogout} title="Sign out" aria-label="Sign out"><I.LogOut/></button></div></header> }
function StatCard({s}) { const [title,num,up,Icon,color]=s;const positive=up>=0;return <div className="stat card"><div className={'stat-icon '+color}><Icon/></div><div><small>{title}</small><strong>{Number(num).toLocaleString()}</strong><p className={positive?'':'down'}>{positive?'↑':'↓'} {Math.abs(up)}% <span>vs previous 7 days</span></p></div></div> }
function PlatformChart({data}){ return <div className="card overview"><div className="card-title"><b>Platform Overview</b><div className="legend"><i className="dot blue-bg"/>Users <i className="dot green-bg"/>Projects <i className="dot purple-bg"/>Clients</div><button>Last 7 Days <I.ChevronDown size={14}/></button></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:15,right:12,left:-22,bottom:0}}><defs>{[['u','#0874e8'],['p','#36b76d'],['c','#8c5ce5']].map(x=><linearGradient key={x[0]} id={x[0]} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={x[1]} stopOpacity=".12"/><stop offset="1" stopColor={x[1]} stopOpacity="0"/></linearGradient>)}</defs><CartesianGrid stroke="#42516a" strokeOpacity=".25" vertical/><XAxis dataKey="label" tick={{fontSize:10,fill:'#8290a5'}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fontSize:10,fill:'#8290a5'}} axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="users" name="Users" stroke="#0874e8" fill="url(#u)" strokeWidth={2}/><Area type="monotone" dataKey="projects" name="Projects" stroke="#36b76d" fill="url(#p)" strokeWidth={2}/><Area type="monotone" dataKey="clients" name="Clients" stroke="#8c5ce5" fill="url(#c)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div>}
function Summary({system}){const rows=[[I.UserRound,'Active Users',system.activeUsers,'green'],[I.Building2,'Active Clients',system.activeClients,'blue'],[I.Folder,'Running Projects',system.runningProjects,'purple'],[I.BadgeHelp,'Support Tickets',system.supportTickets,'orange'],[I.Mail,'Contact Messages',system.messages,'blue']];return <div className="card summary"><h3>System Summary</h3>{rows.map(([Icon,n,v,c])=><div className="summary-row" key={n}><span className={'mini '+c}><Icon/></span><span>{n}</span><b>{Number(v).toLocaleString()}</b>{n==='Support Tickets'&&v>0&&<em>Open</em>}</div>)}</div>}
function Activities({items}){return <div className="card panel"><h3>Recent Activities</h3><div className="rows">{items.length?items.map((item,index)=><div className="activity" key={item.id}><span className={'round '+['blue','green','purple','orange'][index%4]}><I.History/></span><div><b>{item.title}</b><small>{item.description}</small></div><time>{relativeTime(item.createdAt)}</time></div>):<div className="dashboard-empty">No activity recorded yet.</div>}</div><a>Database activity <I.Database/></a></div>}
function Services({items}){const total=items.reduce((sum,item)=>sum+item.value,0);return <div className="card panel services"><h3>Top Services</h3>{items.length?<div className="service-body"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={items} dataKey="value" innerRadius={48} outerRadius={73} paddingAngle={2}>{items.map(s=><Cell key={s.name} fill={s.color}/>)}</Pie></PieChart></ResponsiveContainer><div><small>Total</small><b>{total}</b></div></div><div className="service-list">{items.map(s=><p key={s.name}><i style={{background:s.color}}/>{s.name}<b>{s.value}</b><small>({total?((s.value/total)*100).toFixed(1):0}%)</small></p>)}</div></div>:<div className="dashboard-empty">No services found in the database.</div>}<a>Database services <I.Database/></a></div>}
function Users({items}){return <div className="card panel"><h3>Recent Users</h3><div className="rows">{items.length?items.map((person,idx)=><div className="person" key={person.id}><span className={'photo p'+idx}>{person.name.split(' ').map(part=>part[0]).slice(0,2).join('')}</span><div><b>{person.name}</b><small>{person.email}</small></div><em className={person.role.toLowerCase()}>{person.role}</em><time>{relativeTime(person.createdAt)}</time></div>):<div className="dashboard-empty">No users found.</div>}</div><a>Database users <I.Database/></a></div>}
function Status({generatedAt}){return <div className="card status"><div><span className="status-icon"><I.ShieldCheck/></span><p><small>Admin API</small><b className="ok">Operational</b></p></div><div><span className="status-icon"><I.Database/></span><p><small>PostgreSQL</small><b className="ok">Connected</b></p></div><div><span className="status-icon"><I.LockKeyhole/></span><p><small>Dashboard Access</small><b>Protected session</b></p></div><div><span className="status-icon green"><I.RefreshCw/></span><p><small>Data refreshed</small><b>{new Date(generatedAt).toLocaleString()}</b></p></div></div>}
function Dashboard(){const [state,setState]=useState({loading:true,data:null,error:''});const load=()=>{setState(current=>({...current,loading:true,error:''}));getDashboard().then(data=>setState({loading:false,data,error:''})).catch(error=>setState({loading:false,data:null,error:error.message}))};useEffect(load,[]);if(state.loading&&!state.data)return <div className="content dashboard-state"><I.LoaderCircle className="spin"/>Loading dashboard data...</div>;if(state.error)return <div className="content dashboard-state error"><I.CircleAlert/><b>Dashboard data could not be loaded</b><span>{state.error}</span><button onClick={load}>Try again</button></div>;const data=state.data;const stats=statConfig.map(([key,title,Icon,color])=>[title,data.totals[key].value,data.totals[key].change,Icon,color]);return <div className="content"><div className="welcome"><div><h1>Welcome back, Super Admin! 👋</h1><p>Live data from the Mikenium database.</p></div><button onClick={load} disabled={state.loading}><I.CalendarDays/> {formatRange(data.range)} {state.loading?<I.LoaderCircle className="spin"/>:<I.RefreshCw/>}</button></div><div className="stats">{stats.map(s=><StatCard key={s[0]} s={s}/>)}</div><div className="middle"><PlatformChart data={data.chart}/><Summary system={data.system}/></div><div className="bottom"><Activities items={data.recentActivities}/><Services items={data.topServices}/><Users items={data.recentUsers}/></div><Status generatedAt={data.generatedAt}/></div>}
function CurrentPage({active}){if(active==='Dashboard')return <Dashboard/>;if(active==='Users')return <UsersPage/>;if(active==='Clients')return <ClientsPage/>;if(active==='Projects')return <ProjectsPage/>;if(active==='Services')return <AdminServicesPage/>;if(active==='Products')return <ProductsAdminPage/>;if(active==='Pricing')return <PricingAdminPage/>;if(active==='Blogs')return <BlogsAdminPage/>;if(active==='Testimonials')return <TestimonialsPage/>;if(active==='Partners')return <PartnersPage/>;if(active==='Contact Messages')return <ContactMessagesPage/>;if(active==='Pages')return <PagesAdminPage/>;if(active==='Menus')return <MenusPage/>;if(active==='Media Library')return <MediaLibraryPage/>;if(active==='Sliders')return <SlidersPage/>;if(active==='Roles & Permissions')return <RolesPermissionsPage/>;if(active==='Settings')return <SettingsAdminPage/>;if(active==='Activity Logs')return <ActivityLogsPage/>;if(active==='System Backup')return <SystemBackupAdminPage/>;if(active==='View Site')return <ViewSite/>;if(listingNames.includes(active))return <ListingPage name={active}/>;return <Dashboard/>}
function AdminApp({user,onLogout}){
  const [open,setOpen]=useState(false);
  const [active,setActive]=useState('Dashboard');
  const [dark,setDark]=useState(()=>localStorage.getItem('mikenium-admin-theme')==='dark');
  function changeTheme(){setDark(current=>{const next=!current;localStorage.setItem('mikenium-admin-theme',next?'dark':'light');return next;});}
  return <div className={dark?'app dark-theme':'app'}><Sidebar open={open} setOpen={setOpen} active={active} onSelect={setActive}/>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}<main><Header title={active} toggle={()=>setOpen(!open)} user={user} onLogout={onLogout} dark={dark} onThemeChange={changeTheme}/><CurrentPage active={active}/></main></div>
}
function AdminGate(){
  const [state,setState]=useState({loading:true,user:null});
  useEffect(()=>{let mounted=true;getAdminSession().then(({user})=>mounted&&setState({loading:false,user})).catch(()=>mounted&&setState({loading:false,user:null}));return()=>{mounted=false}},[]);
  async function signOut(){try{await logoutAdmin();}finally{setState({loading:false,user:null});}}
  if(state.loading)return <div className="admin-auth-loading"><I.LoaderCircle className="spin"/><span>Checking secure session...</span></div>;
  if(!state.user)return <AdminLogin onLogin={user=>setState({loading:false,user})}/>;
  return <AdminApp user={state.user} onLogout={signOut}/>;
}
export default function App(){const path=window.location.pathname;return path.startsWith('/admin')?<AdminGate/>:path.startsWith('/blog/')?<SingleBlogPage/>:path==='/about'||path==='/about/'?<AboutPage/>:path==='/services'||path==='/services/'?<ServicesPage/>:path==='/portfolio'||path==='/portfolio/'?<PortfolioPage/>:path==='/products'||path==='/products/'?<ProductsPage/>:path==='/pricing'||path==='/pricing/'?<PricingPage/>:path==='/blog'||path==='/blog/'?<BlogPage/>:path==='/contact'||path==='/contact/'?<ContactPage/>:<PublicHome/>}
