import React, { useEffect, useMemo, useState } from 'react';
import * as I from 'lucide-react';
import './blog-page.css';

const categories=['All','Engineering','AI & Data','Design','Cloud','Business'];
const posts=[
  {category:'Engineering',title:'The Future of Web Development: What High-Performing Teams Do Differently',excerpt:'The architecture, tooling, and product habits shaping faster, more resilient web experiences.',date:'May 20, 2026',read:'7 min read',image:'code',featured:true},
  {category:'Cloud',title:'Cloud-Native Without the Complexity',excerpt:'A practical roadmap for moving to scalable infrastructure while keeping risk and cost under control.',date:'May 15, 2026',read:'6 min read',image:'cloud'},
  {category:'Design',title:'Designing Interfaces People Trust Instantly',excerpt:'Small interaction choices that make complex software feel clear, capable, and reassuring.',date:'May 10, 2026',read:'5 min read',image:'design'},
  {category:'Engineering',title:'Clean Code Is a Business Advantage',excerpt:'Why maintainable software improves delivery speed, reliability, and your ability to respond to change.',date:'May 06, 2026',read:'6 min read',image:'code'},
  {category:'AI & Data',title:'From AI Experiment to Everyday Workflow',excerpt:'How to turn promising prototypes into useful, responsible AI features teams actually adopt.',date:'Apr 29, 2026',read:'8 min read',image:'cloud'},
  {category:'Business',title:'The Real ROI of Custom Software',excerpt:'A straightforward framework for deciding when purpose-built software is worth the investment.',date:'Apr 22, 2026',read:'5 min read',image:'design'}
];

function Logo(){return <a className="public-logo" href="/" aria-label="Mikenium home"><img src="/assets/mikenium-logo-transparent.png" alt="Mikenium — Building Smarter Software"/></a>}
function SiteButton({children,href='/#contact'}){return <a className="site-button" href={href}>{children}<I.ArrowRight/></a>}

function Header({menu,setMenu,scrolled}){return <header className={'public-header '+(scrolled?'scrolled ':'')+(menu?'menu-open':'')}><Logo/><div className="nav-center"><nav className={menu?'open':''}>{[['Home','/'],['Services','/services'],['Portfolio','/portfolio'],['Products','/products'],['Pricing','/pricing'],['Blog','/blog'],['About','/about']].map(([label,href],index)=><a className={label==='Blog'?'active':''} onClick={()=>setMenu(false)} href={href} key={label}><span>0{index+1}</span>{label}</a>)}</nav></div><div className="nav-actions"><a className="nav-contact" href="/contact"><span>Start a Project</span><I.ArrowUpRight/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu?<I.X/>:<I.Menu/>}</button></div></header>}

function ArticleCard({post,index}){const href=index===0?'/blog/future-web-development':'#featured-story';return <article className="journal-card reveal">
  <a href={href} className={'journal-image '+post.image} aria-label={`Read ${post.title}`}><span className="card-index">0{index+1}</span><span className="image-action"><I.ArrowUpRight/></span></a>
  <div className="journal-copy"><span className="post-category">{post.category}</span><h3><a href={href}>{post.title}</a></h3><p>{post.excerpt}</p><div className="post-meta"><span><I.CalendarDays/>{post.date}</span><span><I.Clock3/>{post.read}</span></div><a className="read-link" href={href}>Read insight <I.ArrowRight/></a></div>
  </article>}

function Footer(){return <footer id="contact"><div className="footer-glow"/><div className="cta"><div><span className="cta-label"><i/> LET’S CREATE TOGETHER</span><h2>Ready to build software<br/>that moves your business?</h2><p>Bring us the challenge. We’ll bring the strategy, design, and engineering to turn it into a product people value.</p></div><div className="cta-actions"><SiteButton>Start a Conversation</SiteButton><a href="mailto:hello@mikenium.com">hello@mikenium.com <I.ArrowUpRight/></a></div></div><div className="footer-main"><div className="footer-about"><img src="/assets/mikenium-logo-transparent.png" alt="Mikenium — Building Smarter Software"/><p>We design and engineer secure digital products that help ambitious businesses grow with confidence.</p><span className="footer-socials">{[I.Facebook,I.Linkedin,I.Twitter,I.Github,I.Instagram].map((Icon,i)=><a href="/" aria-label="Social link" key={i}><Icon/></a>)}</span></div><div className="footer-links"><div><h4>Company</h4>{[['About Us','/about'],['Our Work','/portfolio'],['Careers','/#contact'],['Contact','/#contact']].map(([label,href])=><a href={href} key={label}>{label}</a>)}</div><div><h4>Expertise</h4>{['Web Development','Mobile Apps','Cloud Solutions','UI/UX Design'].map(x=><a href="/services#capabilities" key={x}>{x}</a>)}</div><div><h4>Resources</h4>{[['Insights','/blog'],['Products','/products'],['Pricing','/pricing'],['Client Stories','/portfolio']].map(([label,href])=><a href={href} key={label}>{label}</a>)}</div></div><div className="footer-contact"><span><I.MapPin/></span><div><h4>Let’s talk about your next idea.</h4><a href="mailto:hello@mikenium.com">hello@mikenium.com</a><a href="tel:+94112345678">+94 11 234 5678</a><small>Colombo, Sri Lanka</small></div></div></div><div className="footer-bottom"><p>© 2026 Mikenium. All rights reserved.</p><nav><a href="/">Privacy Policy</a><a href="/">Terms of Service</a><a href="/">Cookie Policy</a></nav><span><i/> All systems operational</span></div></footer>}

export default function BlogPage(){
  const [menu,setMenu]=useState(false),[scrolled,setScrolled]=useState(false),[category,setCategory]=useState('All'),[query,setQuery]=useState('');
  const visible=useMemo(()=>posts.filter(post=>(category==='All'||post.category===category)&&(`${post.title} ${post.excerpt} ${post.category}`.toLowerCase().includes(query.toLowerCase()))),[category,query]);
  useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>20);onScroll();window.addEventListener('scroll',onScroll,{passive:true});const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('is-visible')),{threshold:.1});document.querySelectorAll('.blog-page .reveal').forEach(el=>observer.observe(el));return()=>{window.removeEventListener('scroll',onScroll);observer.disconnect()}},[visible]);
  return <div className="public-site blog-page">
    <Header menu={menu} setMenu={setMenu} scrolled={scrolled}/>
    <main>
      <section className="blog-hero"><div className="blog-grid-lines"/><div className="hero-orb orb-a"/><div className="hero-orb orb-b"/><div className="blog-hero-copy"><span className="blog-kicker"><i/> IDEAS FOR BUILDERS</span><h1>Thinking at the edge<br/>of <span>what’s next.</span></h1><p>Clear thinking on software, design, AI, and the decisions that turn ambitious ideas into valuable digital products.</p><div className="hero-reading"><span><I.BookOpen/> Fresh perspectives, twice a month</span><a href="#journal">Explore the journal <I.ArrowDown/></a></div></div><div className="blog-hero-art" aria-hidden="true"><div className="art-frame"><div className="art-image"/><span className="art-label">MIKENIUM / JOURNAL — 026</span><div className="art-code"><i/><i/><i/><i/></div></div><div className="floating-note note-one"><I.Sparkles/><span><b>Human insight</b><small>Behind every build</small></span></div><div className="floating-note note-two"><I.TrendingUp/><span><b>Practical ideas</b><small>Made to create momentum</small></span></div></div></section>

      <section className="featured-story reveal" id="featured-story"><div className="featured-visual code"><span>FEATURED / 8 MIN READ</span><div className="featured-signal"><i/> NEW PERSPECTIVE</div></div><div className="featured-copy"><span className="section-label">EDITOR’S PICK · ENGINEERING</span><h2>Software that scales starts with decisions that do.</h2><p>The most resilient products aren’t built by chasing every new tool. They emerge from clear priorities, thoughtful architecture, and teams that know what not to build.</p><div className="featured-author"><span>MK</span><div><b>Mikenium Engineering</b><small>May 24, 2026</small></div><a href="#journal" aria-label="Read featured article"><I.ArrowUpRight/></a></div></div></section>

      <section className="journal" id="journal"><div className="journal-head reveal"><div><span className="section-label">THE LATEST FROM OUR TEAM</span><h2>Ideas worth building on.</h2></div><p>Field notes from the people designing, shipping, and evolving modern software.</p></div><div className="journal-tools reveal"><div className="category-tabs" role="group" aria-label="Filter articles by category">{categories.map(item=><button className={category===item?'active':''} onClick={()=>setCategory(item)} key={item}>{item}</button>)}</div><label className="journal-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search insights..." aria-label="Search insights"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><I.X/></button>}</label></div>
        {visible.length?<div className="journal-layout"><div className="journal-grid">{visible.map((post,index)=><ArticleCard post={post} index={index} key={post.title}/>)}</div><aside className="journal-aside reveal"><span className="aside-label">MOST READ</span><h3>Popular with product teams</h3>{posts.slice(0,4).map((post,i)=><a href="#featured-story" key={post.title}><strong>0{i+1}</strong><span><b>{post.title}</b><small>{post.read} · {post.category}</small></span><I.ArrowUpRight/></a>)}<div className="editor-note"><I.Quote/><p>“The best technology decisions begin with a better question.”</p><span>Mikenium product principle</span></div></aside></div>:<div className="empty-state"><I.SearchX/><h3>No insights found</h3><p>Try another category or a broader search.</p><button onClick={()=>{setCategory('All');setQuery('')}}>Reset filters</button></div>}
      </section>

      <section className="blog-newsletter reveal"><div className="newsletter-icon"><I.Send/></div><div><span className="section-label">THE USEFUL UPDATE</span><h2>One sharp idea.<br/>Zero inbox noise.</h2><p>Join product leaders and builders getting our best thinking twice a month.</p></div><form onSubmit={e=>e.preventDefault()}><label><I.Mail/><input type="email" placeholder="Work email address" required/></label><button>Join the journal <I.ArrowRight/></button><small><I.ShieldCheck/> No spam. Unsubscribe whenever you like.</small></form></section>
    </main>
    <Footer/>
  </div>
}
