import React, { useEffect, useState } from 'react';
import * as I from 'lucide-react';
import './public-home.css';
import './portfolio-page.css';

const navItems=[['Home','/'],['Services','/services'],['Portfolio','/portfolio'],['Products','/products'],['Pricing','/pricing'],['Blog','/blog'],['About','/about']];
const filters=[
  ['All work',I.LayoutGrid,'all'],['Web platforms',I.Monitor,'web'],['Mobile apps',I.Smartphone,'mobile'],
  ['Product design',I.PenTool,'design'],['Cloud systems',I.Cloud,'cloud'],['Commerce',I.ShoppingBag,'commerce']
];
const projects=[
  {title:'Pulse Analytics',type:'Fintech intelligence',category:'web',result:'+42% faster decisions',copy:'A live financial command center that turns complex signals into confident actions.',tone:'analytics',tags:['React','Data viz','Fintech'],icon:I.ChartNoAxesCombined},
  {title:'Orbit Workspace',type:'Project management SaaS',category:'cloud',result:'2.4× faster delivery',copy:'One calm workspace for planning, collaboration, and high-velocity product teams.',tone:'workspace',tags:['SaaS','Cloud','Automation'],icon:I.Orbit},
  {title:'Maison',type:'E-commerce experience',category:'commerce',result:'+31% conversion',copy:'A premium storefront that makes product discovery feel effortless and personal.',tone:'commerce',tags:['Commerce','UX','Payments'],icon:I.ShoppingBag},
  {title:'NovaPay',type:'Mobile fintech',category:'mobile',result:'120K+ active users',copy:'Secure everyday banking with instant transfers and a radically clear mobile experience.',tone:'mobile',tags:['iOS','Android','Security'],icon:I.WalletCards},
  {title:'Atlas Cloud',type:'Cloud infrastructure',category:'cloud',result:'99.99% availability',copy:'Resilient infrastructure designed for scale, observability, and dependable delivery.',tone:'cloud',tags:['AWS','DevOps','Platform'],icon:I.CloudCog},
  {title:'CareLink',type:'Healthcare operations',category:'design',result:'-38% admin time',copy:'A human-centered clinical dashboard that brings teams, patients, and data together.',tone:'health',tags:['Healthtech','UI/UX','Web'],icon:I.HeartPulse},
  {title:'Elevate',type:'Learning platform',category:'web',result:'4.8/5 learner rating',copy:'A focused learning journey with adaptive content, progress insight, and community.',tone:'learning',tags:['Edtech','Video','SaaS'],icon:I.GraduationCap},
  {title:'Roam',type:'Travel booking platform',category:'commerce',result:'+27% bookings',copy:'Inspiring discovery and frictionless booking for unforgettable places and stays.',tone:'travel',tags:['Travel','Search','Booking'],icon:I.Map},
  {title:'Savor',type:'Food delivery app',category:'mobile',result:'18 min avg. delivery',copy:'A fast, friendly ordering experience connecting local kitchens with hungry customers.',tone:'food',tags:['Mobile','Logistics','Maps'],icon:I.Utensils}
];

function Logo(){return <a className="public-logo" href="/" aria-label="Mikenium home"><img src="/assets/mikenium-logo-transparent.png" alt="Mikenium — Building Smarter Software"/></a>}
function SiteButton({children,href='/#contact'}){return <a className="site-button" href={href}>{children}<I.ArrowRight/></a>}
function Header(){const [menu,setMenu]=useState(false);const [scrolled,setScrolled]=useState(false);useEffect(()=>{const fn=()=>setScrolled(window.scrollY>20);fn();window.addEventListener('scroll',fn,{passive:true});return()=>window.removeEventListener('scroll',fn)},[]);return <header className={'public-header '+(scrolled?'scrolled ':'')+(menu?'menu-open':'')}><Logo/><div className="nav-center"><nav className={menu?'open':''}>{navItems.map(([label,href],index)=><a className={label==='Portfolio'?'active':''} onClick={()=>setMenu(false)} href={href} key={label}><span>0{index+1}</span>{label}</a>)}</nav></div><div className="nav-actions"><a className="nav-contact" href="/contact"><span>Start a Project</span><I.ArrowUpRight/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu?<I.X/>:<I.Menu/>}</button></div></header>}
function ProjectVisual({project}){const Icon=project.icon;return <div className={'portfolio-visual '+project.tone}><div className="visual-noise"/><div className="mini-browser"><div className="mini-bar"><i/><i/><i/><span>mikenium / {project.title.toLowerCase()}</span></div><div className="mini-nav"><Icon/><i/><i/><i/></div><div className="mini-content"><span className="mini-label">{project.type}</span><strong>{project.title}</strong><div className="mini-widgets"><i/><i/><i/></div><div className="mini-chart"><b/><b/><b/><b/><b/><b/></div></div></div><span className="project-float"><Icon/><b>{project.result}</b></span></div>}
function ProjectCard({project,index}){return <article className={'portfolio-card reveal '+(index===0?'portfolio-featured':'')}><ProjectVisual project={project}/><div className="portfolio-card-copy"><div className="card-meta"><span>0{index+1} / {project.type}</span><b>{project.result}</b></div><h3>{project.title}<a href="/#contact" aria-label={`Discuss a project like ${project.title}`}><I.ArrowUpRight/></a></h3><p>{project.copy}</p><div className="project-tags">{project.tags.map(tag=><span key={tag}>{tag}</span>)}<a href="/#contact">View project <I.ArrowRight/></a></div></div></article>}
function Footer(){return <footer id="contact"><div className="footer-glow"/><div className="cta"><div><span className="cta-label"><i/> LET’S CREATE TOGETHER</span><h2>Ready to build software<br/>that moves your business?</h2><p>Bring us the challenge. We’ll bring the strategy, design, and engineering to turn it into a product people value.</p></div><div className="cta-actions"><SiteButton>Start a Conversation</SiteButton><a href="mailto:hello@mikenium.com">hello@mikenium.com <I.ArrowUpRight/></a></div></div><div className="footer-main"><div className="footer-about"><img src="/assets/mikenium-logo-transparent.png" alt="Mikenium — Building Smarter Software"/><p>We design and engineer secure digital products that help ambitious businesses grow with confidence.</p><span className="footer-socials">{[I.Facebook,I.Linkedin,I.Twitter,I.Github,I.Instagram].map((Icon,i)=><a href="/" aria-label="Social link" key={i}><Icon/></a>)}</span></div><div className="footer-links"><div><h4>Company</h4>{[['About Us','/about'],['Our Work','/portfolio'],['Careers','/#contact'],['Contact','/#contact']].map(([label,href])=><a href={href} key={label}>{label}</a>)}</div><div><h4>Expertise</h4>{['Web Development','Mobile Apps','Cloud Solutions','UI/UX Design'].map(x=><a href="/services#capabilities" key={x}>{x}</a>)}</div><div><h4>Resources</h4>{['Insights','Products','Pricing','Client Stories'].map(x=><a href="/#blog" key={x}>{x}</a>)}</div></div><div className="footer-contact"><span><I.MapPin/></span><div><h4>Let’s talk about your next idea.</h4><a href="mailto:hello@mikenium.com">hello@mikenium.com</a><a href="tel:+94112345678">+94 11 234 5678</a><small>Colombo, Sri Lanka</small></div></div></div><div className="footer-bottom"><p>© 2026 Mikenium. All rights reserved.</p><nav><a href="/">Privacy Policy</a><a href="/">Terms of Service</a><a href="/">Cookie Policy</a></nav><span><i/> All systems operational</span></div></footer>}

export default function PortfolioPage(){
  const [active,setActive]=useState('all');
  useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add('is-visible')),{threshold:.1});document.querySelectorAll('.portfolio-page .reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[active]);
  const visible=active==='all'?projects:projects.filter(project=>project.category===active);
  return <div className="public-site portfolio-page"><Header/><main>
    <section className="portfolio-hero"><div className="portfolio-grid-bg"/><div className="portfolio-glow glow-one"/><div className="portfolio-glow glow-two"/><div className="portfolio-hero-copy"><span className="portfolio-kicker"><i/> SELECTED WORK <b>2021 — 2026</b></span><h1>Digital products<br/>with <em>measurable</em><br/><span>momentum.</span></h1><p>We pair sharp product thinking with thoughtful design and resilient engineering to create software people choose to use.</p><div className="portfolio-actions"><SiteButton href="#work">Explore our work</SiteButton><a href="/#contact">Start a project <I.ArrowUpRight/></a></div><div className="hero-proofline"><span><b>100+</b> products shipped</span><i/><span><b>15+</b> industries</span><i/><span><b>98%</b> client satisfaction</span></div></div>
      <div className="portfolio-hero-art" aria-label="A collection of Mikenium digital product interfaces"><div className="hero-art-orbit one"/><div className="hero-art-orbit two"/><div className="showcase-frame"><span className="showcase-status"><i/> LIVE PRODUCTS</span><img src="/assets/portfolio-showcase.png" alt="Analytics, media, commerce and productivity software interfaces"/><div className="showcase-shine"/></div><div className="hero-chip chip-impact"><I.TrendingUp/><span><b>42% average gain</b><small>in operational efficiency</small></span></div><div className="hero-chip chip-users"><I.UsersRound/><span><b>120K+ users</b><small>supported every day</small></span></div></div>
    </section>
    <section className="work-section" id="work"><div className="work-heading reveal"><div><span className="portfolio-kicker">OUR PROJECTS</span><h2>Built for the real world.<br/><em>Designed to stand apart.</em></h2></div><p>Explore a selection of platforms, experiences, and systems we’ve created with ambitious teams.</p></div><div className="filter-bar reveal" role="toolbar" aria-label="Filter portfolio projects">{filters.map(([label,Icon,value])=><button className={active===value?'active':''} onClick={()=>setActive(value)} aria-pressed={active===value} key={value}><Icon/>{label}<span>{value==='all'?projects.length:projects.filter(p=>p.category===value).length}</span></button>)}</div><div className="portfolio-list" key={active}>{visible.map((project,index)=><ProjectCard project={project} index={index} key={project.title}/>)}</div></section>
    <section className="portfolio-impact reveal"><div><span className="portfolio-kicker">THE WORK BEHIND THE WORK</span><h2>Good software doesn’t just look<br/>different. It <em>works better.</em></h2></div><div className="impact-stats">{[[I.Box,'120+','Projects completed'],[I.Smile,'80+','Happy clients'],[I.Award,'5+','Years of experience'],[I.Rocket,'15+','Industries served']].map(([Icon,num,label])=><article key={label}><Icon/><span><b>{num}</b><small>{label}</small></span></article>)}</div></section>
  </main><Footer/></div>
}
