import React, { useEffect, useState } from 'react';
import * as I from 'lucide-react';
import './public-home.css';

const services=[
  [I.MonitorSmartphone,'Web Development','Modern, responsive, and high-performance websites built with the latest tech.','blue'],
  [I.Smartphone,'Mobile Development','Native and cross-platform mobile apps for iOS and Android.','cyan'],
  [I.SwatchBook,'UI/UX Design','Beautiful, intuitive, and user-centered designs that drive engagement.','purple'],
  [I.Cloud,'Cloud Solutions','Scalable, secure, and reliable cloud infrastructure for your business.','blue'],
  [I.GitBranch,'DevOps & CI/CD','Automation, deployment, and continuous integration done the right way.','cyan'],
  [I.Headset,'Maintenance & Support','Ongoing support and maintenance to keep your solutions running smoothly.','purple']
];
const projects=[['FinDash','Finance Dashboard','dashboard'],['EduLearn','E-Learning Platform','learning'],['ShopHub','E-commerce Platform','commerce'],['TaskFlow','Project Management App','tasks']];
const products=[[I.PanelsTopLeft,'Mikenium CRM','Complete customer management solution.','blue',['Sales automation','Customer insights']],[I.NotebookTabs,'Mikenium CMS','Powerful content management system.','cyan',['Visual publishing','Content workflows']],[I.UserRoundCog,'Mikenium HRM','Human resource management system.','purple',['People operations','Smart reporting']],[I.ChartNoAxesCombined,'Mikenium Analytics','Advanced analytics dashboard.','green',['Live dashboards','Predictive insights']]];
const testimonials=[['James Carter','CEO, TechWave Solutions','Mikenium delivered beyond our expectations. Their team is professional, responsive, and truly understands our needs.','Web Platform','38% faster operations'],['Sarah Mitchell','CTO, CloudPeak Systems','The quality of work and attention to detail is unmatched. They became a true extension of our product team.','Cloud Modernization','99.9% uptime'],['David Anderson','Founder, NextGen Digital','Great communication, on-time delivery, and excellent support throughout the entire project.','Product Design','2.2× user growth']];
const plans=[
  {name:'Starter',description:'For teams validating a new digital idea.',monthly:49,annual:39,icon:I.Rocket,features:['One active project','Core development team','Weekly progress updates','Standard support']},
  {name:'Professional',description:'For growing businesses ready to scale.',monthly:99,annual:79,icon:I.Gem,features:['Up to three active projects','Dedicated product team','Priority delivery pipeline','Advanced integrations','Priority support'],popular:true},
  {name:'Enterprise',description:'For organizations with complex needs.',monthly:199,annual:159,icon:I.Building2,features:['Unlimited project scope','Custom engineering squad','Security and compliance','SLA-backed delivery','24/7 dedicated support']}
];
const posts=[['AI & Technology','The Future of Web Development in 2024 and Beyond','May 20, 2024','future','6 min read','The technologies and engineering practices shaping the next generation of fast, intelligent web products.'],['Business','Why Your Business Needs a Custom Software Solution','May 15, 2024','software','5 min read','How purpose-built software turns operational friction into a sustainable competitive advantage.'],['Design','UI/UX Best Practices for Better User Engagement','May 10, 2024','design','4 min read','Practical design principles that make digital products easier to use, trust, and remember.']];
const companies=[[I.Layers3,'TechWave','SOLUTIONS'],[I.Cloud,'CloudPeak','SYSTEMS'],[I.CircleDotDashed,'DataCore','ANALYTICS'],[I.Network,'NextGen','DIGITAL'],[I.Hexagon,'ByteFlow','TECHNOLOGIES'],[I.Badge,'SoftNova','SOLUTIONS']];

function Logo(){return <a className="public-logo" href="#home" aria-label="Mikenium home"><img src="/assets/mikenium-logo-transparent.png" alt="Mikenium — Building Smarter Software"/></a>}
function Button({children,outline=false,href='/contact'}){return <a className={'site-button '+(outline?'outline':'')} href={href}>{children}<I.ArrowRight/></a>}
const sectionDescriptions={
  'Services We Provide':'End-to-end technology expertise to move your business forward.',
  'Featured Projects':'A selection of digital products engineered for measurable impact.',
  'Products Built for Real Impact':'Selected platforms where thoughtful design and engineering created measurable value.',
  'Digital Products':'Ready-to-scale platforms built for modern teams and growing businesses.',
  'What Our Clients Say':'Trusted partnerships, proven delivery, and results our clients value.',
  'Insights & News':'Practical ideas on software, product strategy, and digital growth.'
};
function SectionHead({eyebrow,title,action}){return <div className="section-head-public"><div><small>{eyebrow}</small><h2>{title}</h2><p>{sectionDescriptions[title]}</p></div>{action&&<Button outline href={action.href}>{action.text}</Button>}</div>}
function MockScreen({type,label}){return <div className={'mock-screen '+type} role="img" aria-label={`${label} software interface preview`}/>}
function CompanyRow({hidden=false}){return <div className="company-row" aria-hidden={hidden}>{companies.map(([Icon,n,s],i)=><span className="company-logo" key={`${n}-${hidden?'copy':'main'}`}><span className="company-icon"><Icon/></span><i><strong>{n}</strong><small>{s}</small></i>{i<companies.length-1&&<b/>}</span>)}</div>}

export default function PublicHome(){
  const [menu,setMenu]=useState(false);
  const [annual,setAnnual]=useState(true);
  const [scrolled,setScrolled]=useState(false);
  useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>24);onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);
  return <div className="public-site">
    <div className="hero-shell" id="home">
      <header className={'public-header '+(scrolled?'scrolled ':'')+(menu?'menu-open':'')}><Logo/><div className="nav-center"><nav className={menu?'open':''}>{['Home','Services','Portfolio','Products','Pricing','Blog','About'].map((x,index)=><a className={x==='Home'?'active':''} onClick={()=>setMenu(false)} href={x==='About'?'/about':x==='Services'?'/services':x==='Portfolio'?'/portfolio':x==='Products'?'/products':x==='Pricing'?'/pricing':x==='Blog'?'/blog':'#'+x.toLowerCase()} key={x}><span>0{index+1}</span>{x}</a>)}</nav></div><div className="nav-actions"><a className="nav-contact" href="/contact"><span>Start a Project</span><I.ArrowUpRight/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu?<I.X/>:<I.Menu/>}</button></div></header>
      <section className="hero"><div className="hero-copy"><span className="pill"><i/> TECHNOLOGY BUILT FOR WHAT'S NEXT</span><h1>We engineer digital<br/>products that <span>move<br/>businesses forward.</span></h1><p>From ambitious ideas to scalable platforms, Mikenium designs and develops secure software that creates lasting business value.</p><div className="hero-actions"><Button href="/contact">Start Your Project</Button><Button outline href="#portfolio">Explore Our Work <I.PlayCircle/></Button></div><div className="hero-proof"><span><I.ShieldCheck/> Enterprise-grade security</span><span><I.Zap/> Fast, agile delivery</span><span><I.Headphones/> Dedicated support</span></div><div className="hero-stats">{[[I.BriefcaseBusiness,'100+','Projects Delivered'],[I.Heart,'50+','Happy Clients'],[I.Award,'5+','Years of Experience'],[I.Clock3,'24/7','Support']].map(([Icon,n,l])=><div key={l}><Icon/><span><b>{n}</b><small>{l}</small></span></div>)}</div></div>
        <div className="hero-visual" aria-label="Mikenium software technology ecosystem"><div className="visual-aurora"><i/><i/><i/></div><div className="hero-particles">{Array.from({length:8},(_,i)=><i key={i}/>)}</div><div className="hero-brand"><div className="brand-glow"/><img src="/assets/mikenium-logo-transparent.png" alt="Mikenium — Building Smarter Software"/><span className="brand-status"><I.Sparkles/> AI-enabled product delivery</span></div><div className="floating-tech tech-code"><span><I.Code2/></span><div><b>Clean Code</b><small>Built to scale</small></div></div><div className="floating-tech tech-cloud"><span><I.CloudCog/></span><div><b>Cloud Native</b><small>Always available</small></div></div><div className="floating-tech tech-secure"><span><I.ShieldCheck/></span><div><b>Secure by Design</b><small>Enterprise ready</small></div></div><div className="live-status"><i/><span><b>Systems operational</b><small>99.9% uptime</small></span></div></div>
      </section>
    </div>
    <section className="trusted"><div className="trust-heading"><span><i/> TRUSTED PARTNERS</span><h2>Chosen by teams building what’s next.</h2><p>We partner with ambitious companies to turn complex challenges into reliable digital products.</p></div><div className="company-marquee"><div className="company-track"><CompanyRow/><CompanyRow hidden/></div></div><div className="trust-metrics"><span><strong>98%</strong><small>Client satisfaction</small></span><i/><span><strong>15+</strong><small>Industries served</small></span><i/><span><strong>4.9/5</strong><small>Average project rating</small></span></div></section>
    <main className="public-main">
      <section className="services-showcase" id="services"><div className="services-glow"/><SectionHead eyebrow="WHAT WE DO" title="Services We Provide" action={{text:'Explore All Services',href:'/services'}}/><div className="service-cards">{services.map(([Icon,n,d,c],index)=><article className={index===3?'featured-service':''} key={n}><span className="service-number">0{index+1}</span><span className={'feature-icon '+c}><Icon/></span><div className="service-copy"><h3>{n}</h3><p>{d}</p></div><a className="service-link" href="/services#capabilities" aria-label={`Learn more about ${n}`}><span>Learn more</span><I.ArrowUpRight/></a><div className="service-scan"/></article>)}</div><div className="services-bottom"><p><I.CircleCheck/> Not sure what you need? We’ll help you choose the right technology approach.</p><Button href="#contact">Talk to an Expert</Button></div></section>
      <section className="projects-section" id="portfolio"><div className="project-orb"/><SectionHead eyebrow="SELECTED WORK" title="Products Built for Real Impact" action={{text:'Explore All Projects',href:'/portfolio'}}/><div className="project-grid">{projects.map(([n,d,t],index)=><article className={index===0?'project-featured':''} key={n}><MockScreen type={t} label={n}/><div className="project-info"><span className="project-type">{index===0?'FINTECH':index===1?'EDTECH':index===2?'COMMERCE':'PRODUCTIVITY'}</span><div className="project-title"><span><b>{n}</b><small>{d}</small></span><a href="/portfolio" aria-label={`View ${n} case study`}><I.ArrowUpRight/></a></div>{index===0&&<p>Real-time financial intelligence that turns complex data into confident decisions.</p>}<a className="project-case" href="/portfolio">View case study <I.ArrowRight/></a></div></article>)}</div><div className="project-results"><span><I.TrendingUp/><b>42%</b><small>Average efficiency gain</small></span><span><I.Gauge/><b>2.4×</b><small>Faster product delivery</small></span><span><I.UsersRound/><b>120K+</b><small>End users supported</small></span></div></section>
      <section className="products-showcase" id="products"><div className="products-heading"><SectionHead eyebrow="OUR PRODUCTS" title="Software Ready to Accelerate Growth" action={{text:'View Product Suite',href:'#products'}}/><p className="products-intro">Purpose-built platforms that simplify operations, reveal better insights, and scale alongside your business.</p></div><div className="product-grid">{products.map(([Icon,n,d,c,features],index)=><article key={n}><div className="product-card-top"><span className={'feature-icon '+c}><Icon/></span><span className="product-badge">{index===3?'INTELLIGENCE':'BUSINESS PLATFORM'}</span></div><div className="product-card-body"><span className="product-index">0{index+1}</span><h3>{n}</h3><p>{d}</p><ul>{features.map(feature=><li key={feature}><I.Check/>{feature}</li>)}</ul></div><a className="product-link" href="#contact"><span>Explore product</span><I.ArrowUpRight/></a><div className="product-glow"/></article>)}</div></section>
      <section className="pricing" id="pricing"><div className="pricing-heading"><div><small>FLEXIBLE PRICING</small><h2>Choose a plan built around your growth.</h2><p>Start with the support you need today and scale without friction tomorrow. Every plan includes transparent delivery and no hidden fees.</p></div><div className="billing-toggle" aria-label="Billing period"><button className={!annual?'active':''} onClick={()=>setAnnual(false)}>Monthly</button><button className={annual?'active':''} onClick={()=>setAnnual(true)}>Annual <span>Save 20%</span></button></div></div><div className="price-grid">{plans.map((plan)=><article className={plan.popular?'popular':''} key={plan.name}>{plan.popular&&<span className="popular-label"><I.Sparkles/> MOST POPULAR</span>}<div className="plan-head"><span className="plan-icon"><plan.icon/></span><div><h3>{plan.name}</h3><p>{plan.description}</p></div></div><div className="plan-price"><span>$</span><strong key={`${plan.name}-${annual}`}>{annual?plan.annual:plan.monthly}</strong><small>/ month</small></div><p className="billing-note">{annual?'Billed annually — save 20%':'Billed monthly, cancel anytime'}</p><ul>{plan.features.map(feature=><li key={feature}><I.CircleCheck/>{feature}</li>)}</ul><a className="plan-cta" href="#contact">{plan.popular?'Start Building':'Choose '+plan.name}<I.ArrowRight/></a></article>)}</div><div className="pricing-assurance"><span><I.ShieldCheck/> Secure, transparent contracts</span><span><I.RefreshCw/> Change plans anytime</span><span><I.Headphones/> Expert support included</span></div></section>
      <section className="testimonials-section" id="about"><div className="testimonial-heading"><SectionHead eyebrow="CLIENT STORIES" title="Trusted by Teams That Expect More" action={{text:'Explore Client Stories',href:'#about'}}/><div className="rating-summary"><strong>4.9</strong><span><b>★★★★★</b><small>Average client rating</small></span></div></div><div className="testimonial-grid">{testimonials.map(([n,r,q,project,result],i)=><article className={i===1?'testimonial-featured':''} key={n}><div className="testimonial-top"><span className="project-tag">{project}</span><span className="verified"><I.BadgeCheck/> Verified client</span></div><I.Quote className="quote-mark"/><p>{q}</p><div className="testimonial-result"><I.TrendingUp/><span><b>{result}</b><small>Project outcome</small></span></div><div className="client"><span>{n.split(' ').map(x=>x[0]).join('')}</span><div><b>{n}</b><small>{r}</small></div><div className="stars">★★★★★</div></div></article>)}</div><div className="testimonial-cta"><span><I.MessageSquareQuote/><b>Have a product idea?</b><small>Let’s turn it into your next success story.</small></span><Button href="#contact">Talk to Our Team</Button></div></section>
      <section className="insights-section" id="blog"><div className="insights-heading"><SectionHead eyebrow="ENGINEERING INSIGHTS" title="Ideas for Building What’s Next" action={{text:'Explore All Insights',href:'#blog'}}/><div className="insights-note"><I.Lightbulb/><span><b>Practical thinking</b><small>From our product, design, and engineering teams.</small></span></div></div><div className="blog-grid">{posts.map(([tag,title,date,type,readTime,excerpt],index)=><article className={index===0?'blog-featured':''} key={title}><div className={'blog-image '+type} role="img" aria-label={`${title} article cover`}><span className="image-index">0{index+1}</span><span className="image-arrow"><I.ArrowUpRight/></span></div><div className="blog-content"><div className="blog-meta"><span className="tag">{tag}</span><span><time>{date}</time><i/> {readTime}</span></div><h3>{title}</h3><p>{excerpt}</p><a href="#blog">Read article <I.ArrowRight/></a></div></article>)}</div><div className="insights-subscribe"><span className="subscribe-icon"><I.MailPlus/></span><div><b>Stay ahead of the curve.</b><small>Monthly insights on software, design, AI, and digital growth—straight to your inbox.</small></div><form onSubmit={e=>e.preventDefault()}><input type="email" aria-label="Email address" placeholder="you@company.com" required/><button>Subscribe <I.ArrowRight/></button></form></div></section>
    </main>
    <footer id="contact"><div className="footer-glow"/><div className="cta"><div><span className="cta-label"><i/> LET’S CREATE TOGETHER</span><h2>Ready to build software<br/>that moves your business?</h2><p>Bring us the challenge. We’ll bring the strategy, design, and engineering to turn it into a product people value.</p></div><div className="cta-actions"><Button>Start a Conversation</Button><a href="mailto:hello@mikenium.com">hello@mikenium.com <I.ArrowUpRight/></a></div></div><div className="footer-main"><div className="footer-about"><img src="/assets/mikenium-logo-transparent.png" alt="Mikenium — Building Smarter Software"/><p>We design and engineer secure digital products that help ambitious businesses grow with confidence.</p><span className="footer-socials">{[I.Facebook,I.Linkedin,I.Twitter,I.Github,I.Instagram].map((Icon,i)=><a href="#home" aria-label="Social link" key={i}><Icon/></a>)}</span></div><div className="footer-links"><div><h4>Company</h4>{['About Us','Our Work','Careers','Contact'].map(x=><a href={x==='About Us'?'/about':'#home'} key={x}>{x}</a>)}</div><div><h4>Expertise</h4>{['Web Development','Mobile Apps','Cloud Solutions','UI/UX Design'].map(x=><a href="/services#capabilities" key={x}>{x}</a>)}</div><div><h4>Resources</h4>{['Insights','Products','Pricing','Client Stories'].map(x=><a href="#blog" key={x}>{x}</a>)}</div></div><div className="footer-contact"><span><I.MapPin/></span><div><h4>Let’s talk about your next idea.</h4><a href="mailto:hello@mikenium.com">hello@mikenium.com</a><a href="tel:+94112345678">+94 11 234 5678</a><small>Colombo, Sri Lanka</small></div></div></div><div className="footer-bottom"><p>© 2026 Mikenium. All rights reserved.</p><nav><a href="#home">Privacy Policy</a><a href="#home">Terms of Service</a><a href="#home">Cookie Policy</a></nav><span><i/> All systems operational</span></div></footer>
  </div>
}
