import React,{useEffect,useMemo,useState} from 'react';
import * as I from 'lucide-react';
import { createUser,deleteUser,getUser,getUsers,updateUser } from '../../../services/admin/admin-api';

const roleLabels={SUPER_ADMIN:'Super Admin',ADMIN:'Administrator',EDITOR:'Editor',CLIENT:'Client',AUTHOR:'Author',SUBSCRIBER:'Subscriber'};
const roleValues={Administrator:'ADMIN',Editor:'EDITOR',Client:'CLIENT',Author:'AUTHOR',Subscriber:'SUBSCRIBER'};
const tones={SUPER_ADMIN:'navy',ADMIN:'amber',EDITOR:'rose',CLIENT:'blue',AUTHOR:'teal',SUBSCRIBER:'rose'};
const displayDate=value=>value?new Date(value).toLocaleString(undefined,{year:'numeric',month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const adapt=user=>({...user,handle:user.username,roleLabel:roleLabels[user.role]||user.role,status:user.active?'Active':'Inactive',verified:user.emailVerified,joined:displayDate(user.createdAt),login:displayDate(user.lastLoginAt),tone:tones[user.role]||'blue'});

const initialForm={name:'',username:'',email:'',password:'',role:'CLIENT',active:true,emailVerified:false};
function UserModal({user,onClose,onSave,saving}){
  const [form,setForm]=useState(user?{name:user.name,username:user.username,email:user.email,password:'',role:user.role,active:user.active,emailVerified:user.emailVerified}:initialForm);
  const change=event=>{const {name,value}=event.target;setForm(current=>({...current,[name]:name==='active'||name==='emailVerified'?value==='true':value}))};
  const editing=Boolean(user);
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal user-modal" onMouseDown={event=>event.stopPropagation()} onSubmit={event=>{event.preventDefault();onSave(form)}}>
    <div className="modal-head"><div><h2>{editing?'Edit User':'Add New User'}</h2><p>{editing?'Update account details and access.':'Create a database-backed account.'}</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div>
    <label>Full name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. Alex Morgan"/></label>
    <label>Username<input name="username" required minLength="3" value={form.username} onChange={change} placeholder="alex.morgan"/></label>
    <label>Email address<input name="email" required type="email" value={form.email} onChange={change} placeholder="alex@example.com"/></label>
    <label>{editing?'New password (optional)':'Temporary password'}<input name="password" required={!editing} minLength="12" type="password" autoComplete="new-password" value={form.password} onChange={change} placeholder="At least 12 characters"/></label>
    <label>Role<select name="role" value={form.role} onChange={change}>{Object.entries(roleValues).map(([label,value])=><option value={value} key={value}>{label}</option>)}</select></label>
    <label>Status<select name="active" value={String(form.active)} onChange={change}><option value="true">Active</option><option value="false">Inactive</option></select></label>
    <label>Email verification<select name="emailVerified" value={String(form.emailVerified)} onChange={change}><option value="false">Not verified</option><option value="true">Verified</option></select></label>
    <div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?<I.LoaderCircle className="spin"/>:editing?<I.Save/>:<I.UserPlus/>}{saving?'Saving...':editing?'Save Changes':'Add User'}</button></div>
  </form></div>;
}

function UserDetails({user,onClose,onEdit}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal user-modal" onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><h2>User Details</h2><p>Live account data from PostgreSQL.</p></div><button onClick={onClose} aria-label="Close"><I.X/></button></div><div className="user-detail-list"><p><span>Name</span><b>{user.name}</b></p><p><span>Username</span><b>@{user.username}</b></p><p><span>Email</span><b>{user.email}</b></p><p><span>Role</span><b>{roleLabels[user.role]}</b></p><p><span>Status</span><b>{user.active?'Active':'Inactive'}</b></p><p><span>Email verified</span><b>{user.emailVerified?'Yes':'No'}</b></p><p><span>Created</span><b>{displayDate(user.createdAt)}</b></p><p><span>Last login</span><b>{displayDate(user.lastLoginAt)}</b></p></div><div className="modal-actions"><button onClick={onClose}>Close</button>{user.role!=='SUPER_ADMIN'&&<button className="primary" onClick={()=>onEdit(user)}><I.Pencil/> Edit User</button>}</div></div></div>}

export function UsersPage(){
  const [users,setUsers]=useState([]),[stats,setStats]=useState({total:0,administrators:0,clients:0,subscribers:0,inactive:0}),[query,setQuery]=useState(''),[role,setRole]=useState('All Roles'),[status,setStatus]=useState('All Status'),[verified,setVerified]=useState('Email Verified'),[modal,setModal]=useState(null),[details,setDetails]=useState(null),[toast,setToast]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[selected,setSelected]=useState([]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const load=async()=>{setLoading(true);setError('');try{const data=await getUsers();setUsers(data.users.map(adapt));setStats(data.stats)}catch(err){setError(err.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>users.filter(user=>{const matchesQuery=[user.name,user.handle,user.email,user.roleLabel].join(' ').toLowerCase().includes(query.toLowerCase());return matchesQuery&&(role==='All Roles'||user.roleLabel===role)&&(status==='All Status'||user.status===status)&&(verified==='Email Verified'||(verified==='Verified'?user.verified:!user.verified))}),[users,query,role,status,verified]);
  const statItems=[['Total Users',stats.total,I.Users,'blue'],['Administrators',stats.administrators,I.ShieldCheck,'purple'],['Clients',stats.clients,I.BriefcaseBusiness,'green'],['Subscribers',stats.subscribers,I.Mail,'orange'],['Inactive Users',stats.inactive,I.UserRoundX,'pink']];
  const save=async form=>{setSaving(true);setError('');try{const payload={...form,username:form.username.trim()||undefined};if(modal?.id&&!payload.password)delete payload.password;if(modal?.id)await updateUser(modal.id,payload);else await createUser(payload);setModal(null);flash(modal?.id?'User updated successfully':'User created successfully');await load()}catch(err){setError(err.message)}finally{setSaving(false)}};
  const view=async id=>{setError('');try{setDetails((await getUser(id)).user)}catch(err){setError(err.message)}};
  const remove=async user=>{if(!window.confirm(`Delete ${user.name}? This cannot be undone.`))return;setError('');try{await deleteUser(user.id);setSelected(current=>current.filter(id=>id!==user.id));flash('User deleted successfully');await load()}catch(err){setError(err.message)}};
  const toggle=id=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(user=>selected.includes(user.id))?selected.filter(id=>!filtered.some(user=>user.id===id)):[...new Set([...selected,...filtered.map(user=>user.id)])]);
  const exportUsers=()=>{const header='Name,Username,Email,Role,Status,Email Verified,Joined,Last Login';const rows=filtered.map(user=>[user.name,user.handle,user.email,user.roleLabel,user.status,user.verified?'Yes':'No',user.joined,user.login].map(value=>`"${String(value).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='mikenium-users.csv';anchor.click();URL.revokeObjectURL(url);flash('User list exported')};
  return <div className="users-page"><div className="users-heading"><div><h1>Users</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Users</span></div></div><button className="users-add" onClick={()=>setModal({})}><I.Plus/> Add New User</button></div>
    <div className="user-stats">{statItems.map(([title,value,Icon,color])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{Number(value).toLocaleString()}</b><p>Live database total</p></div></div>)}</div>
    {error&&<div className="admin-inline-error"><I.CircleAlert/>{error}<button onClick={()=>setError('')}><I.X/></button></div>}
    <div className="card users-table-card"><div className="users-toolbar"><div className="users-search"><I.Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search users..."/></div><select value={role} onChange={event=>setRole(event.target.value)}><option>All Roles</option>{Object.keys(roleValues).map(value=><option key={value}>{value}</option>)}</select><select value={status} onChange={event=>setStatus(event.target.value)}><option>All Status</option><option>Active</option><option>Inactive</option></select><select value={verified} onChange={event=>setVerified(event.target.value)}><option>Email Verified</option><option>Verified</option><option>Not Verified</option></select><div className="toolbar-spacer"/><button onClick={load} disabled={loading}>{loading?<I.LoaderCircle className="spin"/>:<I.RefreshCw/>} Refresh</button><button onClick={exportUsers}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(user=>selected.includes(user.id))} onChange={toggleAll}/></th><th>User</th><th>Role</th><th>Email</th><th>Status</th><th>Email Verified</th><th>Joined On</th><th>Last Login</th><th>Actions</th></tr></thead><tbody>{filtered.map(user=><tr key={user.id}><td><input type="checkbox" checked={selected.includes(user.id)} onChange={()=>toggle(user.id)}/></td><td><div className="user-identity"><span className={`user-avatar ${user.tone}`}>{user.name.split(' ').map(name=>name[0]).slice(0,2).join('')}</span><span><b>{user.name}</b><small>@{user.handle}</small></span></div></td><td><span className={`role-pill ${user.roleLabel.toLowerCase().replace(' ','-')}`}>{user.roleLabel}</span></td><td className="user-email">{user.email}</td><td><span className={`user-status ${user.status.toLowerCase()}`}>{user.status}</span></td><td><span className={user.verified?'verified-yes':'verified-no'}>{user.verified?<I.CircleCheck/>:<I.CircleX/>}</span></td><td>{user.joined}</td><td>{user.login}</td><td><div className="user-actions"><button className="edit-user" title={user.role==='SUPER_ADMIN'?'Protected super-admin account':'Edit user'} disabled={user.role==='SUPER_ADMIN'} onClick={()=>setModal(user)}><I.Pencil/><span>Edit</span></button><button title="View user" onClick={()=>view(user.id)}><I.Eye/></button><button className="danger" title="Delete user" disabled={user.role==='SUPER_ADMIN'} onClick={()=>remove(user)}><I.Trash2/></button></div></td></tr>)}</tbody></table>{loading?<div className="empty"><I.LoaderCircle className="spin"/><b>Loading users...</b></div>:!filtered.length&&<div className="empty"><I.SearchX/><b>No users found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer"><span>Showing {filtered.length} of {stats.total} database users</span></div></div>
    {modal&&<UserModal user={modal.id?modal:null} onClose={()=>setModal(null)} onSave={save} saving={saving}/>} {details&&<UserDetails user={details} onClose={()=>setDetails(null)} onEdit={user=>{setDetails(null);setModal(adapt(user))}}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>;
}
