import React,{useEffect,useMemo,useState} from 'react';
import * as I from 'lucide-react';
import { createPricingPlan,deletePricingPlan,getPricingPlans,updatePricingPlan } from '../../../services/admin/admin-api';

const statuses={PUBLISHED:'Published',DRAFT:'Draft',ARCHIVED:'Archived'};
const icons={rocket:I.Rocket,zap:I.Zap,chart:I.ChartNoAxesCombined,shield:I.ShieldCheck,building:I.Building2,gem:I.Gem,star:I.Star,briefcase:I.BriefcaseBusiness};
const empty={name:'',eyebrow:'',description:'',monthlyPrice:'',annualPrice:'',monthlyPriceLkr:'',annualPriceLkr:'',monthlyPriceAud:'',annualPriceAud:'',billingSuffix:'/ month',features:'',ctaLabel:'Get started',ctaUrl:'/contact',icon:'rocket',custom:false,popular:false,status:'PUBLISHED',order:0};

function PlanModal({plan,onClose,onSave,saving}){
  const [form,setForm]=useState(plan?{...plan,monthlyPrice:plan.prices?.USD?.monthly??'',annualPrice:plan.prices?.USD?.annual??'',monthlyPriceLkr:plan.prices?.LKR?.monthly??'',annualPriceLkr:plan.prices?.LKR?.annual??'',monthlyPriceAud:plan.prices?.AUD?.monthly??'',annualPriceAud:plan.prices?.AUD?.annual??'',features:(plan.features||[]).join(', ')}:empty);
  const change=e=>{const {name,value}=e.target;setForm(current=>({...current,[name]:['custom','popular'].includes(name)?value==='true':value}))};
  const submit=e=>{e.preventDefault();const price=value=>form.custom?'':Number(value);onSave({...form,monthlyPrice:price(form.monthlyPrice),annualPrice:price(form.annualPrice),monthlyPriceLkr:price(form.monthlyPriceLkr),annualPriceLkr:price(form.annualPriceLkr),monthlyPriceAud:price(form.monthlyPriceAud),annualPriceAud:price(form.annualPriceAud),order:Number(form.order),features:form.features.split(',').map(x=>x.trim()).filter(Boolean)})};
  const PriceInput=({currency,monthly,annual})=><><label>{currency} monthly<input required type="number" min="0" step=".01" name={monthly} value={form[monthly]} onChange={change}/></label><label>{currency} annual/month<input required type="number" min="0" step=".01" name={annual} value={form[annual]} onChange={change}/></label></>;
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal pricing-admin-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={submit}><div className="modal-head"><div><h2>{plan?'Edit Pricing Plan':'Add Pricing Plan'}</h2><p>Published plans appear on the Home and Pricing pages.</p></div><button type="button" onClick={onClose}><I.X/></button></div><div className="client-form-grid">
    <label>Plan name<input required autoFocus name="name" value={form.name} onChange={change}/></label><label>Eyebrow<input name="eyebrow" value={form.eyebrow} onChange={change} placeholder="GROW"/></label>
    <label className="wide">Description<textarea required minLength="10" name="description" value={form.description} onChange={change}/></label>
    <label>Custom pricing<select name="custom" value={String(form.custom)} onChange={change}><option value="false">No</option><option value="true">Yes — Contact sales</option></select></label><label>Billing suffix<input name="billingSuffix" value={form.billingSuffix} onChange={change}/></label>
    {!form.custom&&<div className="pricing-currency-fields wide"><h3>Costs by currency</h3><p>Enter the exact amounts to display. Currency values are manually controlled and are not automatically converted.</p><div><PriceInput currency="USD" monthly="monthlyPrice" annual="annualPrice"/><PriceInput currency="LKR" monthly="monthlyPriceLkr" annual="annualPriceLkr"/><PriceInput currency="AUD" monthly="monthlyPriceAud" annual="annualPriceAud"/></div></div>}
    <label>Icon<select name="icon" value={form.icon} onChange={change}>{Object.keys(icons).map(x=><option key={x}>{x}</option>)}</select></label>
    <label className="wide">Features<input name="features" value={form.features} onChange={change} placeholder="5 projects, Priority support, API access"/></label><label>CTA label<input name="ctaLabel" value={form.ctaLabel} onChange={change}/></label><label>CTA URL<input name="ctaUrl" value={form.ctaUrl} onChange={change}/></label>
    <label>Most popular<select name="popular" value={String(form.popular)} onChange={change}><option value="false">No</option><option value="true">Yes</option></select></label><label>Status<select name="status" value={form.status} onChange={change}>{Object.entries(statuses).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Display order<input type="number" min="0" name="order" value={form.order} onChange={change}/></label>
  </div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?<I.LoaderCircle className="spin"/>:plan?<I.Save/>:<I.Plus/>}{saving?'Saving...':plan?'Save Changes':'Add Plan'}</button></div></form></div>
}

export function PricingAdminPage(){
  const [plans,setPlans]=useState([]),[stats,setStats]=useState({total:0,published:0,draft:0,popular:0}),[query,setQuery]=useState(''),[status,setStatus]=useState('All Status'),[modal,setModal]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[toast,setToast]=useState('');
  const flash=x=>{setToast(x);setTimeout(()=>setToast(''),2500)};
  const load=async()=>{setLoading(true);setError('');try{const data=await getPricingPlans();setPlans(data.plans);setStats(data.stats)}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>plans.filter(p=>[p.name,p.description,p.eyebrow].join(' ').toLowerCase().includes(query.toLowerCase())&&(status==='All Status'||statuses[p.status]===status)),[plans,query,status]);
  const save=async form=>{setSaving(true);try{if(modal?.id)await updatePricingPlan(modal.id,form);else await createPricingPlan(form);setModal(null);flash('Pricing plan saved');await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
  const remove=async p=>{if(!window.confirm(`Delete ${p.name}?`))return;try{await deletePricingPlan(p.id);flash('Pricing plan deleted');await load()}catch(e){setError(e.message)}};
  const cards=[['Total Plans',stats.total,I.BadgeDollarSign,'blue'],['Published',stats.published,I.CircleCheckBig,'green'],['Draft',stats.draft,I.Clock3,'orange'],['Popular',stats.popular,I.Star,'purple']];
  return <div className="users-page pricing-admin-page"><div className="users-heading"><div><h1>Pricing Plans</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Pricing</span></div></div><button className="users-add" onClick={()=>setModal({})}><I.Plus/> Add Pricing Plan</button></div>
    <div className="product-stats">{cards.map(([t,v,Icon,c])=><div className="card product-stat" key={t}><span className={`user-stat-icon ${c}`}><Icon/></span><div><small>{t}</small><b>{Number(v).toLocaleString()}</b><p>Live database total</p></div></div>)}</div>
    {error&&<div className="admin-inline-error"><I.CircleAlert/>{error}<button onClick={()=>setError('')}><I.X/></button></div>}
    <div className="card users-table-card"><div className="users-toolbar"><div className="users-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pricing plans..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option>{Object.values(statuses).map(x=><option key={x}>{x}</option>)}</select><div className="toolbar-spacer"/><button onClick={load}><I.RefreshCw/> Refresh</button></div>
      <div className="users-table-wrap"><table className="users-table pricing-admin-table"><thead><tr><th>Plan</th><th>USD monthly</th><th>LKR monthly</th><th>AUD monthly</th><th>Features</th><th>Status</th><th>Popular</th><th>Order</th><th>Actions</th></tr></thead><tbody>{filtered.map(p=>{const Icon=icons[p.icon]||I.Rocket;return <tr key={p.id}><td><div className="product-identity"><span className="product-thumb blue"><Icon/></span><span><b>{p.name}</b><small>{p.description}</small></span></div></td><td>{p.custom?'Custom':`$ ${p.prices.USD.monthly}`}</td><td>{p.custom?'Custom':`Rs. ${Number(p.prices.LKR.monthly).toLocaleString()}`}</td><td>{p.custom?'Custom':`A$ ${p.prices.AUD.monthly}`}</td><td>{p.features.length}</td><td><span className={`product-status ${statuses[p.status].toLowerCase()}`}>{statuses[p.status]}</span></td><td>{p.popular?<I.Star className="feature-star active" fill="currentColor"/>:'—'}</td><td>{p.order}</td><td><div className="user-actions"><button className="edit-user" onClick={()=>setModal(p)}><I.Pencil/><span>Edit</span></button><button className="danger" onClick={()=>remove(p)}><I.Trash2/></button></div></td></tr>})}</tbody></table>{loading?<div className="empty"><I.LoaderCircle className="spin"/><b>Loading pricing...</b></div>:!filtered.length&&<div className="empty"><I.SearchX/><b>No pricing plans found</b><span>Add a plan to publish it publicly.</span></div>}</div><div className="users-footer"><span>Showing {filtered.length} of {stats.total} database plans</span></div></div>
    {modal&&<PlanModal plan={modal.id?modal:null} onClose={()=>setModal(null)} onSave={save} saving={saving}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}
