import React, { useMemo, useState } from 'react';
import * as I from 'lucide-react';

const serviceSeed=[
  {name:'Web Development',description:'Custom websites and web applications',category:'Development',type:'Core Service',status:'Published',order:1,created:'May 10, 2024',Icon:I.CodeXml,tone:'blue'},
  {name:'Mobile Development',description:'iOS and Android app development',category:'Development',type:'Core Service',status:'Published',order:2,created:'May 11, 2024',Icon:I.Smartphone,tone:'green'},
  {name:'UI/UX Design',description:'User interface and experience design',category:'Design',type:'Core Service',status:'Published',order:3,created:'May 12, 2024',Icon:I.TabletSmartphone,tone:'orange'},
  {name:'Cloud Solutions',description:'Scalable cloud infrastructure',category:'Cloud',type:'Core Service',status:'Published',order:4,created:'May 13, 2024',Icon:I.Cloud,tone:'purple'},
  {name:'E-Commerce Solutions',description:'Online store development',category:'Development',type:'Core Service',status:'Draft',order:5,created:'May 14, 2024',Icon:I.ShoppingCart,tone:'pink'},
  {name:'Maintenance & Support',description:'Ongoing maintenance and support',category:'Support',type:'Support Service',status:'Published',order:6,created:'May 15, 2024',Icon:I.Settings,tone:'cyan'},
  {name:'Digital Marketing',description:'SEO, SEM and social media marketing',category:'Marketing',type:'Support Service',status:'Inactive',order:7,created:'May 16, 2024',Icon:I.ChartNoAxesCombined,tone:'purple'},
  {name:'Cyber Security',description:'Security assessment and protection',category:'Security',type:'Support Service',status:'Published',order:8,created:'May 17, 2024',Icon:I.ShieldCheck,tone:'yellow'}
];

const serviceStats=[['Total Services','24','14.3%',I.Package,'purple',true],['Published','20','11.1%',I.SquareCheckBig,'green',true],['Draft','2','33.3%',I.Clock3,'orange',false],['Inactive','2','0%',I.CirclePause,'blue',null],['Trash','0','0%',I.Trash2,'pink',null]];

function ServiceModal({onClose,onSave}){const [form,setForm]=useState({name:'',description:'',category:'Development',type:'Core Service',status:'Published'});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal service-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Service</h2><p>Create a service and configure its visibility.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label className="wide">Service name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. API Development"/></label><label className="wide">Description<input name="description" required value={form.description} onChange={change} placeholder="Short service description"/></label><label>Category<select name="category" value={form.category} onChange={change}><option>Development</option><option>Design</option><option>Cloud</option><option>Support</option><option>Marketing</option><option>Security</option></select></label><label>Service type<select name="type" value={form.type} onChange={change}><option>Core Service</option><option>Support Service</option></select></label><label className="wide">Status<select name="status" value={form.status} onChange={change}><option>Published</option><option>Draft</option><option>Inactive</option></select></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Service</button></div></form></div>}

export function ServicesPage(){
  const [services,setServices]=useState(serviceSeed),[query,setQuery]=useState(''),[category,setCategory]=useState('All Categories'),[status,setStatus]=useState('All Status'),[type,setType]=useState('All Service Types'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]);
  const filtered=useMemo(()=>services.filter(s=>[s.name,s.description,s.category,s.type].join(' ').toLowerCase().includes(query.toLowerCase())&&(category==='All Categories'||s.category===category)&&(status==='All Status'||s.status===status)&&(type==='All Service Types'||s.type===type)),[services,query,category,status,type]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addService=form=>{setServices([{...form,order:services.length+1,created:'Jul 14, 2026',Icon:I.Box,tone:'blue'},...services]);setModal(false);flash('Service added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(s=>selected.includes(s.name))?selected.filter(id=>!filtered.some(s=>s.name===id)):[...new Set([...selected,...filtered.map(s=>s.name)])]);
  const exportServices=()=>{const header='Service,Description,Category,Type,Status,Order,Created At';const rows=filtered.map(s=>[s.name,s.description,s.category,s.type,s.status,s.order,s.created].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-services.csv';a.click();URL.revokeObjectURL(url);flash('Service list exported')};
  return <div className="users-page services-page">
    <div className="users-heading"><div><h1>Services</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Services</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Service</button></div>
    <div className="user-stats">{serviceStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up===false?'down':'up'}>{up===true&&<I.ArrowUp/>}{up===false&&<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
    <div className="card users-table-card">
      <div className="users-toolbar"><div className="users-search service-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search services..."/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option>All Categories</option>{[...new Set(serviceSeed.map(s=>s.category))].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Published</option><option>Draft</option><option>Inactive</option></select><select value={type} onChange={e=>setType(e.target.value)}><option>All Service Types</option><option>Core Service</option><option>Support Service</option></select><div className="toolbar-spacer"/><button><I.ListFilter/> Filter</button><button onClick={exportServices}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table services-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(s=>selected.includes(s.name))} onChange={toggleAll}/></th><th>#</th><th>Service Name</th><th>Category</th><th>Type</th><th>Status</th><th>Order</th><th>Created At</th><th>Actions</th></tr></thead><tbody>{filtered.map((s,index)=>{const Icon=s.Icon;return <tr key={s.name}><td><input type="checkbox" checked={selected.includes(s.name)} onChange={()=>toggle(s.name)}/></td><td>{index+1}</td><td><div className="service-identity"><span className={`service-icon ${s.tone}`}><Icon/></span><span><b>{s.name}</b><small>{s.description}</small></span></div></td><td><span className={`service-category ${s.category.toLowerCase()}`}>{s.category}</span></td><td><span className={`service-type ${s.type.startsWith('Core')?'core':'support'}`}>{s.type.startsWith('Core')?<I.Box/>:<I.Headphones/>}{s.type}</span></td><td><span className={`service-status ${s.status.toLowerCase()}`}>{s.status}</span></td><td><span className="service-order"><I.GripVertical/>{s.order}</span></td><td>{s.created}</td><td><div className="user-actions"><button title="Edit service" onClick={()=>flash(`Editing ${s.name}`)}><I.Pencil/></button><button title="View service" onClick={()=>flash(`Viewing ${s.name}`)}><I.Eye/></button><button className="more" title="More actions"><I.EllipsisVertical/></button></div></td></tr>})}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No services found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer"><span>Showing 1 to {filtered.length} of 24 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>3</button><button aria-label="Next"><I.ChevronRight/></button></div></div>
    </div>
    {modal&&<ServiceModal onClose={()=>setModal(false)} onSave={addService}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}
