import React,{useEffect,useMemo,useState} from 'react';
import * as I from 'lucide-react';
import { createService,deleteService,getService,getServices,updateService } from '../../../services/admin/admin-api';

const categories=['Development','Design','Cloud','Support','Marketing','Security'];
const icons={code:I.CodeXml,mobile:I.Smartphone,design:I.TabletSmartphone,cloud:I.Cloud,commerce:I.ShoppingCart,support:I.Headphones,security:I.ShieldCheck,marketing:I.ChartNoAxesCombined,database:I.Database,automation:I.Workflow};
const iconLabels={code:'Code',mobile:'Mobile',design:'Design',cloud:'Cloud',commerce:'Commerce',support:'Support',security:'Security',marketing:'Marketing',database:'Database',automation:'Automation'};
const statuses={PUBLISHED:'Published',DRAFT:'Draft',INACTIVE:'Inactive'};
const emptyForm={name:'',description:'',category:'Development',type:'Core Service',status:'PUBLISHED',order:0,tagline:'',features:'',icon:'code'};
const formatDate=value=>new Date(value).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'});

function ServiceModal({service,onClose,onSave,saving}){
  const [form,setForm]=useState(service?{...service,features:(service.features||[]).join(', ')}:emptyForm);
  const change=event=>setForm(current=>({...current,[event.target.name]:event.target.value}));
  const submit=event=>{event.preventDefault();onSave({...form,order:Number(form.order),features:form.features.split(',').map(item=>item.trim()).filter(Boolean)})};
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal service-modal" onMouseDown={event=>event.stopPropagation()} onSubmit={submit}><div className="modal-head"><div><h2>{service?'Edit Service':'Add New Service'}</h2><p>Published services appear automatically on the Home and Services pages.</p></div><button type="button" onClick={onClose}><I.X/></button></div><div className="client-form-grid">
    <label className="wide">Service name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. API Development"/></label>
    <label className="wide">Description<textarea name="description" required minLength="10" value={form.description} onChange={change} placeholder="Describe the service for public visitors"/></label>
    <label>Category<select name="category" value={form.category} onChange={change}>{categories.map(value=><option key={value}>{value}</option>)}</select></label>
    <label>Service type<select name="type" value={form.type} onChange={change}><option>Core Service</option><option>Support Service</option></select></label>
    <label>Status<select name="status" value={form.status} onChange={change}>{Object.entries(statuses).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>
    <label>Display order<input name="order" type="number" min="0" max="999" value={form.order} onChange={change}/></label>
    <label>Icon<select name="icon" value={form.icon} onChange={change}>{Object.entries(iconLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>
    <label>Public tagline<input name="tagline" value={form.tagline} onChange={change} placeholder="BUILT FOR GROWTH"/></label>
    <label className="wide">Service features<input name="features" value={form.features} onChange={change} placeholder="Web applications, API integrations, Enterprise portals"/></label>
  </div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?<I.LoaderCircle className="spin"/>:service?<I.Save/>:<I.Plus/>}{saving?'Saving...':service?'Save Changes':'Add Service'}</button></div></form></div>
}

function ServiceDetails({service,onClose,onEdit}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal service-modal" onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><h2>{service.name}</h2><p>{service.description}</p></div><button onClick={onClose}><I.X/></button></div><div className="user-detail-list">{[['Category',service.category],['Type',service.type],['Status',statuses[service.status]],['Order',service.order],['Tagline',service.tagline||'—'],['Features',(service.features||[]).join(', ')||'—']].map(([label,value])=><p key={label}><span>{label}</span><b>{value}</b></p>)}</div><div className="modal-actions"><button onClick={onClose}>Close</button><button className="primary" onClick={()=>onEdit(service)}><I.Pencil/> Edit Service</button></div></div></div>}

export function ServicesPage(){
  const [services,setServices]=useState([]),[stats,setStats]=useState({total:0,published:0,draft:0,inactive:0}),[query,setQuery]=useState(''),[category,setCategory]=useState('All Categories'),[status,setStatus]=useState('All Status'),[type,setType]=useState('All Service Types'),[modal,setModal]=useState(null),[details,setDetails]=useState(null),[toast,setToast]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[selected,setSelected]=useState([]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const load=async()=>{setLoading(true);setError('');try{const data=await getServices();setServices(data.services);setStats(data.stats)}catch(err){setError(err.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>services.filter(service=>[service.name,service.description,service.category,service.type].join(' ').toLowerCase().includes(query.toLowerCase())&&(category==='All Categories'||service.category===category)&&(status==='All Status'||statuses[service.status]===status)&&(type==='All Service Types'||service.type===type)),[services,query,category,status,type]);
  const statItems=[['Total Services',stats.total,I.Package,'purple'],['Published',stats.published,I.SquareCheckBig,'green'],['Draft',stats.draft,I.Clock3,'orange'],['Inactive',stats.inactive,I.CirclePause,'blue']];
  const save=async form=>{setSaving(true);setError('');try{if(modal?.id)await updateService(modal.id,form);else await createService(form);const editing=Boolean(modal?.id);setModal(null);flash(editing?'Service updated successfully':form.status==='PUBLISHED'?'Service created and published successfully':'Service created successfully');await load()}catch(err){setError(err.message)}finally{setSaving(false)}};
  const view=async id=>{try{setDetails((await getService(id)).service)}catch(err){setError(err.message)}};
  const remove=async service=>{if(!window.confirm(`Delete ${service.name}? It will be removed from public pages.`))return;try{await deleteService(service.id);flash('Service deleted successfully');await load()}catch(err){setError(err.message)}};
  const toggle=id=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(service=>selected.includes(service.id))?selected.filter(id=>!filtered.some(service=>service.id===id)):[...new Set([...selected,...filtered.map(service=>service.id)])]);
  const exportServices=()=>{const header='Service,Description,Category,Type,Status,Order';const rows=filtered.map(service=>[service.name,service.description,service.category,service.type,statuses[service.status],service.order].map(value=>`"${String(value).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='mikenium-services.csv';anchor.click();URL.revokeObjectURL(url);flash('Service list exported')};
  return <div className="users-page services-page">
    <div className="users-heading"><div><h1>Services</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Services</span></div></div><button className="users-add" onClick={()=>setModal({})}><I.Plus/> Add New Service</button></div>
    <div className="user-stats">{statItems.map(([title,value,Icon,color])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{Number(value).toLocaleString()}</b><p>Live database total</p></div></div>)}</div>
    {error&&<div className="admin-inline-error"><I.CircleAlert/>{error}<button onClick={()=>setError('')}><I.X/></button></div>}
    <div className="card users-table-card"><div className="users-toolbar"><div className="users-search service-search"><I.Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search services..."/></div><select value={category} onChange={event=>setCategory(event.target.value)}><option>All Categories</option>{categories.map(value=><option key={value}>{value}</option>)}</select><select value={status} onChange={event=>setStatus(event.target.value)}><option>All Status</option>{Object.values(statuses).map(value=><option key={value}>{value}</option>)}</select><select value={type} onChange={event=>setType(event.target.value)}><option>All Service Types</option><option>Core Service</option><option>Support Service</option></select><div className="toolbar-spacer"/><button onClick={load} disabled={loading}>{loading?<I.LoaderCircle className="spin"/>:<I.RefreshCw/>} Refresh</button><button onClick={exportServices}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table services-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(service=>selected.includes(service.id))} onChange={toggleAll}/></th><th>#</th><th>Service Name</th><th>Category</th><th>Type</th><th>Status</th><th>Order</th><th>Created At</th><th>Actions</th></tr></thead><tbody>{filtered.map((service,index)=>{const Icon=icons[service.icon]||I.CodeXml;return <tr key={service.id}><td><input type="checkbox" checked={selected.includes(service.id)} onChange={()=>toggle(service.id)}/></td><td>{index+1}</td><td><div className="service-identity"><span className="service-icon"><Icon/></span><span><b>{service.name}</b><small>{service.description}</small></span></div></td><td><span className={`service-category ${service.category.toLowerCase()}`}>{service.category}</span></td><td><span className={`service-type ${service.type.startsWith('Core')?'core':'support'}`}>{service.type.startsWith('Core')?<I.Box/>:<I.Headphones/>}{service.type}</span></td><td><span className={`service-status ${statuses[service.status].toLowerCase()}`}>{statuses[service.status]}</span></td><td><span className="service-order"><I.GripVertical/>{service.order}</span></td><td>{formatDate(service.createdAt)}</td><td><div className="user-actions"><button className="edit-user" onClick={()=>setModal(service)}><I.Pencil/><span>Edit</span></button><button onClick={()=>view(service.id)}><I.Eye/></button><button className="danger" onClick={()=>remove(service)}><I.Trash2/></button></div></td></tr>})}</tbody></table>{loading?<div className="empty"><I.LoaderCircle className="spin"/><b>Loading services...</b></div>:!filtered.length&&<div className="empty"><I.SearchX/><b>No services found</b><span>Add a service to publish it on the website.</span></div>}</div>
      <div className="users-footer"><span>Showing {filtered.length} of {stats.total} database services</span></div>
    </div>
    {modal&&<ServiceModal service={modal.id?modal:null} onClose={()=>setModal(null)} onSave={save} saving={saving}/>} {details&&<ServiceDetails service={details} onClose={()=>setDetails(null)} onEdit={service=>{setDetails(null);setModal(service)}}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}
