import {Router} from 'express';
import {pool} from '../config/db.js';
import {requireSuperAdmin} from '../middleware/auth.js';
const router=Router();router.use(requireSuperAdmin);
const title=value=>String(value||'').toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const moduleOf=action=>{const key=String(action).split('_')[0];return ({SUPER:'Authentication',SITE:'Settings',CONTACT:'Messages',PARTNER:'Partners',PROJECT:'Projects',USER:'Users',CLIENT:'Clients',SERVICE:'Services',PRODUCT:'Products',PRICING:'Pricing',BLOG:'Blogs',TESTIMONIAL:'Testimonials',BACKUP:'Backup'})[key]||'System'};
const statusOf=action=>String(action).includes('FAILED')?'Failed':'Success';
const serialize=row=>({id:row.id,createdAt:row.created_at,user:row.user_name||'System',email:row.email||'',action:title(row.action),actionCode:row.action,module:moduleOf(row.action),description:row.metadata?.description||title(row.action),detail:row.metadata?.detail||row.metadata?.targetName||'',ip:row.ip_address||'',status:statusOf(row.action),metadata:row.metadata||{}});
function filters(query){const values=[],clauses=[];const add=(sql,value)=>{values.push(value);clauses.push(sql.replace('?',`$${values.length}`))};if(query.search){values.push(`%${query.search}%`);clauses.push(`(l.action ILIKE $${values.length} OR COALESCE(u.name,'System') ILIKE $${values.length} OR COALESCE(u.email,'') ILIKE $${values.length} OR l.metadata::text ILIKE $${values.length})`)}if(query.user)add('l.user_id=?',query.user);if(query.action)add('l.action=?',query.action);if(query.module)add(`split_part(l.action,'_',1)=?`,query.module);if(query.status==='Failed')clauses.push(`l.action LIKE '%FAILED%'`);if(query.status==='Success')clauses.push(`l.action NOT LIKE '%FAILED%'`);if(query.ip)add('host(l.ip_address) ILIKE ?',`%${query.ip}%`);if(query.from)add('l.created_at>=?',query.from);if(query.to)add("l.created_at<?::date+interval '1 day'",query.to);return {where:clauses.length?`WHERE ${clauses.join(' AND ')}`:'',values}}
router.get('/',async(req,res)=>{const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(10,Number(req.query.limit)||20));const {where,values}=filters(req.query);const [data,count,stats,users,actions]=await Promise.all([pool.query(`SELECT l.*,u.name user_name,u.email FROM admin_audit_logs l LEFT JOIN users u ON u.id=l.user_id ${where} ORDER BY l.created_at DESC LIMIT $${values.length+1} OFFSET $${values.length+2}`,[...values,limit,(page-1)*limit]),pool.query(`SELECT count(*)::int total FROM admin_audit_logs l LEFT JOIN users u ON u.id=l.user_id ${where}`,values),pool.query(`SELECT count(*)::int total,count(DISTINCT user_id)::int users,count(*) FILTER(WHERE created_at::date=current_date)::int today,count(*) FILTER(WHERE action LIKE '%FAILED%' AND created_at>=now()-interval '7 days')::int failed FROM admin_audit_logs`),pool.query(`SELECT id,name,email FROM users ORDER BY name`),pool.query(`SELECT DISTINCT action FROM admin_audit_logs ORDER BY action`)]);res.set('Cache-Control','no-store').json({logs:data.rows.map(serialize),total:count.rows[0].total,page,limit,stats:stats.rows[0],users:users.rows,actions:actions.rows.map(x=>x.action)})});
router.get('/export',async(req,res)=>{const {where,values}=filters(req.query);const {rows}=await pool.query(`SELECT l.*,u.name user_name,u.email FROM admin_audit_logs l LEFT JOIN users u ON u.id=l.user_id ${where} ORDER BY l.created_at DESC LIMIT 10000`,values);const logs=rows.map(serialize);if(req.query.format==='json'){res.attachment(`activity-logs-${Date.now()}.json`).type('application/json').send(JSON.stringify(logs,null,2));return}const quote=value=>`"${String(value??'').replaceAll('"','""')}"`;const csv=[['Date','User','Email','Action','Module','Description','IP Address','Status'],...logs.map(x=>[x.createdAt,x.user,x.email,x.action,x.module,x.description,x.ip,x.status])].map(row=>row.map(quote).join(',')).join('\r\n');res.attachment(`activity-logs-${Date.now()}.csv`).type('text/csv').send(csv)});
export default router;
