import React, { useMemo, useState } from 'react';
import * as I from 'lucide-react';

const projectSeed=[
  {name:'EazyStore – eCommerce Platform',description:'Custom eCommerce solution',client:'TechSolutions Inc.',category:'Web Development',status:'In Progress',progress:65,start:'May 01, 2024',deadline:'Jun 15, 2024',team:['JS','ED','MB'],extra:2,tone:'blue'},
  {name:'Mikenium Analytics Dashboard',description:'Analytics dashboard for SAAS',client:'DataPro Systems',category:'UI/UX Design',status:'Completed',progress:100,start:'Apr 10, 2024',deadline:'May 05, 2024',team:['LJ','DT','SW'],extra:3,tone:'green'},
  {name:'TaskFlow – Project Management Tool',description:'Project management web app',client:'InnovateX',category:'Web Development',status:'In Progress',progress:40,start:'May 05, 2024',deadline:'Jun 20, 2024',team:['JW','SL','RA'],extra:1,tone:'orange'},
  {name:'HealthCare Plus – Mobile App',description:'Healthcare mobile application',client:'Medicare Group',category:'Mobile Development',status:'Completed',progress:100,start:'Mar 15, 2024',deadline:'Apr 30, 2024',team:['AB','SK','NH'],extra:2,tone:'purple'},
  {name:'CloudNova Website',description:'Corporate website development',client:'CloudNova',category:'Web Development',status:'On Hold',progress:25,start:'May 12, 2024',deadline:'Jun 30, 2024',team:['LM','DW'],extra:0,tone:'blue'},
  {name:'FinSoft – SaaS Platform',description:'SaaS platform for finance',client:'FinSoft Ltd.',category:'Web Development',status:'In Progress',progress:70,start:'Apr 20, 2024',deadline:'Jun 10, 2024',team:['MT','KA','OP'],extra:4,tone:'green'},
  {name:'ShopHub – Marketplace App',description:'Multi-vendor marketplace app',client:'MarketHub',category:'Mobile Development',status:'Cancelled',progress:0,start:'Apr 01, 2024',deadline:'May 01, 2024',team:['JT','SB','KL'],extra:0,tone:'orange'},
  {name:'EduLearn – E-learning Platform',description:'Online learning management system',client:'EduTech Solutions',category:'Web Development',status:'Completed',progress:100,start:'Feb 10, 2024',deadline:'Mar 30, 2024',team:['ED','ML','AR'],extra:1,tone:'purple'}
];

const projectStats=[['Total Projects','156','15.2%',I.Folder,'blue',true],['Completed','78','12.8%',I.SquareCheckBig,'green',true],['In Progress','48','8.4%',I.Clock3,'orange',true],['On Hold','12','3.1%',I.CirclePause,'purple',false],['Cancelled','18','2.6%',I.CircleOff,'pink',false]];

function ProjectModal({onClose,onSave}){const [form,setForm]=useState({name:'',description:'',client:'',category:'Web Development',deadline:''});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal project-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Project</h2><p>Create a project and assign its delivery details.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label className="wide">Project name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. Customer Portal"/></label><label className="wide">Description<input name="description" required value={form.description} onChange={change} placeholder="Short project description"/></label><label>Client<input name="client" required value={form.client} onChange={change} placeholder="Client company"/></label><label>Category<select name="category" value={form.category} onChange={change}><option>Web Development</option><option>Mobile Development</option><option>UI/UX Design</option></select></label><label className="wide">Deadline<input name="deadline" required type="date" value={form.deadline} onChange={change}/></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Project</button></div></form></div>}

export function ProjectsPage(){
  const [projects,setProjects]=useState(projectSeed),[query,setQuery]=useState(''),[client,setClient]=useState('All Clients'),[status,setStatus]=useState('All Status'),[category,setCategory]=useState('All Categories'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]);
  const filtered=useMemo(()=>projects.filter(p=>[p.name,p.description,p.client,p.category].join(' ').toLowerCase().includes(query.toLowerCase())&&(client==='All Clients'||p.client===client)&&(status==='All Status'||p.status===status)&&(category==='All Categories'||p.category===category)),[projects,query,client,status,category]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addProject=form=>{const deadline=form.deadline?new Date(`${form.deadline}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'}):'—';setProjects([{...form,deadline,status:'In Progress',progress:0,start:'Jul 14, 2026',team:['SA'],extra:0,tone:'blue'},...projects]);setModal(false);flash('Project added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(p=>selected.includes(p.name))?selected.filter(id=>!filtered.some(p=>p.name===id)):[...new Set([...selected,...filtered.map(p=>p.name)])]);
  const exportProjects=()=>{const header='Project,Description,Client,Category,Status,Progress,Start Date,Deadline';const rows=filtered.map(p=>[p.name,p.description,p.client,p.category,p.status,`${p.progress}%`,p.start,p.deadline].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-projects.csv';a.click();URL.revokeObjectURL(url);flash('Project list exported')};
  return <div className="users-page projects-page">
    <div className="users-heading"><div><h1>Projects</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Projects</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Project</button></div>
    <div className="user-stats">{projectStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up?'up':'down'}>{up?<I.ArrowUp/>:<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
    <div className="card users-table-card">
      <div className="users-toolbar"><div className="users-search project-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects..."/></div><select value={client} onChange={e=>setClient(e.target.value)}><option>All Clients</option>{[...new Set(projectSeed.map(p=>p.client))].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Completed</option><option>In Progress</option><option>On Hold</option><option>Cancelled</option></select><select value={category} onChange={e=>setCategory(e.target.value)}><option>All Categories</option><option>Web Development</option><option>Mobile Development</option><option>UI/UX Design</option></select><div className="toolbar-spacer"/><button className="date-button"><I.CalendarDays/> May 15, 2024 - May 21, 2024 <I.ChevronDown/></button><button><I.ListFilter/> Filter</button><button onClick={exportProjects}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table projects-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(p=>selected.includes(p.name))} onChange={toggleAll}/></th><th>#</th><th>Project Name</th><th>Client</th><th>Category</th><th>Status</th><th>Progress</th><th>Start Date <I.RotateCw/></th><th>Deadline <I.RotateCw/></th><th>Team</th><th>Actions</th></tr></thead><tbody>{filtered.map((p,index)=><tr key={p.name}><td><input type="checkbox" checked={selected.includes(p.name)} onChange={()=>toggle(p.name)}/></td><td>{index+1}</td><td><span className="project-name"><b>{p.name}</b><small>{p.description}</small></span></td><td><span className="project-client"><i className={p.tone}>{p.client[0]}</i>{p.client}</span></td><td><span className={`category-pill ${p.category.toLowerCase().replaceAll(/[^a-z]+/g,'-')}`}>{p.category}</span></td><td><span className={`project-status ${p.status.toLowerCase().replaceAll(' ','-')}`}>{p.status}</span></td><td><div className="project-progress"><span>{p.progress}%</span><i><b className={p.status==='Completed'?'done':''} style={{width:`${p.progress}%`}}/></i></div></td><td>{p.start}</td><td className={p.status==='Completed'?'deadline-done':'deadline-late'}>{p.deadline}</td><td><div className="project-team">{p.team.map((member,i)=><i className={`face face-${i}`} key={member}>{member}</i>)}{p.extra>0&&<span>+{p.extra}</span>}</div></td><td><button className="project-more" title="Project actions" onClick={()=>flash(`Actions for ${p.name}`)}><I.EllipsisVertical/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No projects found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer"><span>Showing 1 to {filtered.length} of 156 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>20</button><button aria-label="Next"><I.ChevronRight/></button></div></div>
    </div>
    {modal&&<ProjectModal onClose={()=>setModal(false)} onSave={addProject}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}
