import React,{useEffect,useMemo,useState} from 'react';
import * as I from 'lucide-react';
import { createProject,deleteProject,getClients,getProject,getProjects,updateProject,uploadProjectImage } from '../../../services/admin/admin-api';

const categories=['Web Development','Mobile Development','UI/UX Design','Cloud Solutions','E-commerce'];
const statusLabels={PLANNED:'Planned',IN_PROGRESS:'In Progress',ON_HOLD:'On Hold',COMPLETED:'Completed',CANCELLED:'Cancelled'};
const statusValues=Object.keys(statusLabels);
const dateInput=value=>value?String(value).slice(0,10):'';
const displayDate=value=>value?new Date(`${dateInput(value)}T00:00:00`).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'}):'—';
const adapt=project=>({...project,statusLabel:statusLabels[project.status]||project.status,start:displayDate(project.startDate),deadlineLabel:displayDate(project.deadline)});
const emptyForm={name:'',slug:'',description:'',clientId:'',category:'Web Development',status:'IN_PROGRESS',progress:0,startDate:new Date().toISOString().slice(0,10),deadline:'',result:'',tags:'React, Web',imageUrl:'',projectUrl:'',theme:'analytics',published:true,featured:false};

function ProjectModal({project,clients,onClose,onSave,saving}){
  const [form,setForm]=useState(project?{name:project.name,slug:project.slug||'',description:project.description,clientId:project.clientId||'',category:project.category,status:project.status,progress:project.progress,startDate:dateInput(project.startDate),deadline:dateInput(project.deadline),result:project.result||'',tags:(project.tags||[]).join(', '),imageUrl:project.imageUrl||'',projectUrl:project.projectUrl||'',theme:project.theme||'analytics',published:project.published,featured:project.featured}:emptyForm);
  const [uploading,setUploading]=useState(false);
  const [uploadError,setUploadError]=useState('');
  const change=event=>{const {name,value}=event.target;setForm(current=>({...current,[name]:name==='published'||name==='featured'?value==='true':value}))};
  const uploadImage=async event=>{const file=event.target.files?.[0];if(!file)return;setUploadError('');if(file.size>5*1024*1024){setUploadError('Project image must be 5 MB or smaller');event.target.value='';return}setUploading(true);try{const data=await uploadProjectImage(file);setForm(current=>({...current,imageUrl:data.imageUrl}))}catch(error){setUploadError(error.message)}finally{setUploading(false);event.target.value=''}};
  const editing=Boolean(project);
  const submit=event=>{event.preventDefault();onSave({...form,progress:Number(form.progress),tags:form.tags.split(',').map(tag=>tag.trim()).filter(Boolean)})};
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal project-modal project-crud-modal" onMouseDown={event=>event.stopPropagation()} onSubmit={submit}><div className="modal-head"><div><h2>{editing?'Edit Project':'Add New Project'}</h2><p>Delivery details and public portfolio visibility use the same database record.</p></div><button type="button" onClick={onClose}><I.X/></button></div><div className="client-form-grid">
    <label className="wide">Project name<input name="name" required autoFocus value={form.name} onChange={change}/></label><label className="wide">Slug (optional)<input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={form.slug} onChange={change} placeholder="generated-from-project-name"/></label>
    <label className="wide">Description<textarea name="description" required minLength="10" value={form.description} onChange={change}/></label>
    <label>Client<select name="clientId" value={form.clientId} onChange={change}><option value="">No client assigned</option>{clients.map(client=><option value={client.id} key={client.id}>{client.name}</option>)}</select></label><label>Category<select name="category" value={form.category} onChange={change}>{categories.map(value=><option key={value}>{value}</option>)}</select></label>
    <label>Status<select name="status" value={form.status} onChange={change}>{statusValues.map(value=><option value={value} key={value}>{statusLabels[value]}</option>)}</select></label><label>Progress<input name="progress" type="number" min="0" max="100" value={form.progress} onChange={change}/></label>
    <label>Start date<input name="startDate" type="date" value={form.startDate} onChange={change}/></label><label>Deadline<input name="deadline" type="date" value={form.deadline} onChange={change}/></label>
    <label className="wide">Public result<input name="result" value={form.result} onChange={change} placeholder="e.g. +42% faster operations"/></label><label className="wide">Public tags<input name="tags" value={form.tags} onChange={change} placeholder="React, SaaS, Automation"/></label>
    <label className="wide">Published project URL<input name="projectUrl" type="url" value={form.projectUrl} onChange={change} placeholder="https://your-live-project.com"/></label>
    <label className="wide project-image-upload">Project image<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={uploadImage} disabled={uploading}/><span className="project-upload-box">{form.imageUrl?<img src={form.imageUrl} alt="Project preview"/>:<I.ImagePlus/>}<b>{uploading?'Uploading image...':form.imageUrl?'Choose another image':'Click to upload project image'}</b><small>JPG, PNG, WebP or GIF · maximum 5 MB</small></span>{uploadError&&<em>{uploadError}</em>}</label>
    <label className="wide">External image URL (optional)<input name="imageUrl" type="url" value={form.imageUrl} onChange={change} placeholder="Uploaded image URL appears here"/></label>
    <label>Public website<select name="published" value={String(form.published)} onChange={change}><option value="true">Published</option><option value="false">Hidden</option></select></label><label>Featured<select name="featured" value={String(form.featured)} onChange={change}><option value="false">No</option><option value="true">Yes</option></select></label>
  </div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving||uploading}>{saving||uploading?<I.LoaderCircle className="spin"/>:editing?<I.Save/>:<I.Plus/>}{uploading?'Uploading...':saving?'Saving...':editing?'Save Changes':'Add Project'}</button></div></form></div>
}

function ProjectDetails({project,onClose,onEdit}){const fields=[['Project',project.name],['Client',project.client||'Unassigned'],['Category',project.category],['Status',statusLabels[project.status]],['Progress',`${project.progress}%`],['Start',displayDate(project.startDate)],['Deadline',displayDate(project.deadline)],['Public',project.published?'Published':'Hidden'],['Featured',project.featured?'Yes':'No'],['Result',project.result||'—'],['Tags',(project.tags||[]).join(', ')||'—']];return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal project-modal" onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><h2>Project Details</h2><p>{project.description}</p></div><button onClick={onClose}><I.X/></button></div><div className="user-detail-list">{fields.map(([label,value])=><p key={label}><span>{label}</span><b>{value}</b></p>)}</div><div className="modal-actions"><button onClick={onClose}>Close</button><button className="primary" onClick={()=>onEdit(project)}><I.Pencil/> Edit Project</button></div></div></div>}

export function ProjectsPage(){
  const [projects,setProjects]=useState([]),[clients,setClients]=useState([]),[stats,setStats]=useState({total:0,completed:0,in_progress:0,on_hold:0,cancelled:0,published:0}),[query,setQuery]=useState(''),[client,setClient]=useState('All Clients'),[status,setStatus]=useState('All Status'),[category,setCategory]=useState('All Categories'),[modal,setModal]=useState(null),[details,setDetails]=useState(null),[toast,setToast]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[selected,setSelected]=useState([]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const load=async()=>{setLoading(true);setError('');try{const [projectData,clientData]=await Promise.all([getProjects(),getClients()]);setProjects(projectData.projects.map(adapt));setStats(projectData.stats);setClients(clientData.clients)}catch(err){setError(err.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>projects.filter(project=>[project.name,project.description,project.client,project.category].join(' ').toLowerCase().includes(query.toLowerCase())&&(client==='All Clients'||project.client===client)&&(status==='All Status'||project.statusLabel===status)&&(category==='All Categories'||project.category===category)),[projects,query,client,status,category]);
  const statItems=[['Total Projects',stats.total,I.Folder,'blue'],['Completed',stats.completed,I.SquareCheckBig,'green'],['In Progress',stats.in_progress,I.Clock3,'orange'],['On Hold',stats.on_hold,I.CirclePause,'purple'],['Published',stats.published,I.Globe2,'pink']];
  const save=async form=>{setSaving(true);setError('');try{if(modal?.id)await updateProject(modal.id,form);else await createProject(form);setModal(null);flash(modal?.id?'Project updated successfully':form.published?'Project created and published successfully':'Project created successfully');await load()}catch(err){setError(err.message)}finally{setSaving(false)}};
  const view=async id=>{setError('');try{setDetails((await getProject(id)).project)}catch(err){setError(err.message)}};
  const remove=async project=>{if(!window.confirm(`Delete ${project.name}? It will also disappear from the public portfolio.`))return;setError('');try{await deleteProject(project.id);setSelected(current=>current.filter(id=>id!==project.id));flash('Project deleted successfully');await load()}catch(err){setError(err.message)}};
  const toggle=id=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(project=>selected.includes(project.id))?selected.filter(id=>!filtered.some(project=>project.id===id)):[...new Set([...selected,...filtered.map(project=>project.id)])]);
  const exportProjects=()=>{const header='Project,Client,Category,Status,Progress,Published,Start,Deadline';const rows=filtered.map(project=>[project.name,project.client,project.category,project.statusLabel,project.progress,project.published?'Yes':'No',project.start,project.deadlineLabel].map(value=>`"${String(value).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='mikenium-projects.csv';anchor.click();URL.revokeObjectURL(url);flash('Project list exported')};
  return <div className="users-page projects-page"><div className="users-heading"><div><h1>Projects</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Projects</span></div></div><button className="users-add" onClick={()=>setModal({})}><I.Plus/> Add New Project</button></div>
    <div className="user-stats">{statItems.map(([title,value,Icon,color])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{Number(value).toLocaleString()}</b><p>Live database total</p></div></div>)}</div>
    {error&&<div className="admin-inline-error"><I.CircleAlert/>{error}<button onClick={()=>setError('')}><I.X/></button></div>}
    <div className="card users-table-card"><div className="users-toolbar"><div className="users-search project-search"><I.Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search projects..."/></div><select value={client} onChange={event=>setClient(event.target.value)}><option>All Clients</option>{[...new Set(projects.map(project=>project.client).filter(Boolean))].map(value=><option key={value}>{value}</option>)}</select><select value={status} onChange={event=>setStatus(event.target.value)}><option>All Status</option>{Object.values(statusLabels).map(value=><option key={value}>{value}</option>)}</select><select value={category} onChange={event=>setCategory(event.target.value)}><option>All Categories</option>{categories.map(value=><option key={value}>{value}</option>)}</select><div className="toolbar-spacer"/><button onClick={load} disabled={loading}>{loading?<I.LoaderCircle className="spin"/>:<I.RefreshCw/>} Refresh</button><button onClick={exportProjects}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table projects-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(project=>selected.includes(project.id))} onChange={toggleAll}/></th><th>#</th><th>Project Name</th><th>Client</th><th>Category</th><th>Status</th><th>Progress</th><th>Start Date</th><th>Deadline</th><th>Public</th><th>Actions</th></tr></thead><tbody>{filtered.map((project,index)=><tr key={project.id}><td><input type="checkbox" checked={selected.includes(project.id)} onChange={()=>toggle(project.id)}/></td><td>{index+1}</td><td><span className="project-name"><b>{project.name}</b><small>{project.description}</small></span></td><td><span className="project-client"><i>{project.client?.[0]||'M'}</i>{project.client||'Unassigned'}</span></td><td><span className={`category-pill ${project.category.toLowerCase().replaceAll(/[^a-z]+/g,'-')}`}>{project.category}</span></td><td><span className={`project-status ${project.statusLabel.toLowerCase().replaceAll(' ','-')}`}>{project.statusLabel}</span></td><td><div className="project-progress"><span>{project.progress}%</span><i><b className={project.status==='COMPLETED'?'done':''} style={{width:`${project.progress}%`}}/></i></div></td><td>{project.start}</td><td>{project.deadlineLabel}</td><td><span className={`user-status ${project.published?'active':'inactive'}`}>{project.published?'Published':'Hidden'}</span></td><td><div className="user-actions"><button className="edit-user" onClick={()=>setModal(project)}><I.Pencil/><span>Edit</span></button><button onClick={()=>view(project.id)}><I.Eye/></button><button className="danger" onClick={()=>remove(project)}><I.Trash2/></button></div></td></tr>)}</tbody></table>{loading?<div className="empty"><I.LoaderCircle className="spin"/><b>Loading projects...</b></div>:!filtered.length&&<div className="empty"><I.SearchX/><b>No projects found</b><span>Add a project to publish it on the website.</span></div>}</div><div className="users-footer"><span>Showing {filtered.length} of {stats.total} database projects</span></div></div>
    {modal&&<ProjectModal project={modal.id?modal:null} clients={clients} onClose={()=>setModal(null)} onSave={save} saving={saving}/>} {details&&<ProjectDetails project={details} onClose={()=>setDetails(null)} onEdit={project=>{setDetails(null);setModal(adapt(project))}}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>;
}
