import React, { useMemo, useState } from 'react';
import * as I from 'lucide-react';

const messageSeed=[
  {id:1,sender:'John Smith',email:'john.smith@email.com',phone:'+1 (555) 123-4567',location:'New York, USA',subject:'Project Inquiry',preview:'Hello, I am interested in your web development...',status:'New',date:'May 21, 2024',time:'10:30 AM',channel:'Contact Form',ip:'192.168.1.100',tone:'blue',body:['Hello,','I am interested in your web development services for my new project.','Could you please provide more information about your process, timeline and estimated cost?','Looking forward to your response.','Thank you!','John Smith']},
  {id:2,sender:'Sarah Johnson',email:'sarah.johnson@email.com',phone:'+1 (555) 442-9182',location:'Austin, USA',subject:'General Question',preview:'Can you please provide more information about...',status:'New',date:'May 21, 2024',time:'09:15 AM',channel:'Email',ip:'192.168.1.114',tone:'purple',body:['Hello,','Can you please provide more information about your consulting services and availability?','Thank you,','Sarah Johnson']},
  {id:3,sender:'Michael Brown',email:'michael.brown@email.com',phone:'+44 20 7788 1092',location:'London, UK',subject:'Service Support',preview:'I need help with integration of the payment...',status:'Replied',date:'May 20, 2024',time:'04:45 PM',channel:'Contact Form',ip:'172.16.2.41',tone:'orange',body:['Hi Support,','I need help with integration of the payment service in our application.','Please let me know the next steps.','Michael']},
  {id:4,sender:'Emily Davis',email:'emily.davis@email.com',phone:'+1 (416) 555-2210',location:'Toronto, Canada',subject:'Partnership Opportunity',preview:'We are interested in partnership with your company...',status:'Replied',date:'May 20, 2024',time:'11:20 AM',channel:'Email',ip:'10.22.8.90',tone:'green',body:['Hello Mikenium,','We are interested in partnership with your company on an upcoming digital initiative.','I would love to arrange a call.','Emily Davis']},
  {id:5,sender:'David Wilson',email:'david.wilson@email.com',phone:'+61 2 8844 2091',location:'Sydney, Australia',subject:'Custom Development',preview:'Do you develop custom applications? We have...',status:'New',date:'May 19, 2024',time:'03:10 PM',channel:'Live Chat',ip:'192.168.4.20',tone:'red',body:['Hi,','Do you develop custom applications? We have a detailed scope ready for review.','Regards,','David Wilson']},
  {id:6,sender:'Laura Martinez',email:'laura.martinez@email.com',phone:'+49 30 2288 390',location:'Berlin, Germany',subject:'Pricing Information',preview:'Please share the pricing details for your services...',status:'Replied',date:'May 19, 2024',time:'10:05 AM',channel:'Contact Form',ip:'172.18.3.72',tone:'yellow',body:['Hello,','Please share the pricing details for your services and available engagement models.','Laura']},
  {id:7,sender:'James Taylor',email:'james.taylor@email.com',phone:'+1 (415) 555-7731',location:'San Francisco, USA',subject:'Career Inquiry',preview:'I would like to know about job opportunities...',status:'New',date:'May 18, 2024',time:'05:30 PM',channel:'Email',ip:'10.0.1.56',tone:'cyan',body:['Hello,','I would like to know about job opportunities currently available at Mikenium.','Best,','James Taylor']},
  {id:8,sender:'Olivia Anderson',email:'olivia.anderson@email.com',phone:'+81 90 4432 8100',location:'Tokyo, Japan',subject:'Website Feedback',preview:'Your website is amazing! Just wanted to provide...',status:'Replied',date:'May 18, 2024',time:'01:25 PM',channel:'Contact Form',ip:'192.168.8.33',tone:'purple',body:['Hi team,','Your website is amazing! Just wanted to provide some positive feedback on the design and experience.','Olivia Anderson']}
];

const messageStats=[['Total Messages','128','12.5%',I.Mail,'blue',true],['New Messages','18','20.0%',I.MessageSquare,'green',true],['Replied','92','8.3%',I.MailCheck,'orange',true],['Trash','6','14.3%',I.Trash2,'pink',false]];

export function ContactMessagesPage(){
  const [messages,setMessages]=useState(messageSeed),[activeId,setActiveId]=useState(1),[query,setQuery]=useState(''),[status,setStatus]=useState('All Status'),[channel,setChannel]=useState('All Channels'),[selected,setSelected]=useState([]),[reply,setReply]=useState(''),[tab,setTab]=useState('Reply'),[toast,setToast]=useState('');
  const filtered=useMemo(()=>messages.filter(m=>[m.sender,m.email,m.subject,m.preview].join(' ').toLowerCase().includes(query.toLowerCase())&&(status==='All Status'||m.status===status)&&(channel==='All Channels'||m.channel===channel)),[messages,query,status,channel]);
  const active=messages.find(m=>m.id===activeId)||messages[0];
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(m=>selected.includes(m.id))?selected.filter(id=>!filtered.some(m=>m.id===id)):[...new Set([...selected,...filtered.map(m=>m.id)])]);
  const markReplied=()=>{setMessages(messages.map(m=>m.id===active.id?{...m,status:'Replied'}:m));flash('Message marked as replied')};
  const remove=()=>{const remaining=messages.filter(m=>m.id!==active.id);setMessages(remaining);setActiveId(remaining[0]?.id);flash('Message moved to trash')};
  const sendReply=()=>{if(!reply.trim()){flash('Write a reply first');return}setMessages(messages.map(m=>m.id===active.id?{...m,status:'Replied'}:m));setReply('');flash(tab==='Reply'?'Reply sent successfully':'Internal note saved')};
  return <div className="users-page contact-messages-page">
    <div className="users-heading contact-heading"><div><h1>Contact Messages</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Contact Messages</span></div></div></div>
    <div className="contact-layout"><div className="contact-left"><div className="contact-stats">{messageStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up?'up':'down'}>{up?<I.ArrowUp/>:<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
      <div className="card contact-inbox"><div className="contact-toolbar"><div className="users-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search messages..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>New</option><option>Replied</option></select><select value={channel} onChange={e=>setChannel(e.target.value)}><option>All Channels</option><option>Contact Form</option><option>Email</option><option>Live Chat</option></select><div className="toolbar-spacer"/><button className="date-button"><I.CalendarDays/> May 15, 2024 - May 21, 2024 <I.ChevronDown/></button><button><I.ListFilter/> Filter</button></div>
        <div className="contact-table-wrap"><table className="users-table contact-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(m=>selected.includes(m.id))} onChange={toggleAll}/></th><th>Sender</th><th>Subject</th><th>Status</th><th>Received On <I.RotateCw/></th></tr></thead><tbody>{filtered.map(m=><tr key={m.id} className={m.id===activeId?'selected':''} onClick={()=>setActiveId(m.id)}><td><input type="checkbox" checked={selected.includes(m.id)} onClick={e=>e.stopPropagation()} onChange={()=>toggle(m.id)}/></td><td><div className="message-sender"><i className={m.tone}>{m.sender.split(' ').map(x=>x[0]).join('')}</i><span><b>{m.sender}</b><small>{m.email}</small></span></div></td><td><span className="message-subject"><b>{m.subject}</b><small>{m.preview}</small></span></td><td><span className={`message-status ${m.status.toLowerCase()}`}>{m.status}</span></td><td><span className="created-date">{m.date}<small>{m.time}</small></span></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No messages found</b><span>Try changing the search or filters.</span></div>}</div>
        <div className="users-footer"><span>Showing 1 to {filtered.length} of 128 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>16</button><button aria-label="Next"><I.ChevronRight/></button></div></div></div></div>
      {active&&<aside className="card message-detail"><div className="message-detail-head"><h2>{active.subject}</h2><span className={`message-status ${active.status.toLowerCase()}`}>{active.status}</span><div><button title="Mark replied" onClick={markReplied}><I.CircleCheck/></button><button title="Move to trash" onClick={remove}><I.Trash2/></button><button><I.EllipsisVertical/></button></div></div><div className="message-profile"><div className="message-person"><i className={active.tone}>{active.sender.split(' ').map(x=>x[0]).join('')}</i><span><b>{active.sender}</b><small>{active.email}</small><small>{active.phone}</small><small>{active.location}</small></span></div><dl><div><dt>Received On</dt><dd>{active.date} {active.time}</dd></div><div><dt>Channel</dt><dd>{active.channel}</dd></div><div><dt>IP Address</dt><dd>{active.ip}</dd></div></dl></div><div className="message-body">{active.body.map((p,i)=><p key={i}>{p}</p>)}</div><div className="previous-conversation"><h3>Previous Conversations (1) <I.ChevronDown/></h3><div><span className="mini-admin">SA</span><p><b>Super Admin</b><small>May 21, 2024 11:15 AM</small><em>Replied</em><span>Hello {active.sender.split(' ')[0]}, Thank you for reaching out to us. We’d be happy to help...</span></p></div></div><div className="reply-tabs"><button className={tab==='Reply'?'active':''} onClick={()=>setTab('Reply')}>Reply</button><button className={tab==='Internal Note'?'active':''} onClick={()=>setTab('Internal Note')}>Internal Note</button></div><div className="reply-editor"><div><I.Bold/><I.Italic/><I.Underline/><I.List/><I.ListOrdered/><I.Link/><I.Image/><I.SquarePlay/></div><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder={tab==='Reply'?'Type your reply...':'Add an internal note...'}/></div><div className="reply-actions"><button onClick={()=>flash('Attach file selected')}><I.Paperclip/> Attach File</button><button onClick={sendReply}><I.Send/> {tab==='Reply'?'Send Reply':'Save Note'} <I.ChevronDown/></button></div></aside>}
    </div>{toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}
