import React,{cloneElement,useEffect,useState} from 'react';
import {getPublicSettings} from '../services/public-api';
import {applyPublicSiteSettings} from '../config/site-contact';
import BrandLogo from '../components/BrandLogo';
import {resolveAssetUrl} from '../services/http';
function setMeta(name,content){let element=document.head.querySelector(`meta[name="${name}"]`);if(!element){element=document.createElement('meta');element.name=name;document.head.appendChild(element)}element.content=content||''}
function applyDocumentSettings(settings){const identity=settings.identity||{},seo=settings.seo||{},maintenance=settings.maintenance||{};if(seo.defaultTitle)document.title=seo.defaultTitle;setMeta('description',seo.description);setMeta('keywords',seo.keywords);setMeta('robots',seo.allowIndexing===false||maintenance.enabled?'noindex, nofollow':'index, follow');if(identity.primaryColor)document.documentElement.style.setProperty('--site-primary',identity.primaryColor);if(identity.faviconUrl){let link=document.head.querySelector('link[rel="icon"]');if(!link){link=document.createElement('link');link.rel='icon';document.head.appendChild(link)}link.href=resolveAssetUrl(identity.faviconUrl)}}
function applyPublicDom(settings){const others=settings.others||{},identity=settings.identity||{};document.querySelectorAll('[data-brand-logo] img').forEach(image=>{if(identity.logoAlt&&image.alt!==identity.logoAlt)image.alt=identity.logoAlt});document.querySelectorAll('footer .footer-about>p').forEach(element=>{if(others.footerDescription&&element.textContent!==others.footerDescription)element.textContent=others.footerDescription});document.querySelectorAll('footer .footer-bottom>p').forEach(element=>{if(others.copyright&&element.textContent!==others.copyright)element.textContent=others.copyright});const legalRoutes={'Privacy Policy':'/privacy-policy','Terms of Service':'/terms-of-service','Cookie Policy':'/cookie-policy'};document.querySelectorAll('footer .footer-bottom nav a').forEach(link=>{const route=legalRoutes[link.textContent];if(route&&link.getAttribute('href')!==route)link.setAttribute('href',route)});document.querySelectorAll('footer .footer-bottom>span').forEach(element=>{if(element.textContent!=='Service status')element.textContent='Service status';const hidden=others.showSystemStatus!==true;if(element.hidden!==hidden)element.hidden=hidden;const display=hidden?'none':'flex';if(element.style.display!==display)element.style.display=display})}
function Maintenance({settings}){const general=settings.general||{},maintenance=settings.maintenance||{};return <main className="site-maintenance"><BrandLogo alt={settings.identity?.logoAlt||general.siteName}/><span>PLANNED MAINTENANCE</span><h1>{maintenance.title}</h1><p>{maintenance.message}</p><a href={`mailto:${general.contactEmail}`}>{general.contactEmail}</a></main>}
export function SiteSettingsProvider({children}){const [state,setState]=useState({settings:null,version:0});useEffect(()=>{let mounted=true;getPublicSettings().then(settings=>{if(!mounted)return;applyPublicSiteSettings(settings);applyDocumentSettings(settings);setState({settings,version:1})}).catch(()=>{});return()=>{mounted=false}},[]);useEffect(()=>{const refresh=()=>applyPublicDom(state.settings||{others:{showSystemStatus:false}});requestAnimationFrame(refresh);const observer=new MutationObserver(refresh);observer.observe(document.getElementById('root'),{childList:true,subtree:true});return()=>observer.disconnect()},[state.settings]);if(state.settings?.maintenance?.enabled)return <Maintenance settings={state.settings}/>;return cloneElement(children,{key:`site-${state.version}`})}
