import React, { useMemo, useState } from 'react';
import * as I from 'lucide-react';

const blogSeed=[
  {title:'The Future of Web Development in 2024',slug:'/future-of-web-development-2024',author:'John Smith',category:'Technology',status:'Published',views:1245,date:'May 20, 2024',time:'10:30 AM',thumb:0,tone:'amber'},
  {title:'Top 10 Mobile App Design Trends',slug:'/top-10-mobile-app-design-trends',author:'Sarah Johnson',category:'Design',status:'Published',views:987,date:'May 18, 2024',time:'09:15 AM',thumb:1,tone:'rose'},
  {title:'How Digital Marketing Can Grow Your Business',slug:'/digital-marketing-can-grow-your-business',author:'Michael Brown',category:'Marketing',status:'Published',views:2156,date:'May 15, 2024',time:'02:45 PM',thumb:2,tone:'blue'},
  {title:'Understanding Cloud Computing Benefits',slug:'/understanding-cloud-computing-benefits',author:'Emily Davis',category:'Technology',status:'Draft',views:null,date:'—',time:'',thumb:3,tone:'rose'},
  {title:'Best Practices for Remote Team Management',slug:'/best-practices-for-remote-team-management',author:'David Wilson',category:'Business',status:'Scheduled',views:null,date:'May 25, 2024',time:'08:00 AM',thumb:4,tone:'amber'},
  {title:'E-commerce Security: Protecting Your Store',slug:'/ecommerce-security-protecting-your-store',author:'Laura Martinez',category:'E-commerce',status:'Published',views:1673,date:'May 12, 2024',time:'11:20 AM',thumb:5,tone:'rose'},
  {title:'AI in Business: Opportunities and Challenges',slug:'/ai-in-business-opportunities-challenges',author:'James Taylor',category:'Technology',status:'Draft',views:null,date:'—',time:'',thumb:6,tone:'blue'},
  {title:'SEO Tips to Rank Higher in Search Engines',slug:'/seo-tips-rank-higher-search-engines',author:'Olivia Anderson',category:'SEO',status:'Published',views:2834,date:'May 10, 2024',time:'04:10 PM',thumb:7,tone:'rose'}
];

const blogStats=[['Total Blogs','48','14.3%',I.NotebookText,'blue',true],['Published','36','16.7%',I.CircleCheckBig,'green',true],['Draft','8','11.1%',I.Pencil,'orange',false],['Scheduled','2','2.6%',I.CalendarDays,'purple',true],['Trash','2','0%',I.Trash2,'pink',true]];

function BlogModal({onClose,onSave}){const [form,setForm]=useState({title:'',slug:'',author:'John Smith',category:'Technology',status:'Draft'});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal blog-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Blog</h2><p>Create a post and configure its publishing state.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label className="wide">Blog title<input name="title" required autoFocus value={form.title} onChange={change} placeholder="Article title"/></label><label className="wide">Slug<input name="slug" required value={form.slug} onChange={change} placeholder="/article-slug"/></label><label>Author<select name="author" value={form.author} onChange={change}>{[...new Set(blogSeed.map(b=>b.author))].map(x=><option key={x}>{x}</option>)}</select></label><label>Category<select name="category" value={form.category} onChange={change}>{[...new Set(blogSeed.map(b=>b.category))].map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Status<select name="status" value={form.status} onChange={change}><option>Draft</option><option>Published</option><option>Scheduled</option></select></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Blog</button></div></form></div>}

export function BlogsAdminPage(){
  const [blogs,setBlogs]=useState(blogSeed),[query,setQuery]=useState(''),[category,setCategory]=useState('All Categories'),[author,setAuthor]=useState('All Authors'),[status,setStatus]=useState('All Status'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]);
  const filtered=useMemo(()=>blogs.filter(b=>[b.title,b.slug,b.author,b.category].join(' ').toLowerCase().includes(query.toLowerCase())&&(category==='All Categories'||b.category===category)&&(author==='All Authors'||b.author===author)&&(status==='All Status'||b.status===status)),[blogs,query,category,author,status]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addBlog=form=>{setBlogs([{...form,views:null,date:form.status==='Published'?'Jul 14, 2026':'—',time:form.status==='Published'?'Just now':'',thumb:0,tone:'blue'},...blogs]);setModal(false);flash('Blog added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(b=>selected.includes(b.slug))?selected.filter(id=>!filtered.some(b=>b.slug===id)):[...new Set([...selected,...filtered.map(b=>b.slug)])]);
  const exportBlogs=()=>{const header='Title,Slug,Author,Category,Status,Views,Published On';const rows=filtered.map(b=>[b.title,b.slug,b.author,b.category,b.status,b.views??'',`${b.date} ${b.time}`].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-blogs.csv';a.click();URL.revokeObjectURL(url);flash('Blog list exported')};
  return <div className="users-page blogs-admin-page">
    <div className="users-heading"><div><h1>Blogs</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Blogs</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Blog</button></div>
    <div className="user-stats">{blogStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up?'up':'down'}>{up?<I.ArrowUp/>:<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
    <div className="card users-table-card"><div className="users-toolbar"><div className="users-search blog-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search blogs..."/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option>All Categories</option>{[...new Set(blogSeed.map(b=>b.category))].map(x=><option key={x}>{x}</option>)}</select><select value={author} onChange={e=>setAuthor(e.target.value)}><option>All Authors</option>{[...new Set(blogSeed.map(b=>b.author))].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Published</option><option>Draft</option><option>Scheduled</option></select><div className="toolbar-spacer"/><button className="date-button"><I.CalendarDays/> May 15, 2024 - May 21, 2024 <I.ChevronDown/></button><button><I.ListFilter/> Filter</button><button onClick={exportBlogs}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table blogs-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(b=>selected.includes(b.slug))} onChange={toggleAll}/></th><th>Blog</th><th>Author</th><th>Category</th><th>Status</th><th>Views</th><th>Published On <I.RotateCw/></th><th>Actions</th></tr></thead><tbody>{filtered.map(b=><tr key={b.slug}><td><input type="checkbox" checked={selected.includes(b.slug)} onChange={()=>toggle(b.slug)}/></td><td><div className="blog-identity"><span className={`blog-thumb thumb-${b.thumb}`}/><span><b>{b.title}</b><small>{b.slug}</small></span></div></td><td><span className="blog-author"><i className={b.tone}>{b.author.split(' ').map(x=>x[0]).join('')}</i>{b.author}</span></td><td><span className={`blog-category ${b.category.toLowerCase().replaceAll(/[^a-z]+/g,'-')}`}>{b.category}</span></td><td><span className={`blog-status ${b.status.toLowerCase()}`}>{b.status}</span></td><td><span className="blog-views">{b.views?<><I.Eye/>{b.views.toLocaleString()}</>:'—'}</span></td><td><span className="created-date">{b.date}<small>{b.time}</small></span></td><td><div className="user-actions">{b.status!=='Draft'&&<button title="View blog" onClick={()=>flash(`Viewing ${b.title}`)}><I.Eye/></button>}<button title="Edit blog" onClick={()=>flash(`Editing ${b.title}`)}><I.Pencil/></button><button className="more"><I.EllipsisVertical/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No blogs found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer"><span>Showing 1 to {filtered.length} of 48 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>6</button><button aria-label="Next"><I.ChevronRight/></button></div></div>
    </div>{modal&&<BlogModal onClose={()=>setModal(false)} onSave={addBlog}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}
