import React,{useEffect,useMemo,useState} from 'react';
import * as I from 'lucide-react';
import {createBlog,deleteBlog,getBlogs,updateBlog,uploadBlogImage} from '../../../services/admin/admin-api';

const labels={PUBLISHED:'Published',DRAFT:'Draft',SCHEDULED:'Scheduled',ARCHIVED:'Archived'};
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const make={
  heading:()=>({id:uid(),type:'heading',eyebrow:'SECTION',title:'Section heading'}),
  paragraph:()=>({id:uid(),type:'paragraph',text:'Write the article paragraph here.',lead:false}),
  quote:()=>({id:uid(),type:'quote',text:'Add a memorable quote or key principle.',cite:'Mikenium'}),
  list:()=>({id:uid(),type:'list',title:'Key takeaways',items:['First practical point','Second practical point']}),
  image:()=>({id:uid(),type:'image',url:'',alt:'',caption:''}),
  featureGrid:()=>({id:uid(),type:'featureGrid',title:'What matters most',items:[{title:'Clear strategy',text:'Explain why this matters.'},{title:'Strong execution',text:'Add another useful insight.'}]}),
  callout:()=>({id:uid(),type:'callout',eyebrow:'HAVE A PRODUCT IDEA?',title:'Let’s build something useful.',text:'Turn this insight into a clear next step.',buttonLabel:'Start a project',buttonUrl:'/contact'})
};
const blank={title:'',slug:'',excerpt:'',category:'Engineering',authorName:'Mikenium Team',authorTitle:'Product & Engineering',authorBio:'Building useful digital products through strategy, design, and engineering.',authorAvatarUrl:'',coverImageUrl:'',coverCaption:'MIKENIUM / JOURNAL',readingMinutes:6,tags:'',seoTitle:'',seoDescription:'',featured:false,status:'DRAFT',scheduledAt:'',blocks:[make.paragraph(),make.heading(),make.paragraph()]};
const initials=name=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const date=value=>value?new Date(value).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'2-digit'}):'—';

function ContentBlock({block,index,change,move,remove,upload,uploading}){
  const set=(key,value)=>change({...block,[key]:value});
  return <div className="blog-block-editor"><div className="blog-block-head"><span>{String(index+1).padStart(2,'0')} · {block.type}</span><div><button type="button" onClick={()=>move(-1)}><I.ArrowUp/></button><button type="button" onClick={()=>move(1)}><I.ArrowDown/></button><button type="button" className="danger" onClick={remove}><I.Trash2/></button></div></div>
    {block.type==='heading'&&<div className="client-form-grid"><label>Eyebrow<input value={block.eyebrow} onChange={e=>set('eyebrow',e.target.value)}/></label><label className="wide">Heading<input required value={block.title} onChange={e=>set('title',e.target.value)}/></label></div>}
    {block.type==='paragraph'&&<><label className="blog-check"><input type="checkbox" checked={block.lead} onChange={e=>set('lead',e.target.checked)}/> Large introductory paragraph</label><label>Paragraph<textarea required value={block.text} onChange={e=>set('text',e.target.value)}/></label></>}
    {block.type==='quote'&&<div className="client-form-grid"><label className="wide">Quote<textarea required value={block.text} onChange={e=>set('text',e.target.value)}/></label><label className="wide">Citation<input value={block.cite} onChange={e=>set('cite',e.target.value)}/></label></div>}
    {block.type==='list'&&<div className="client-form-grid"><label className="wide">List heading<input value={block.title} onChange={e=>set('title',e.target.value)}/></label><label className="wide">Items — one per line<textarea required value={block.items.join('\n')} onChange={e=>set('items',e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))}/></label></div>}
    {block.type==='image'&&<div className="client-form-grid"><label className="wide">Image URL<input value={block.url} onChange={e=>set('url',e.target.value)}/></label><label className="wide blog-upload">Upload article image<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>e.target.files[0]&&upload(e.target.files[0])}/><small>{uploading?'Uploading...':'JPG, PNG, WebP or GIF · max 5 MB'}</small></label><label>Alt text<input value={block.alt} onChange={e=>set('alt',e.target.value)}/></label><label>Caption<input value={block.caption} onChange={e=>set('caption',e.target.value)}/></label>{block.url&&<img className="blog-editor-image" src={block.url} alt=""/>}</div>}
    {block.type==='featureGrid'&&<div className="client-form-grid"><label className="wide">Grid heading<input value={block.title} onChange={e=>set('title',e.target.value)}/></label><label className="wide">Cards — Title | Description, one per line<textarea required value={block.items.map(x=>`${x.title} | ${x.text}`).join('\n')} onChange={e=>set('items',e.target.value.split('\n').filter(Boolean).map(line=>{const [title,...rest]=line.split('|');return{title:title.trim(),text:rest.join('|').trim()}}))}/></label></div>}
    {block.type==='callout'&&<div className="client-form-grid"><label>Eyebrow<input value={block.eyebrow} onChange={e=>set('eyebrow',e.target.value)}/></label><label>Title<input required value={block.title} onChange={e=>set('title',e.target.value)}/></label><label className="wide">Text<textarea value={block.text} onChange={e=>set('text',e.target.value)}/></label><label>Button label<input value={block.buttonLabel} onChange={e=>set('buttonLabel',e.target.value)}/></label><label>Button URL<input value={block.buttonUrl} onChange={e=>set('buttonUrl',e.target.value)}/></label></div>}
  </div>;
}

function Editor({blog,onClose,onSave,saving,error}){
  const [form,setForm]=useState(blog?{...blog,tags:blog.tags.join(', '),scheduledAt:blog.scheduledAt?new Date(blog.scheduledAt).toISOString().slice(0,16):''}:blank);
  const [uploading,setUploading]=useState('');
  const [localError,setLocalError]=useState('');
  const change=e=>{const{name,value,type,checked}=e.target;setForm(f=>({...f,[name]:type==='checkbox'?checked:value}))};
  const upload=async(file,target,index)=>{setUploading(`${target}-${index??''}`);try{const{imageUrl}=await uploadBlogImage(file);setForm(f=>target==='cover'?{...f,coverImageUrl:imageUrl}:{...f,blocks:f.blocks.map((b,i)=>i===index?{...b,url:imageUrl}:b)})}finally{setUploading('')}};
  const update=(index,value)=>setForm(f=>({...f,blocks:f.blocks.map((b,i)=>i===index?value:b)}));
  const move=(index,direction)=>setForm(f=>{const blocks=[...f.blocks],to=index+direction;if(to<0||to>=blocks.length)return f;[blocks[index],blocks[to]]=[blocks[to],blocks[index]];return{...f,blocks}});
  const submit=async e=>{e.preventDefault();setLocalError('');try{await onSave({...form,slug:form.slug.trim().replace(/^\/+|\/+$/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),readingMinutes:Number(form.readingMinutes),tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean),scheduledAt:form.status==='SCHEDULED'&&form.scheduledAt?new Date(form.scheduledAt).toISOString():''})}catch(saveError){setLocalError(saveError.message)}};
  const visibleError=localError||error;
  return <div className="modal-backdrop blog-editor-backdrop"><form className="modal blog-editor-modal" onSubmit={submit}><div className="modal-head"><div><h2>{blog?'Edit Blog Article':'Create Blog Article'}</h2><p>Build the structured layout used by the public single-blog page.</p></div><button type="button" onClick={onClose}><I.X/></button></div>{visibleError&&<div className="blog-editor-error"><I.CircleAlert/><span><b>Unable to save this article</b>{visibleError}</span></div>}<div className="blog-editor-scroll">
    <section className="blog-editor-section"><h3><I.FileText/> Article details</h3><div className="client-form-grid"><label className="wide">Article title<input required autoFocus name="title" value={form.title} onChange={change}/></label><label>Slug<input name="slug" value={form.slug} onChange={change} placeholder="generated-from-title"/></label><label>Category<input required name="category" value={form.category} onChange={change}/></label><label className="wide">Hero excerpt<textarea required minLength="20" name="excerpt" value={form.excerpt} onChange={change}/></label><label>Reading time<input type="number" min="1" max="120" name="readingMinutes" value={form.readingMinutes} onChange={change}/></label><label>Tags<input name="tags" value={form.tags} onChange={change}/></label></div></section>
    <section className="blog-editor-section"><h3><I.Image/> Cover and author</h3><div className="client-form-grid"><label className="wide">Cover image URL<input name="coverImageUrl" value={form.coverImageUrl} onChange={change}/></label><label className="wide blog-upload">Upload cover image<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>e.target.files[0]&&upload(e.target.files[0],'cover')}/><small>{uploading==='cover-'?'Uploading...':'Recommended wide image · max 5 MB'}</small></label>{form.coverImageUrl&&<img className="blog-cover-preview" src={form.coverImageUrl} alt="Cover preview"/>}<label className="wide">Cover caption<input name="coverCaption" value={form.coverCaption} onChange={change}/></label><label>Author name<input required name="authorName" value={form.authorName} onChange={change}/></label><label>Author title<input name="authorTitle" value={form.authorTitle} onChange={change}/></label><label className="wide">Author bio<textarea name="authorBio" value={form.authorBio} onChange={change}/></label><label className="wide">Author avatar URL<input name="authorAvatarUrl" value={form.authorAvatarUrl} onChange={change}/></label></div></section>
    <section className="blog-editor-section"><div className="blog-section-title"><h3><I.LayoutTemplate/> Article layout</h3><span>Add and arrange blocks in reading order.</span></div><div className="blog-block-toolbar">{Object.keys(make).map(type=><button type="button" onClick={()=>setForm(f=>({...f,blocks:[...f.blocks,make[type]()] }))} key={type}><I.Plus/>{type.replace(/([A-Z])/g,' $1')}</button>)}</div><div className="blog-blocks">{form.blocks.map((block,index)=><ContentBlock key={block.id} block={block} index={index} change={value=>update(index,value)} move={direction=>move(index,direction)} remove={()=>setForm(f=>({...f,blocks:f.blocks.filter((_,i)=>i!==index)}))} upload={file=>upload(file,'block',index)} uploading={uploading===`block-${index}`}/>)}</div></section>
    <section className="blog-editor-section"><h3><I.SearchCheck/> SEO and publishing</h3><div className="client-form-grid"><label className="wide">SEO title<input name="seoTitle" value={form.seoTitle} onChange={change} placeholder="Defaults to article title"/></label><label className="wide">SEO description<textarea name="seoDescription" value={form.seoDescription} onChange={change}/></label><label>Status<select name="status" value={form.status} onChange={change}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>{form.status==='SCHEDULED'&&<label>Schedule date<input required type="datetime-local" name="scheduledAt" value={form.scheduledAt} onChange={change}/></label>}<label className="blog-check"><input type="checkbox" name="featured" checked={form.featured} onChange={change}/> Feature on public blog page</label></div></section>
  </div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving||uploading||!form.blocks.length}>{saving?<I.LoaderCircle className="spin"/>:<I.Save/>}{saving?'Saving...':'Save article'}</button></div></form></div>;
}

export function BlogsAdminPage(){
  const [blogs,setBlogs]=useState([]),[stats,setStats]=useState({}),[query,setQuery]=useState(''),[status,setStatus]=useState('All Status'),[category,setCategory]=useState('All Categories'),[modal,setModal]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const data=await getBlogs();setBlogs(data.blogs);setStats(data.stats)}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
  const categories=[...new Set(blogs.map(x=>x.category))];
  const filtered=useMemo(()=>blogs.filter(x=>`${x.title} ${x.slug} ${x.authorName} ${x.category}`.toLowerCase().includes(query.toLowerCase())&&(status==='All Status'||x.status===status)&&(category==='All Categories'||x.category===category)),[blogs,query,status,category]);
  const flash=text=>{setToast(text);setTimeout(()=>setToast(''),2500)};
  const save=async form=>{setSaving(true);setError('');try{modal?.id?await updateBlog(modal.id,form):await createBlog(form);setModal(null);await load();flash('Blog article saved')}catch(e){setError(e.message);throw e}finally{setSaving(false)}};
  const remove=async blog=>{if(!confirm(`Delete "${blog.title}"?`))return;try{await deleteBlog(blog.id);await load();flash('Blog deleted')}catch(e){setError(e.message)}};
  const cards=[['Total Blogs',stats.total,I.NotebookText,'blue'],['Published',stats.published,I.CircleCheckBig,'green'],['Draft',stats.draft,I.Pencil,'orange'],['Scheduled',stats.scheduled,I.CalendarDays,'purple'],['Archived',stats.archived,I.Archive,'pink']];
  return <div className="users-page blogs-admin-page"><div className="users-heading"><div><h1>Blogs</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Blogs</span></div></div><button className="users-add" onClick={()=>setModal({})}><I.Plus/> Add New Blog</button></div><div className="user-stats">{cards.map(([title,value,Icon,color])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{Number(value||0).toLocaleString()}</b><p>Live database total</p></div></div>)}</div>
    {error&&<div className="admin-inline-error"><I.CircleAlert/>{error}<button onClick={()=>setError('')}><I.X/></button></div>}<div className="card users-table-card"><div className="users-toolbar"><div className="users-search blog-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search blogs..."/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option>All Categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><div className="toolbar-spacer"/><button onClick={load}><I.RefreshCw/> Refresh</button></div><div className="users-table-wrap"><table className="users-table blogs-table"><thead><tr><th>Blog</th><th>Author</th><th>Category</th><th>Status</th><th>Views</th><th>Published</th><th>Actions</th></tr></thead><tbody>{filtered.map(blog=><tr key={blog.id}><td><div className="blog-identity">{blog.coverImageUrl?<img className="blog-thumb" src={blog.coverImageUrl} alt=""/>:<span className="blog-thumb"/>}<span><b>{blog.title}</b><small>/blog/{blog.slug}</small></span></div></td><td><span className="blog-author"><i className="blue">{initials(blog.authorName)}</i>{blog.authorName}</span></td><td><span className="blog-category technology">{blog.category}</span></td><td><span className={`blog-status ${blog.status.toLowerCase()}`}>{labels[blog.status]}</span></td><td><span className="blog-views"><I.Eye/>{blog.views.toLocaleString()}</span></td><td>{date(blog.publishedAt||blog.scheduledAt)}</td><td><div className="user-actions">{blog.status==='PUBLISHED'&&<a className="admin-icon-link" href={`/blog/${blog.slug}`} target="_blank" rel="noreferrer"><I.Eye/></a>}<button onClick={()=>setModal(blog)}><I.Pencil/></button><button className="danger" onClick={()=>remove(blog)}><I.Trash2/></button></div></td></tr>)}</tbody></table>{loading?<div className="empty"><I.LoaderCircle className="spin"/><b>Loading blogs...</b></div>:!filtered.length&&<div className="empty"><I.SearchX/><b>No blogs found</b><span>Create your first structured article.</span></div>}</div><div className="users-footer"><span>Showing {filtered.length} of {Number(stats.total||0)} database blogs</span></div></div>{modal&&<Editor blog={modal.id?modal:null} onClose={()=>setModal(null)} onSave={save} saving={saving}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}</div>;
}
