import React,{useEffect,useRef,useState} from 'react';
import * as I from 'lucide-react';
import {Heading,Toast} from '../shared/SystemShared';
import {getSiteSettings,updateSiteSettings,uploadSiteIdentityImage} from '../../../services/admin/admin-api';

const tabs=[['general',I.Settings,'General'],['identity',I.Link,'Site Identity'],['email',I.Mail,'Email'],['seo',I.PanelTop,'SEO'],['social',I.Share2,'Social Links'],['maintenance',I.Wrench,'Maintenance'],['security',I.ShieldCheck,'Security'],['others',I.Combine,'Others']];
const fields={
 general:[['siteName','Site Name','The business name shown across the website.'],['tagline','Site Tagline','Short branding line for public pages.'],['contactEmail','Public Email','Used in public contact sections.','email'],['phonePrimary','Primary Phone','Main public telephone number.'],['phoneSecondary','Secondary Phone','Optional second public telephone number.'],['address','Business Address','Displayed on contact and footer sections.'],['language','Site Language','Default website language.','select',['English','Sinhala','Tamil']],['timezone','Timezone','Timezone used for website dates.','select',['Asia/Colombo','UTC']],['itemsPerPage','Items Per Page','Default admin list size.','number']],
 identity:[['logoUrl','Logo URL','Public logo path or full URL.'],['faviconUrl','Favicon URL','Browser tab icon path or full URL.'],['logoAlt','Logo Alternative Text','Accessible description of the logo.'],['primaryColor','Primary Brand Colour','Six-digit hex colour.','color']],
 email:[['senderName','Sender Name','Name used by website notification emails.'],['replyTo','Reply-to Email','Replies to automated messages go here.','email'],['notificationEmail','Notification Email','New enquiries are sent to this address.','email'],['notifyContact','Contact Notifications','Email the team for new contact enquiries.','checkbox'],['notifyNewsletter','Newsletter Notifications','Enable newsletter-related notifications.','checkbox']],
 seo:[['defaultTitle','Default Page Title','Fallback browser and search result title.'],['titleSuffix','Title Suffix','Text appended to page-specific titles.'],['description','Meta Description','Default search result description.','textarea'],['keywords','Keywords','Comma-separated search keywords.','textarea'],['ogImageUrl','Social Share Image','Full URL or local path for link previews.'],['allowIndexing','Search Indexing','Allow search engines to index public pages.','checkbox']],
 social:[['facebook','Facebook URL','Public Facebook profile.'],['instagram','Instagram URL','Public Instagram profile.'],['linkedin','LinkedIn URL','Public LinkedIn profile.'],['tiktok','TikTok URL','Public TikTok profile.'],['youtube','YouTube URL','Public YouTube channel.']],
 maintenance:[['enabled','Maintenance Mode','Replace public pages with a maintenance notice.','checkbox'],['title','Notice Title','Heading shown while maintenance mode is enabled.'],['message','Notice Message','Public explanation shown to visitors.','textarea']],
 security:[['sessionMinutes','Admin Session Duration','Session lifetime in minutes.','number'],['maxLoginAttempts','Maximum Login Attempts','Number of failed attempts allowed.','number'],['auditLogging','Audit Logging','Record administrative settings changes.','checkbox']],
 others:[['copyright','Copyright Text','Displayed in every public footer.'],['footerDescription','Footer Description','Company summary displayed in the footer.','textarea'],['businessHours','Business Hours','Displayed with public contact information.'],['mapsUrl','Map Link','Destination for the public address link.'],['showSystemStatus','System Status','Show the operational status in the footer.','checkbox']]
};

function Field({definition,value,onChange}){const [name,label,help,type='text',options]=definition;const control=type==='select'?<select name={name} value={value??''} onChange={onChange}>{options.map(x=><option key={x}>{x}</option>)}</select>:type==='textarea'?<textarea name={name} value={value??''} onChange={onChange}/>:type==='checkbox'?<span className="settings-switch"><input name={name} type="checkbox" checked={Boolean(value)} onChange={onChange}/><i/><em>{value?'Enabled':'Disabled'}</em></span>:<input name={name} type={type} value={value??''} onChange={onChange}/>;return <label className="setting-row"><span><b>{label}</b><small>{help}</small></span>{control}</label>}

export function SettingsAdminPage(){
 const [tab,setTab]=useState('general'),[settings,setSettings]=useState(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);const logoRef=useRef(),faviconRef=useRef();
 const flash=text=>{setNotice(text);setTimeout(()=>setNotice(''),2400)};
 useEffect(()=>{getSiteSettings().then(data=>setSettings(data.settings)).catch(e=>setError(e.message))},[]);
 const change=e=>setSettings(current=>({...current,[tab]:{...current[tab],[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value}}));
 async function save(e){e.preventDefault();setSaving(true);setError('');try{const result=await updateSiteSettings(tab,settings[tab]);setSettings(current=>({...current,[tab]:result.section,updated_at:result.updatedAt}));flash(`${tabs.find(x=>x[0]===tab)[2]} settings saved`)}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function upload(file,key){if(!file)return;setSaving(true);setError('');try{const {url}=await uploadSiteIdentityImage(file);const identity={...settings.identity,[key]:url};const result=await updateSiteSettings('identity',identity);setSettings(current=>({...current,identity:result.section}));flash(`${key==='logoUrl'?'Logo':'Favicon'} uploaded`)}catch(e){setError(e.message)}finally{setSaving(false)}}
 if(!settings)return <div className="users-page settings-admin"><Heading title="Settings"/><div className="card settings-loading">{error?<><I.CircleAlert/>{error}</>:<><I.LoaderCircle className="spin"/>Loading database settings…</>}</div></div>;
 const label=tabs.find(x=>x[0]===tab)[2];
 return <div className="users-page settings-admin"><Heading title="Settings"/><div className="card settings-nav">{tabs.map(([key,Icon,name])=><button type="button" className={tab===key?'active':''} onClick={()=>setTab(key)} key={key}><Icon/>{name}</button>)}</div>{error&&<div className="settings-error"><I.CircleAlert/>{error}</div>}<div className="settings-main"><form className="card settings-general" onSubmit={save}><header><h2>{label} Settings</h2><p>Manage {label.toLowerCase()} configuration. Public-safe changes are reflected on the website.</p></header><div className="setting-rows">{fields[tab].map(def=><Field key={def[0]} definition={def} value={settings[tab]?.[def[0]]} onChange={change}/>)}</div><button className="save-settings" disabled={saving}>{saving?<I.LoaderCircle className="spin"/>:<I.Save/>}{saving?'Saving…':'Save Changes'}</button></form><aside className="settings-side">{tab==='identity'&&<><section className="card logo-card"><h3>Site Logo</h3><p>PNG, JPG, or WebP. Maximum 3 MB.</p><button type="button" onClick={()=>logoRef.current.click()}><img src={settings.identity.logoUrl||'/assets/mikenium-logo-transparent.png'} alt="Current logo"/><b>Choose a new logo</b></button><input ref={logoRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files[0],'logoUrl')}/></section><section className="card favicon-card"><h3>Site Favicon</h3><p>PNG, JPG, WebP, or ICO. Maximum 3 MB.</p><div><span><img src={settings.identity.faviconUrl||'/assets/mikenium-logo-transparent.png'} alt="Current favicon"/></span><button type="button" onClick={()=>faviconRef.current.click()}>Change</button></div><input ref={faviconRef} hidden type="file" accept="image/png,image/jpeg,image/webp,image/x-icon" onChange={e=>upload(e.target.files[0],'faviconUrl')}/></section></>}<section className="card settings-summary"><h3>Where changes appear</h3><p>{tab==='security'?'Security controls remain private to the admin system.':tab==='email'?'Notification preferences are server-only; public email comes from General settings.':'Supported fields update public branding, metadata, contact areas, social links, footer, and maintenance notice.'}</p><div><I.Database/> Stored in PostgreSQL</div><div><I.Globe2/> Public API connected</div><div><I.ShieldCheck/> Private fields protected</div></section></aside></div><footer className="settings-footer">Mikenium settings <span>{settings.updated_at?`Last updated ${new Date(settings.updated_at).toLocaleString()}`:'Database connected'}</span></footer><Toast text={notice}/></div>
}
