import React,{useEffect,useMemo,useState} from 'react';
import * as I from 'lucide-react';
import { createClient,deleteClient,getClient,getClients,updateClient } from '../../../services/admin/admin-api';

const industries=['Technology','Healthcare','E-commerce','Education','Finance','Design','Retail','Wellness','Automotive'];
const tones=['blue','green','purple','orange','cyan','pink','brown'];
const displayDate=value=>value?new Date(value).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'}):'—';
const adapt=(client,index=0)=>({...client,statusLabel:client.status==='ACTIVE'?'Active':'Inactive',joined:displayDate(client.createdAt),tone:tones[index%tones.length]});
const emptyForm={name:'',location:'',contact:'',title:'',email:'',phone:'',industry:'Technology',status:'ACTIVE',revenue:0};

function ClientModal({client,onClose,onSave,saving}){const [form,setForm]=useState(client?{name:client.name,location:client.location,contact:client.contact,title:client.title,email:client.email,phone:client.phone,industry:client.industry,status:client.status,revenue:client.revenue}:emptyForm);const change=event=>setForm(current=>({...current,[event.target.name]:event.target.value}));const editing=Boolean(client);return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal client-modal" onMouseDown={event=>event.stopPropagation()} onSubmit={event=>{event.preventDefault();onSave({...form,revenue:Number(form.revenue)})}}><div className="modal-head"><div><h2>{editing?'Edit Client':'Add New Client'}</h2><p>{editing?'Update the organization and primary contact.':'Add a database-backed client organization.'}</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid">
  <label>Company name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. Acme Inc."/></label><label>Location<input name="location" required value={form.location} onChange={change} placeholder="City, Country"/></label>
  <label>Contact person<input name="contact" required value={form.contact} onChange={change} placeholder="Full name"/></label><label>Job title<input name="title" value={form.title} onChange={change} placeholder="e.g. CEO"/></label>
  <label className="wide">Email address<input name="email" required type="email" value={form.email} onChange={change} placeholder="contact@company.com"/></label><label>Phone number<input name="phone" value={form.phone} onChange={change} placeholder="+94 11 234 5678"/></label>
  <label>Industry<select name="industry" value={form.industry} onChange={change}>{industries.map(value=><option key={value}>{value}</option>)}</select></label><label>Status<select name="status" value={form.status} onChange={change}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label>
  <label>Revenue<input name="revenue" min="0" step="0.01" type="number" value={form.revenue} onChange={change}/></label>
  </div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?<I.LoaderCircle className="spin"/>:editing?<I.Save/>:<I.Plus/>}{saving?'Saving...':editing?'Save Changes':'Add Client'}</button></div></form></div>}

function ClientDetails({client,onClose,onEdit}){const fields=[['Company',client.name],['Location',client.location],['Contact',client.contact],['Title',client.title||'—'],['Email',client.email],['Phone',client.phone||'—'],['Industry',client.industry],['Status',client.status==='ACTIVE'?'Active':'Inactive'],['Projects',client.projectCount],['Revenue',Number(client.revenue).toLocaleString(undefined,{style:'currency',currency:'USD'})],['Created',displayDate(client.createdAt)]];return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal client-modal" onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><h2>Client Details</h2><p>Live organization data from PostgreSQL.</p></div><button onClick={onClose}><I.X/></button></div><div className="user-detail-list">{fields.map(([label,value])=><p key={label}><span>{label}</span><b>{value}</b></p>)}</div><div className="modal-actions"><button onClick={onClose}>Close</button><button className="primary" onClick={()=>onEdit(client)}><I.Pencil/> Edit Client</button></div></div></div>}

export function ClientsPage(){
  const [clients,setClients]=useState([]),[stats,setStats]=useState({total:0,active:0,inactive:0,projects:0,revenue:0}),[query,setQuery]=useState(''),[status,setStatus]=useState('All Status'),[industry,setIndustry]=useState('All Industries'),[country,setCountry]=useState('All Countries'),[modal,setModal]=useState(null),[details,setDetails]=useState(null),[toast,setToast]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[selected,setSelected]=useState([]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const load=async()=>{setLoading(true);setError('');try{const data=await getClients();setClients(data.clients.map(adapt));setStats(data.stats)}catch(err){setError(err.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const countries=useMemo(()=>[...new Set(clients.map(client=>client.location.split(',').at(-1).trim()))],[clients]);
  const availableIndustries=useMemo(()=>[...new Set([...industries,...clients.map(client=>client.industry)])],[clients]);
  const filtered=useMemo(()=>clients.filter(client=>{const searchable=[client.name,client.location,client.contact,client.email,client.industry].join(' ').toLowerCase();const clientCountry=client.location.split(',').at(-1).trim();return searchable.includes(query.toLowerCase())&&(status==='All Status'||client.statusLabel===status)&&(industry==='All Industries'||client.industry===industry)&&(country==='All Countries'||clientCountry===country)}),[clients,query,status,industry,country]);
  const statItems=[['Total Clients',stats.total,I.Users,'blue'],['Active Clients',stats.active,I.Building2,'green'],['Inactive Clients',stats.inactive,I.Clock3,'orange'],['Projects',stats.projects,I.Folder,'purple'],['Total Revenue',Number(stats.revenue).toLocaleString(undefined,{style:'currency',currency:'USD'}),I.CircleDollarSign,'pink']];
  const save=async form=>{setSaving(true);setError('');try{if(modal?.id)await updateClient(modal.id,form);else await createClient(form);setModal(null);flash(modal?.id?'Client updated successfully':'Client created successfully');await load()}catch(err){setError(err.message)}finally{setSaving(false)}};
  const view=async id=>{setError('');try{setDetails((await getClient(id)).client)}catch(err){setError(err.message)}};
  const remove=async client=>{if(!window.confirm(`Delete ${client.name}? Projects will remain but no longer be assigned to this client.`))return;setError('');try{await deleteClient(client.id);setSelected(current=>current.filter(id=>id!==client.id));flash('Client deleted successfully');await load()}catch(err){setError(err.message)}};
  const toggle=id=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(client=>selected.includes(client.id))?selected.filter(id=>!filtered.some(client=>client.id===id)):[...new Set([...selected,...filtered.map(client=>client.id)])]);
  const exportClients=()=>{const header='Client,Location,Contact Person,Title,Email,Phone,Industry,Status,Revenue,Joined';const rows=filtered.map(client=>[client.name,client.location,client.contact,client.title,client.email,client.phone,client.industry,client.statusLabel,client.revenue,client.joined].map(value=>`"${String(value).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='mikenium-clients.csv';anchor.click();URL.revokeObjectURL(url);flash('Client list exported')};
  return <div className="users-page clients-page"><div className="users-heading"><div><h1>Clients</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Clients</span></div></div><button className="users-add" onClick={()=>setModal({})}><I.Plus/> Add New Client</button></div>
    <div className="user-stats">{statItems.map(([title,value,Icon,color])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{typeof value==='number'?value.toLocaleString():value}</b><p>Live database total</p></div></div>)}</div>
    {error&&<div className="admin-inline-error"><I.CircleAlert/>{error}<button onClick={()=>setError('')}><I.X/></button></div>}
    <div className="card users-table-card"><div className="users-toolbar"><div className="users-search"><I.Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search clients..."/></div><select value={status} onChange={event=>setStatus(event.target.value)}><option>All Status</option><option>Active</option><option>Inactive</option></select><select value={industry} onChange={event=>setIndustry(event.target.value)}><option>All Industries</option>{availableIndustries.map(value=><option key={value}>{value}</option>)}</select><select value={country} onChange={event=>setCountry(event.target.value)}><option>All Countries</option>{countries.map(value=><option key={value}>{value}</option>)}</select><div className="toolbar-spacer"/><button onClick={load} disabled={loading}>{loading?<I.LoaderCircle className="spin"/>:<I.RefreshCw/>} Refresh</button><button onClick={exportClients}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table clients-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(client=>selected.includes(client.id))} onChange={toggleAll}/></th><th>#</th><th>Client</th><th>Contact Person</th><th>Email</th><th>Phone</th><th>Industry</th><th>Status</th><th>Joined On</th><th>Actions</th></tr></thead><tbody>{filtered.map((client,index)=><tr key={client.id}><td><input type="checkbox" checked={selected.includes(client.id)} onChange={()=>toggle(client.id)}/></td><td>{index+1}</td><td><div className="client-identity"><span className={`client-logo ${client.tone}`}>{client.name[0]}</span><span><b>{client.name}</b><small>{client.location}</small></span></div></td><td><span className="client-contact"><b>{client.contact}</b><small>{client.title||'Primary Contact'}</small></span></td><td className="user-email">{client.email}</td><td>{client.phone||'—'}</td><td><span className={`industry-pill ${client.industry.toLowerCase().replaceAll(' ','-')}`}>{client.industry}</span></td><td><span className={`user-status ${client.statusLabel.toLowerCase()}`}>{client.statusLabel}</span></td><td>{client.joined}</td><td><div className="user-actions"><button className="edit-user" onClick={()=>setModal(client)}><I.Pencil/><span>Edit</span></button><button title="View client" onClick={()=>view(client.id)}><I.Eye/></button><button className="danger" title="Delete client" onClick={()=>remove(client)}><I.Trash2/></button></div></td></tr>)}</tbody></table>{loading?<div className="empty"><I.LoaderCircle className="spin"/><b>Loading clients...</b></div>:!filtered.length&&<div className="empty"><I.SearchX/><b>No clients found</b><span>Try changing the search or filters.</span></div>}</div><div className="users-footer"><span>Showing {filtered.length} of {stats.total} database clients</span></div></div>
    {modal&&<ClientModal client={modal.id?modal:null} onClose={()=>setModal(null)} onSave={save} saving={saving}/>} {details&&<ClientDetails client={details} onClose={()=>setDetails(null)} onEdit={client=>{setDetails(null);setModal(adapt(client))}}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>;
}
