import React, { useMemo, useState } from 'react';
import * as I from 'lucide-react';

const clientSeed=[
  {name:'TechSolutions Inc.',location:'New York, USA',contact:'John Smith',title:'CEO',email:'john.smith@techsolutions.com',phone:'+1 (555) 123-4567',industry:'Technology',status:'Active',joined:'Jan 15, 2024',tone:'blue'},
  {name:'HealthCare Plus',location:'Los Angeles, USA',contact:'Sarah Johnson',title:'Manager',email:'sarah.johnson@healthcareplus.com',phone:'+1 (555) 987-6543',industry:'Healthcare',status:'Active',joined:'Feb 10, 2024',tone:'green'},
  {name:'MarketHub Ltd.',location:'London, UK',contact:'Michael Brown',title:'Director',email:'michael.brown@markethub.co.uk',phone:'+44 20 7946 0958',industry:'E-commerce',status:'Active',joined:'Mar 05, 2024',tone:'purple'},
  {name:'EduTech Solutions',location:'Toronto, Canada',contact:'Emily Davis',title:'Co-founder',email:'emily.davis@edutech.ca',phone:'+1 (416) 555-0198',industry:'Education',status:'Inactive',joined:'Mar 18, 2024',tone:'orange'},
  {name:'FinSoft Systems',location:'Sydney, Australia',contact:'David Wilson',title:'CTO',email:'david.wilson@finsoft.com.au',phone:'+61 2 9123 4567',industry:'Finance',status:'Active',joined:'Apr 01, 2024',tone:'blue'},
  {name:'CloudNova',location:'Berlin, Germany',contact:'Laura Martinez',title:'Product Head',email:'laura.martinez@cloudnova.de',phone:'+49 30 12345678',industry:'Technology',status:'Active',joined:'Apr 12, 2024',tone:'cyan'},
  {name:'DesignHub Studio',location:'San Francisco, USA',contact:'James Taylor',title:'Creative Director',email:'james.taylor@designhub.com',phone:'+1 (415) 555-2671',industry:'Design',status:'Active',joined:'Apr 20, 2024',tone:'pink'},
  {name:'RetailPro Group',location:'Dubai, UAE',contact:'Olivia Anderson',title:'Operations Manager',email:'olivia.anderson@retailpro.ae',phone:'+971 50 123 4567',industry:'Retail',status:'Inactive',joined:'May 02, 2024',tone:'brown'},
  {name:'Wellness Life',location:'Singapore',contact:'Daniel Thomas',title:'Founder',email:'daniel.thomas@wellnesslife.sg',phone:'+65 9123 4567',industry:'Wellness',status:'Active',joined:'May 10, 2024',tone:'green'},
  {name:'AutoDrive Co.',location:'Tokyo, Japan',contact:'Sophia Lee',title:'CEO',email:'sophia.lee@autodrive.co.jp',phone:'+81 90 1234 5678',industry:'Automotive',status:'Active',joined:'May 14, 2024',tone:'purple'}
];

const clientStats=[['Total Clients','342','8.3%',I.Users,'blue',true],['Active Clients','245','10.6%',I.Building2,'green',true],['Inactive Clients','22','15.4%',I.Clock3,'orange',false],['Projects','156','12.5%',I.Folder,'purple',true],['Total Revenue','$256,540','9.7%',I.CircleDollarSign,'pink',true]];

function ClientModal({onClose,onSave}){const [form,setForm]=useState({name:'',contact:'',email:'',industry:'Technology',location:''});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal client-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Client</h2><p>Add a company and its primary contact.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label>Company name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. Acme Inc."/></label><label>Contact person<input name="contact" required value={form.contact} onChange={change} placeholder="Full name"/></label><label className="wide">Email address<input name="email" required type="email" value={form.email} onChange={change} placeholder="contact@company.com"/></label><label>Industry<select name="industry" value={form.industry} onChange={change}><option>Technology</option><option>Healthcare</option><option>E-commerce</option><option>Education</option><option>Finance</option><option>Design</option><option>Retail</option><option>Wellness</option><option>Automotive</option></select></label><label>Location<input name="location" required value={form.location} onChange={change} placeholder="City, Country"/></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Client</button></div></form></div>}

export function ClientsPage(){
  const [clients,setClients]=useState(clientSeed),[query,setQuery]=useState(''),[status,setStatus]=useState('All Status'),[industry,setIndustry]=useState('All Industries'),[country,setCountry]=useState('All Countries'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]);
  const filtered=useMemo(()=>clients.filter(c=>{const searchable=[c.name,c.location,c.contact,c.email,c.industry].join(' ').toLowerCase();const clientCountry=c.location.split(', ').at(-1);return searchable.includes(query.toLowerCase())&&(status==='All Status'||c.status===status)&&(industry==='All Industries'||c.industry===industry)&&(country==='All Countries'||clientCountry===country)}),[clients,query,status,industry,country]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addClient=form=>{setClients([{...form,title:'Primary Contact',phone:'—',status:'Active',joined:'Jul 14, 2026',tone:'blue'},...clients]);setModal(false);flash('Client added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(c=>selected.includes(c.email))?selected.filter(id=>!filtered.some(c=>c.email===id)):[...new Set([...selected,...filtered.map(c=>c.email)])]);
  const exportClients=()=>{const header='Client,Location,Contact Person,Title,Email,Phone,Industry,Status,Joined';const rows=filtered.map(c=>[c.name,c.location,c.contact,c.title,c.email,c.phone,c.industry,c.status,c.joined].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-clients.csv';a.click();URL.revokeObjectURL(url);flash('Client list exported')};
  return <div className="users-page clients-page">
    <div className="users-heading"><div><h1>Clients</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Clients</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Client</button></div>
    <div className="user-stats">{clientStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up?'up':'down'}>{up?<I.ArrowUp/>:<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
    <div className="card users-table-card">
      <div className="users-toolbar"><div className="users-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search clients..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Active</option><option>Inactive</option></select><select value={industry} onChange={e=>setIndustry(e.target.value)}><option>All Industries</option>{[...new Set(clientSeed.map(c=>c.industry))].map(x=><option key={x}>{x}</option>)}</select><select value={country} onChange={e=>setCountry(e.target.value)}><option>All Countries</option>{[...new Set(clientSeed.map(c=>c.location.split(', ').at(-1)))].map(x=><option key={x}>{x}</option>)}</select><div className="toolbar-spacer"/><button className="date-button"><I.CalendarDays/> May 15, 2024 - May 21, 2024 <I.ChevronDown/></button><button><I.ListFilter/> Filter</button><button onClick={exportClients}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table clients-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(c=>selected.includes(c.email))} onChange={toggleAll}/></th><th>#</th><th>Client</th><th>Contact Person</th><th>Email</th><th>Phone</th><th>Industry</th><th>Status</th><th>Joined On <I.RotateCw/></th><th>Actions</th></tr></thead><tbody>{filtered.map((c,index)=><tr key={c.email}><td><input type="checkbox" checked={selected.includes(c.email)} onChange={()=>toggle(c.email)}/></td><td>{index+1}</td><td><div className="client-identity"><span className={`client-logo ${c.tone}`}>{c.name[0]}</span><span><b>{c.name}</b><small>{c.location}</small></span></div></td><td><span className="client-contact"><b>{c.contact}</b><small>{c.title}</small></span></td><td className="user-email">{c.email}</td><td>{c.phone}</td><td><span className={`industry-pill ${c.industry.toLowerCase().replaceAll(' ','-')}`}>{c.industry}</span></td><td><span className={`user-status ${c.status.toLowerCase()}`}>{c.status}</span></td><td>{c.joined}</td><td><div className="user-actions"><button title="View client" onClick={()=>flash(`Viewing ${c.name}`)}><I.Eye/></button><button title="Edit client" onClick={()=>flash(`Editing ${c.name}`)}><I.Pencil/></button><button className="more" title="More actions"><I.EllipsisVertical/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No clients found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer"><span>Showing 1 to {filtered.length} of 342 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>35</button><button aria-label="Next"><I.ChevronRight/></button></div></div>
    </div>
    {modal&&<ClientModal onClose={()=>setModal(false)} onSave={addClient}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}
