import React,{useEffect,useMemo,useState} from 'react';
import * as I from 'lucide-react';
import {getPublicBlogs} from '../../services/public-api';
import '../../styles/blog-page.css';
import {companyContact,footerNavigation} from '../../config/site-contact';

const date=value=>new Date(value).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'2-digit'});
const initials=name=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function Logo(){return <a className="public-logo" href="/" aria-label="Mikenium home"><img src="/assets/mikenium-logo-transparent.png" alt="Mikenium — Building Smarter Software"/></a>}
function Header({menu,setMenu,scrolled}){return <header className={'public-header '+(scrolled?'scrolled ':'')+(menu?'menu-open':'')}><Logo/><div className="nav-center"><nav className={menu?'open':''}>{[['Home','/'],['Services','/services'],['Portfolio','/portfolio'],['Products','/products'],['Pricing','/pricing'],['Blog','/blog'],['About','/about']].map(([label,href],index)=><a className={label==='Blog'?'active':''} onClick={()=>setMenu(false)} href={href} key={label}><span>0{index+1}</span>{label}</a>)}</nav></div><div className="nav-actions"><a className="nav-contact" href="/contact"><span>Start a Project</span><I.ArrowUpRight/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)}>{menu?<I.X/>:<I.Menu/>}</button></div></header>}
function Footer(){return <footer id="contact"><div className="footer-glow"/><div className="cta"><div><span className="cta-label"><i/> LET’S CREATE TOGETHER</span><h2>Ready to build software<br/>that moves your business?</h2><p>Bring us the challenge. We’ll bring the strategy, design, and engineering to turn it into a product people value.</p></div><div className="cta-actions"><a className="site-button" href="/contact">Start a Conversation<I.ArrowRight/></a><a href={companyContact.emailHref}>{companyContact.email} <I.ArrowUpRight/></a></div></div><div className="footer-main"><div className="footer-about"><img src="/assets/mikenium-logo-transparent.png" alt="Mikenium — Building Smarter Software"/><p>We design and engineer secure digital products that help ambitious businesses grow with confidence.</p><span className="footer-socials">{companyContact.socialLinks.map(item=>{const Icon=item.Icon;return <a href={item.href} target="_blank" rel="noreferrer" aria-label={item.label} title={item.label} key={item.label}><Icon/></a>})}</span></div><div className="footer-links">{footerNavigation.map(section=><div key={section.title}><h4>{section.title}</h4>{section.links.map(link=><a href={link.href} key={link.label}>{link.label}</a>)}</div>)}</div><div className="footer-contact"><span><I.MapPin/></span><div><h4>Let’s talk about your next idea.</h4><a href={companyContact.emailHref}>{companyContact.email}</a>{companyContact.phones.map(phone=><a href={phone.href} key={phone.href}>{phone.label}</a>)}<small>{companyContact.address}</small></div></div></div><div className="footer-bottom"><p>© 2026 Mikenium. All rights reserved.</p><nav><a href="/">Privacy Policy</a><a href="/">Terms of Service</a><a href="/">Cookie Policy</a></nav><span><i/> All systems operational</span></div></footer>}
function Card({post,index}){return <article className="journal-card reveal"><a href={`/blog/${post.slug}`} className="journal-image" style={post.coverImageUrl?{backgroundImage:`linear-gradient(180deg,transparent,#06142a6e),url("${post.coverImageUrl}")`,backgroundSize:'cover',backgroundPosition:'center'}:undefined}><span className="card-index">{String(index+1).padStart(2,'0')}</span><span className="image-action"><I.ArrowUpRight/></span></a><div className="journal-copy"><span className="post-category">{post.category}</span><h3><a href={`/blog/${post.slug}`}>{post.title}</a></h3><p>{post.excerpt}</p><div className="post-meta"><span><I.CalendarDays/>{date(post.publishedAt)}</span><span><I.Clock3/>{post.readingMinutes} min read</span></div><a className="read-link" href={`/blog/${post.slug}`}>Read insight <I.ArrowRight/></a></div></article>}

export default function BlogPage(){
  const [menu,setMenu]=useState(false),[scrolled,setScrolled]=useState(false),[category,setCategory]=useState('All'),[query,setQuery]=useState(''),[posts,setPosts]=useState([]),[loading,setLoading]=useState(true);
  const categories=useMemo(()=>['All',...new Set(posts.map(x=>x.category))],[posts]);
  const featured=posts.find(x=>x.featured)||posts[0];
  const visible=useMemo(()=>posts.filter(x=>(category==='All'||x.category===category)&&`${x.title} ${x.excerpt} ${x.category}`.toLowerCase().includes(query.toLowerCase())),[posts,category,query]);
  useEffect(()=>{let active=true;getPublicBlogs().then(items=>active&&setPosts(items)).catch(()=>{}).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
  useEffect(()=>{const scroll=()=>setScrolled(scrollY>20);scroll();addEventListener('scroll',scroll,{passive:true});const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('is-visible')),{threshold:.08});document.querySelectorAll('.blog-page .reveal').forEach(el=>observer.observe(el));return()=>{removeEventListener('scroll',scroll);observer.disconnect()}},[visible.length]);
  return <div className="public-site blog-page"><Header menu={menu} setMenu={setMenu} scrolled={scrolled}/><main>
    <section className="blog-hero"><div className="blog-grid-lines"/><div className="hero-orb orb-a"/><div className="hero-orb orb-b"/><div className="blog-hero-copy"><span className="blog-kicker"><i/> IDEAS FOR BUILDERS</span><h1>Thinking at the edge<br/>of <span>what’s next.</span></h1><p>Clear thinking on software, design, AI, and the decisions that turn ambitious ideas into valuable digital products.</p><div className="hero-reading"><span><I.BookOpen/> Fresh perspectives from our team</span><a href="#journal">Explore the journal <I.ArrowDown/></a></div></div><div className="blog-hero-art"><div className="art-frame"><div className="art-image"/><span className="art-label">MIKENIUM / JOURNAL</span></div></div></section>
    {featured&&<section className="featured-story reveal"><div className="featured-visual" style={featured.coverImageUrl?{backgroundImage:`linear-gradient(180deg,transparent,#031127b8),url("${featured.coverImageUrl}")`,backgroundSize:'cover',backgroundPosition:'center'}:undefined}><span>FEATURED / {featured.readingMinutes} MIN READ</span><div className="featured-signal"><i/> NEW PERSPECTIVE</div></div><div className="featured-copy"><span className="section-label">EDITOR’S PICK · {featured.category}</span><h2>{featured.title}</h2><p>{featured.excerpt}</p><div className="featured-author"><span>{initials(featured.authorName)}</span><div><b>{featured.authorName}</b><small>{date(featured.publishedAt)}</small></div><a href={`/blog/${featured.slug}`}><I.ArrowUpRight/></a></div></div></section>}
    <section className="journal" id="journal"><div className="journal-head reveal"><div><span className="section-label">THE LATEST FROM OUR TEAM</span><h2>Ideas worth building on.</h2></div><p>Field notes from the people designing, shipping, and evolving modern software.</p></div><div className="journal-tools reveal"><div className="category-tabs">{categories.map(x=><button className={category===x?'active':''} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><label className="journal-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search insights..."/>{query&&<button onClick={()=>setQuery('')}><I.X/></button>}</label></div>
      {loading?<div className="empty-state"><I.LoaderCircle className="spin"/><h3>Loading insights...</h3></div>:visible.length?<div className="journal-layout"><div className="journal-grid">{visible.map((post,index)=><Card post={post} index={index} key={post.id}/>)}</div><aside className="journal-aside reveal"><span className="aside-label">MOST READ</span><h3>Popular with product teams</h3>{[...posts].sort((a,b)=>b.views-a.views).slice(0,4).map((post,i)=><a href={`/blog/${post.slug}`} key={post.id}><strong>0{i+1}</strong><span><b>{post.title}</b><small>{post.readingMinutes} min · {post.category}</small></span><I.ArrowUpRight/></a>)}</aside></div>:<div className="empty-state"><I.SearchX/><h3>No insights found</h3><p>Published articles from Super Admin will appear here.</p></div>}
    </section>
  </main><Footer/></div>;
}
