import React,{useEffect,useState} from 'react';
import * as I from 'lucide-react';
import '../../styles/public-home.css';
import '../../styles/legal-pages.css';
import {companyContact} from '../../config/site-contact';

const pages={
  privacy:{eyebrow:'YOUR DATA',title:'Privacy Policy',summary:'How Mikenium collects, uses, protects, and shares personal information when you use our website or work with us.',updated:'22 July 2026',sections:[
    ['Information we collect',<><p>We may collect information you provide directly, including your name, email address, telephone number, company, project details, and messages submitted through our forms. We also collect limited technical information such as browser type, device information, IP address, and pages visited.</p></>],
    ['How we use information',<><p>We use personal information to respond to enquiries, provide and improve our services, manage client relationships, protect our systems, comply with legal obligations, and send updates where you have chosen to receive them.</p></>],
    ['Legal basis and consent',<><p>We process information where it is necessary to respond to your request, perform a contract, meet a legal obligation, pursue a legitimate business interest, or where you have given consent. You may withdraw consent at any time.</p></>],
    ['Sharing and international processing',<><p>We do not sell personal information. We may share it with vetted service providers that support hosting, communications, analytics, security, or professional advice, and with authorities where the law requires it. Appropriate safeguards are used when information is processed outside your country.</p></>],
    ['Retention and security',<><p>We keep personal information only as long as needed for the purpose collected, legal requirements, and legitimate record keeping. We use reasonable administrative, technical, and physical safeguards, although no internet service can guarantee absolute security.</p></>],
    ['Your rights',<><p>Depending on applicable law, you may ask to access, correct, delete, restrict, or receive a copy of your personal information, or object to certain processing. Contact us to make a request; we may need to verify your identity.</p></>],
    ['Contact us',<><p>Questions or privacy requests can be sent to <a href={companyContact.emailHref}>{companyContact.email}</a> or mailed to {companyContact.address}.</p></>]
  ]},
  terms:{eyebrow:'WEBSITE TERMS',title:'Terms of Service',summary:'The rules that apply when you access Mikenium’s website, content, and digital services.',updated:'22 July 2026',sections:[
    ['Acceptance of these terms',<p>By accessing this website, you agree to these terms and our Privacy and Cookie Policies. If you do not agree, please do not use the website.</p>],
    ['Website use',<p>You may use the website for lawful, personal, or business-information purposes. You must not disrupt the website, attempt unauthorised access, introduce harmful code, scrape content at scale, misrepresent your identity, or use the website to violate another person’s rights.</p>],
    ['Services and proposals',<p>Website information is general and is not a binding offer. Software development, design, support, or other professional services are governed by a separate proposal or agreement signed with the client. If that agreement conflicts with these terms, the signed agreement controls.</p>],
    ['Intellectual property',<p>The website, brand, design, text, graphics, and software are owned by or licensed to Mikenium and protected by applicable intellectual-property laws. You may not reproduce, modify, distribute, or commercially exploit them without written permission.</p>],
    ['Third-party links',<p>Links to third-party websites are provided for convenience. We do not control or endorse their content, availability, security, or privacy practices.</p>],
    ['Disclaimers and liability',<p>We aim to keep website information accurate and the service available, but provide the website on an “as available” basis. To the extent permitted by law, Mikenium is not liable for indirect, incidental, or consequential loss arising from use of this website.</p>],
    ['Changes and contact',<p>We may update these terms as our services or legal requirements change. The date above shows the latest revision. Questions may be sent to <a href={companyContact.emailHref}>{companyContact.email}</a>.</p>]
  ]},
  cookies:{eyebrow:'YOUR CHOICES',title:'Cookie Policy',summary:'What cookies are, how Mikenium uses them, and how you can control optional cookies.',updated:'22 July 2026',sections:[
    ['What cookies are',<p>Cookies are small text files stored on your device by a website. They help websites remember information, maintain secure functions, and understand how visitors use a service.</p>],
    ['Cookies we use',<><div className="legal-table"><div><b>Necessary</b><span>Consent choices, security, and essential site functions</span><em>Always active</em></div><div><b>Analytics</b><span>Aggregated website usage and performance measurement</span><em>Optional</em></div><div><b>Marketing</b><span>Campaign measurement and more relevant communications</span><em>Optional</em></div></div><p>We currently keep optional categories disabled unless you accept them. The providers and exact duration may change as the website evolves.</p></>],
    ['Managing your choices',<><p>You can accept, reject, or customise optional cookies in our preference panel. Your choice is stored for up to 180 days, after which we may ask again.</p><button className="manage-cookie-button" onClick={()=>window.dispatchEvent(new Event('mikenium:open-cookie-settings'))}><I.Settings2/> Manage cookie preferences</button></>],
    ['Browser controls',<p>Most browsers let you delete or block cookies in their privacy settings. Blocking necessary cookies may prevent parts of the website from working correctly.</p>],
    ['Updates and contact',<p>We may update this policy when our cookie use changes. Questions can be sent to <a href={companyContact.emailHref}>{companyContact.email}</a>.</p>]
  ]}
};

function Header(){const [menu,setMenu]=useState(false),[scrolled,setScrolled]=useState(false);useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>20);onScroll();addEventListener('scroll',onScroll,{passive:true});return()=>removeEventListener('scroll',onScroll)},[]);return <header className={'public-header '+(scrolled?'scrolled ':'')+(menu?'menu-open':'')}><a className="public-logo" href="/"><img src={companyContact.logoUrl} alt={companyContact.logoAlt}/></a><div className="nav-center"><nav className={menu?'open':''}>{[['Home','/'],['Services','/services'],['Portfolio','/portfolio'],['Products','/products'],['Pricing','/pricing'],['Blog','/blog'],['About','/about']].map(([label,href],i)=><a href={href} key={label}><span>0{i+1}</span>{label}</a>)}</nav></div><div className="nav-actions"><a className="nav-contact" href="/contact"><span>Start a Project</span><I.ArrowUpRight/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">{menu?<I.X/>:<I.Menu/>}</button></div></header>}
function Footer(){return <footer className="legal-footer"><div><p>{companyContact.copyright}</p><nav><a href="/privacy-policy">Privacy Policy</a><a href="/terms-of-service">Terms of Service</a><a href="/cookie-policy">Cookie Policy</a></nav><a href="/">Back to Mikenium <I.ArrowUpRight/></a></div></footer>}

export default function LegalPage({type}){const page=pages[type];useEffect(()=>{document.title=`${page.title} | Mikenium`;window.scrollTo(0,0)},[page.title]);return <div className={`public-site legal-page legal-${type}`}><Header/><main><section className="legal-hero"><div className="legal-breadcrumb"><a href="/">Home</a><I.ChevronRight/><span>{page.title}</span></div><span className="legal-eyebrow"><i/>{page.eyebrow}</span><h1>{page.title}</h1><p>{page.summary}</p><div className="legal-meta"><span><I.CalendarDays/>Last updated {page.updated}</span><span><I.Clock3/>{Math.max(3,Math.ceil(page.sections.length*.7))} minute read</span></div></section><div className="legal-layout"><aside><div><I.ListTree/><span><b>Contents</b><small>Jump to a section</small></span></div><nav>{page.sections.map(([title],i)=><a href={`#section-${i+1}`} key={title}><span>{String(i+1).padStart(2,'0')}</span>{title}<I.ChevronRight/></a>)}</nav></aside><article><header className="legal-document-head"><span><I.ShieldCheck/></span><div><b>Mikenium {page.title}</b><p>This document applies to visitors of mikenium.com and customers who interact with us through this website.</p></div></header>{page.sections.map(([title,content],i)=><section id={`section-${i+1}`} key={title}><span>{String(i+1).padStart(2,'0')}</span><div><h2>{title}</h2>{content}</div></section>)}<div className="legal-help"><span><I.MessageCircleQuestion/></span><div><b>Still have a question?</b><p>Contact our team and we’ll help clarify anything in this document.</p></div><a href={companyContact.emailHref}>Contact us<I.ArrowUpRight/></a></div></article></div></main><Footer/></div>}
