import React, { useEffect, useState } from 'react';
import * as I from 'lucide-react';
import '../../styles/public-home.css';
import '../../styles/portfolio-page.css';
import {companyContact,footerNavigation} from '../../config/site-contact';
import { getPublicProjects } from '../../services/public-api';

const navItems=[['Home','/'],['Services','/services'],['Portfolio','/portfolio'],['Products','/products'],['Pricing','/pricing'],['Blog','/blog'],['About','/about']];
const filters=[
  ['All work',I.LayoutGrid,'all'],['Web platforms',I.Monitor,'web'],['Mobile apps',I.Smartphone,'mobile'],
  ['Product design',I.PenTool,'design'],['Cloud systems',I.Cloud,'cloud'],['Commerce',I.ShoppingBag,'commerce']
];
function Logo(){return <a className="public-logo" href="/" aria-label="Mikenium home"><img src={companyContact.logoUrl} alt={companyContact.logoAlt}/></a>}
function SiteButton({children,href='/#contact'}){return <a className="site-button" href={href}>{children}<I.ArrowRight/></a>}
function Header(){const [menu,setMenu]=useState(false);const [scrolled,setScrolled]=useState(false);useEffect(()=>{const fn=()=>setScrolled(window.scrollY>20);fn();window.addEventListener('scroll',fn,{passive:true});return()=>window.removeEventListener('scroll',fn)},[]);return <header className={'public-header '+(scrolled?'scrolled ':'')+(menu?'menu-open':'')}><Logo/><div className="nav-center"><nav className={menu?'open':''}>{navItems.map(([label,href],index)=><a className={label==='Portfolio'?'active':''} onClick={()=>setMenu(false)} href={href} key={label}><span>0{index+1}</span>{label}</a>)}</nav></div><div className="nav-actions"><a className="nav-contact" href="/contact"><span>Start a Project</span><I.ArrowUpRight/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu?<I.X/>:<I.Menu/>}</button></div></header>}
function ProjectVisual({project}){const Icon=project.icon;if(project.imageUrl)return <div className="portfolio-visual uploaded-project-image"><img src={project.imageUrl} alt={`${project.title} project`}/></div>;return <div className={'portfolio-visual '+project.tone}><div className="visual-noise"/><div className="mini-browser"><div className="mini-bar"><i/><i/><i/><span>mikenium / {project.title.toLowerCase()}</span></div><div className="mini-nav"><Icon/><i/><i/><i/></div><div className="mini-content"><span className="mini-label">{project.type}</span><strong>{project.title}</strong><div className="mini-widgets"><i/><i/><i/></div><div className="mini-chart"><b/><b/><b/><b/><b/><b/></div></div></div><span className="project-float"><Icon/><b>{project.result}</b></span></div>}
function ProjectCard({project,index}){const href=project.projectUrl||'/#contact';const external=Boolean(project.projectUrl);return <article className={'portfolio-card reveal '+(index===0?'portfolio-featured':'')}><ProjectVisual project={project}/><div className="portfolio-card-copy"><div className="card-meta"><span>0{index+1} / {project.type}</span><b>{project.result}</b></div><h3>{project.title}<a href={href} target={external?'_blank':undefined} rel={external?'noreferrer':undefined} aria-label={external?`Open ${project.title}`:`Discuss a project like ${project.title}`}><I.ArrowUpRight/></a></h3><p>{project.copy}</p><div className="project-tags">{project.tags.map(tag=><span key={tag}>{tag}</span>)}<a href={href} target={external?'_blank':undefined} rel={external?'noreferrer':undefined}>{external?'Visit project':'View project'} <I.ArrowRight/></a></div></div></article>}
function Footer(){return <footer id="contact"><div className="footer-glow"/><div className="cta"><div><span className="cta-label"><i/> LET’S CREATE TOGETHER</span><h2>Ready to build software<br/>that moves your business?</h2><p>Bring us the challenge. We’ll bring the strategy, design, and engineering to turn it into a product people value.</p></div><div className="cta-actions"><SiteButton>Start a Conversation</SiteButton><a href={companyContact.emailHref}>{companyContact.email} <I.ArrowUpRight/></a></div></div><div className="footer-main"><div className="footer-about"><img src="/assets/mikenium-logo-transparent.png" alt="Mikenium — Building Smarter Software"/><p>We design and engineer secure digital products that help ambitious businesses grow with confidence.</p><span className="footer-socials">{companyContact.socialLinks.map(item=>{const Icon=item.Icon;return <a href={item.href} target="_blank" rel="noreferrer" aria-label={item.label} title={item.label} key={item.label}><Icon/></a>})}</span></div><div className="footer-links">{footerNavigation.map(section=><div key={section.title}><h4>{section.title}</h4>{section.links.map(link=><a href={link.href} key={link.label}>{link.label}</a>)}</div>)}</div><div className="footer-contact"><span><I.MapPin/></span><div><h4>Let’s talk about your next idea.</h4><a href={companyContact.emailHref}>{companyContact.email}</a>{companyContact.phones.map(phone=><a href={phone.href} key={phone.href}>{phone.label}</a>)}<small>{companyContact.address}</small></div></div></div><div className="footer-bottom"><p>© 2026 Mikenium. All rights reserved.</p><nav><a href="/">Privacy Policy</a><a href="/">Terms of Service</a><a href="/">Cookie Policy</a></nav><span><i/> All systems operational</span></div></footer>}

export default function PortfolioPage(){
  const [active,setActive]=useState('all');
  const [databaseProjects,setDatabaseProjects]=useState([]);
  const [projectsLoading,setProjectsLoading]=useState(true);
  useEffect(()=>{let mounted=true;getPublicProjects().then(items=>{if(mounted)setDatabaseProjects(items)}).catch(()=>{}).finally(()=>mounted&&setProjectsLoading(false));return()=>{mounted=false}},[]);
  useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add('is-visible')),{threshold:.1});document.querySelectorAll('.portfolio-page .reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[active,databaseProjects.length]);
  const iconFor=category=>category==='mobile'?I.Smartphone:category==='design'?I.PenTool:category==='cloud'?I.CloudCog:category==='commerce'?I.ShoppingBag:I.Monitor;
  const categoryFor=value=>{const category=value.toLowerCase();if(category.includes('mobile'))return'mobile';if(category.includes('design')||category.includes('ui/ux'))return'design';if(category.includes('cloud'))return'cloud';if(category.includes('commerce'))return'commerce';return'web'};
  const liveProjects=databaseProjects.map(project=>{const category=categoryFor(project.category);return {id:project.id,title:project.name,type:project.client||project.category,category,result:project.result||'Mikenium project',copy:project.description,tone:project.theme||'analytics',tags:project.tags.length?project.tags:[project.category],imageUrl:project.imageUrl,projectUrl:project.projectUrl,icon:iconFor(category)}});
  const projects=liveProjects;
  const visible=active==='all'?projects:projects.filter(project=>project.category===active);
  return <div className="public-site portfolio-page"><Header/><main>
    <section className="portfolio-hero"><div className="portfolio-grid-bg"/><div className="portfolio-glow glow-one"/><div className="portfolio-glow glow-two"/><div className="portfolio-hero-copy"><span className="portfolio-kicker"><i/> SELECTED WORK <b>2021 — 2026</b></span><h1>Digital products<br/>with <em>measurable</em><br/><span>momentum.</span></h1><p>We pair sharp product thinking with thoughtful design and resilient engineering to create software people choose to use.</p><div className="portfolio-actions"><SiteButton href="#work">Explore our work</SiteButton><a href="/#contact">Start a project <I.ArrowUpRight/></a></div><div className="hero-proofline"><span><b>100+</b> products shipped</span><i/><span><b>15+</b> industries</span><i/><span><b>98%</b> client satisfaction</span></div></div>
      <div className="portfolio-hero-art" aria-label="A collection of Mikenium digital product interfaces"><div className="hero-art-orbit one"/><div className="hero-art-orbit two"/><div className="showcase-frame"><span className="showcase-status"><i/> LIVE PRODUCTS</span><img src="/assets/portfolio-showcase.png" alt="Analytics, media, commerce and productivity software interfaces"/><div className="showcase-shine"/></div><div className="hero-chip chip-impact"><I.TrendingUp/><span><b>42% average gain</b><small>in operational efficiency</small></span></div><div className="hero-chip chip-users"><I.UsersRound/><span><b>120K+ users</b><small>supported every day</small></span></div></div>
    </section>
    <section className="work-section" id="work"><div className="work-heading reveal"><div><span className="portfolio-kicker">OUR PROJECTS</span><h2>Built for the real world.<br/><em>Designed to stand apart.</em></h2></div><p>Explore a selection of platforms, experiences, and systems we’ve created with ambitious teams.</p></div>{projectsLoading&&<p className="portfolio-loading"><I.LoaderCircle/> Loading latest projects...</p>}{!projectsLoading&&projects.length>0&&<div className="filter-bar reveal" role="toolbar" aria-label="Filter portfolio projects">{filters.map(([label,Icon,value])=><button className={active===value?'active':''} onClick={()=>setActive(value)} aria-pressed={active===value} key={value}><Icon/>{label}<span>{value==='all'?projects.length:projects.filter(p=>p.category===value).length}</span></button>)}</div>}<div className="portfolio-list" key={active}>{visible.map((project,index)=><ProjectCard project={project} index={index} key={project.id}/>)}</div>{!projectsLoading&&!projects.length&&<div className="portfolio-empty"><I.FolderOpen/><h3>No published projects yet</h3><p>Projects published by the Super Admin will appear here.</p></div>}</section>
    <section className="portfolio-impact reveal"><div><span className="portfolio-kicker">THE WORK BEHIND THE WORK</span><h2>Good software doesn’t just look<br/>different. It <em>works better.</em></h2></div><div className="impact-stats">{[[I.Box,'120+','Projects completed'],[I.Smile,'80+','Happy clients'],[I.Award,'5+','Years of experience'],[I.Rocket,'15+','Industries served']].map(([Icon,num,label])=><article key={label}><Icon/><span><b>{num}</b><small>{label}</small></span></article>)}</div></section>
  </main><Footer/></div>
}
