import React, { useEffect, useMemo, useState } from 'react';
import * as I from 'lucide-react';
import '../../styles/public-home.css';
import '../../styles/products-page.css';

const navItems=[['Home','/'],['Services','/services'],['Portfolio','/portfolio'],['Products','/products'],['Pricing','/pricing'],['Blog','/blog'],['About','/about']];
const categories=[['All products','all'],['SaaS platforms','saas'],['Developer tools','developer'],['Business tools','business'],['Mobile apps','mobile'],['E-commerce','commerce']];
const products=[
  {name:'Mikenium Analytics',category:'saas',label:'SaaS Platform',copy:'Turn complex business data into clear, confident decisions with real-time intelligence.',features:['Live dashboards','Smart forecasting'],icon:I.ChartNoAxesCombined,tone:'blue',action:'Live demo',visual:'analytics'},
  {name:'TaskFlow',category:'saas',label:'SaaS Platform',copy:'Keep projects, priorities, and people moving together in one focused workspace.',features:['Team planning','Workflow automation'],icon:I.CircleCheckBig,tone:'violet',action:'Live demo',visual:'tasks'},
  {name:'EazyStore',category:'commerce',label:'E-commerce',copy:'Launch and grow a fast, flexible storefront with every tool built in.',features:['Smart inventory','Secure checkout'],icon:I.Store,tone:'green',action:'Live demo',visual:'store'},
  {name:'Mikenium Wallet',category:'mobile',label:'Mobile App',copy:'A beautifully simple digital wallet for payments, transfers, and everyday money.',features:['Instant transfers','Bank-grade security'],icon:I.WalletCards,tone:'orange',action:'Google Play',visual:'wallet'},
  {name:'CodeStarter',category:'developer',label:'Developer Tool',copy:'Production-ready starter kits that help modern product teams build faster.',features:['Clean architecture','Ready-to-ship UI'],icon:I.CodeXml,tone:'cyan',action:'GitHub',visual:'code'},
  {name:'LeadCRM',category:'business',label:'Business Tool',copy:'Bring leads, customers, conversations, and revenue into one intelligent view.',features:['Visual pipelines','Sales insights'],icon:I.UsersRound,tone:'teal',action:'Live demo',visual:'crm'},
  {name:'CloudPanel',category:'developer',label:'DevOps Tool',copy:'Manage servers, deployments, and databases from one calm command center.',features:['One-click deploys','Live monitoring'],icon:I.CloudCog,tone:'purple',action:'Live demo',visual:'cloud'},
  {name:'Invoice.ly',category:'business',label:'Business Tool',copy:'Create polished invoices, manage clients, and get paid without the busywork.',features:['Fast invoicing','Payment tracking'],icon:I.FileText,tone:'yellow',action:'Live demo',visual:'invoice'},
  {name:'LearnHub',category:'mobile',label:'Mobile App',copy:'A modern learning platform for courses, quizzes, progress, and community.',features:['Adaptive courses','Progress insights'],icon:I.GraduationCap,tone:'pink',action:'Google Play',visual:'learn'}
];

function Logo(){return <a className="public-logo" href="/" aria-label="Mikenium home"><img src="/assets/mikenium-logo-transparent.png" alt="Mikenium — Building Smarter Software"/></a>}
function SiteButton({children,href='/#contact'}){return <a className="site-button" href={href}>{children}<I.ArrowRight/></a>}
function Header(){const [menu,setMenu]=useState(false);const [scrolled,setScrolled]=useState(false);useEffect(()=>{const fn=()=>setScrolled(window.scrollY>20);fn();window.addEventListener('scroll',fn,{passive:true});return()=>window.removeEventListener('scroll',fn)},[]);return <header className={'public-header '+(scrolled?'scrolled ':'')+(menu?'menu-open':'')}><Logo/><div className="nav-center"><nav className={menu?'open':''}>{navItems.map(([label,href],index)=><a className={label==='Products'?'active':''} onClick={()=>setMenu(false)} href={href} key={label}><span>0{index+1}</span>{label}</a>)}</nav></div><div className="nav-actions"><a className="nav-contact" href="/contact"><span>Start a Project</span><I.ArrowUpRight/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu?<I.X/>:<I.Menu/>}</button></div></header>}
function Footer(){return <footer id="contact"><div className="footer-glow"/><div className="cta"><div><span className="cta-label"><i/> LET’S CREATE TOGETHER</span><h2>Ready to build software<br/>that moves your business?</h2><p>Bring us the challenge. We’ll bring the strategy, design, and engineering to turn it into a product people value.</p></div><div className="cta-actions"><SiteButton>Start a Conversation</SiteButton><a href="mailto:hello@mikenium.com">hello@mikenium.com <I.ArrowUpRight/></a></div></div><div className="footer-main"><div className="footer-about"><img src="/assets/mikenium-logo-transparent.png" alt="Mikenium — Building Smarter Software"/><p>We design and engineer secure digital products that help ambitious businesses grow with confidence.</p><span className="footer-socials">{[I.Facebook,I.Linkedin,I.Twitter,I.Github,I.Instagram].map((Icon,i)=><a href="/" aria-label="Social link" key={i}><Icon/></a>)}</span></div><div className="footer-links"><div><h4>Company</h4>{[['About Us','/about'],['Our Work','/portfolio'],['Careers','/#contact'],['Contact','/#contact']].map(([label,href])=><a href={href} key={label}>{label}</a>)}</div><div><h4>Expertise</h4>{['Web Development','Mobile Apps','Cloud Solutions','UI/UX Design'].map(x=><a href="/services#capabilities" key={x}>{x}</a>)}</div><div><h4>Resources</h4>{[['Insights','/#blog'],['Products','/products'],['Pricing','/pricing'],['Client Stories','/portfolio']].map(([label,href])=><a href={href} key={label}>{label}</a>)}</div></div><div className="footer-contact"><span><I.MapPin/></span><div><h4>Let’s talk about your next idea.</h4><a href="mailto:hello@mikenium.com">hello@mikenium.com</a><a href="tel:+94112345678">+94 11 234 5678</a><small>Colombo, Sri Lanka</small></div></div></div><div className="footer-bottom"><p>© 2026 Mikenium. All rights reserved.</p><nav><a href="/">Privacy Policy</a><a href="/">Terms of Service</a><a href="/">Cookie Policy</a></nav><span><i/> All systems operational</span></div></footer>}

function HeroDashboard(){return <div className="product-command" aria-label="Mikenium product analytics command center"><div className="command-top"><span className="command-logo"><I.Sparkles/></span><div><b>Product intelligence</b><small>All systems connected</small></div><span className="command-live"><i/> LIVE</span></div><div className="command-body"><aside><I.LayoutDashboard/><I.ChartSpline/><I.UsersRound/><I.FolderKanban/><I.Settings/></aside><div className="command-content"><div className="command-title"><span><small>Overview</small><b>Good morning, Alex.</b></span><button><I.CalendarDays/> This month</button></div><div className="command-metrics"><span><small>Revenue</small><b>$84,240</b><em>+18.2%</em></span><span><small>Active users</small><b>24,890</b><em>+12.4%</em></span><span><small>Conversion</small><b>8.42%</b><em>+3.1%</em></span></div><div className="command-grid"><div className="command-chart"><span><b>Growth velocity</b><small>Last 12 weeks</small></span><svg viewBox="0 0 420 150" role="img" aria-label="Rising growth chart"><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#28bff2" stopOpacity=".42"/><stop offset="1" stopColor="#28bff2" stopOpacity="0"/></linearGradient></defs><path className="chart-area" d="M5 130 C40 123 57 94 91 103 S145 124 174 78 S230 105 263 61 S315 84 346 42 S386 54 415 18 L415 150 L5 150Z"/><path className="chart-line" d="M5 130 C40 123 57 94 91 103 S145 124 174 78 S230 105 263 61 S315 84 346 42 S386 54 415 18"/></svg></div><div className="command-ring"><span>Engagement</span><div><b>86%</b></div><small><i/> Excellent health</small></div></div></div></div><span className="hero-float float-release"><I.Rocket/><b>Release shipped</b><small>v4.8 is live</small></span><span className="hero-float float-secure"><I.ShieldCheck/><b>Secure by design</b><small>99.99% uptime</small></span></div>}

function ProductVisual({product}){const Icon=product.icon;return <div className={'product-visual '+product.tone+' '+product.visual}><div className="pv-orb"/><div className="pv-window"><div className="pv-bar"><i/><i/><i/><span>{product.name.toLowerCase().replaceAll(' ','-')}.app</span></div><div className="pv-layout"><aside><Icon/><i/><i/><i/><i/></aside><div className="pv-content"><span className="pv-heading"><b>{product.name}</b><i/></span><div className="pv-stats"><i/><i/><i/></div><div className="pv-data"><span/><span/><span/><span/><span/><span/></div></div></div></div><span className="pv-badge"><Icon/></span></div>}

function ProductCard({product,index}){const Icon=product.icon;return <article className="catalog-card reveal"><ProductVisual product={product}/><div className="catalog-copy"><div className="catalog-heading"><span className={'catalog-icon '+product.tone}><Icon/></span><span><small>{product.label}</small><h3>{product.name}</h3></span><em>0{index+1}</em></div><p>{product.copy}</p><ul>{product.features.map(feature=><li key={feature}><I.Check/>{feature}</li>)}</ul><div className="catalog-actions"><a href="/#contact">View details <I.ArrowRight/></a><a className="product-demo" href="/#contact">{product.action} {product.action==='GitHub'?<I.Github/>:product.action==='Google Play'?<I.Play/>:<I.ArrowUpRight/>}</a></div></div></article>}

export default function ProductsPage(){
  const [active,setActive]=useState('all');
  const [query,setQuery]=useState('');
  const visible=useMemo(()=>products.filter(product=>(active==='all'||product.category===active)&&`${product.name} ${product.label} ${product.copy}`.toLowerCase().includes(query.toLowerCase())),[active,query]);
  useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add('is-visible')),{threshold:.08});document.querySelectorAll('.products-page .reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[active,query]);
  return <div className="public-site products-page"><Header/><main>
    <section className="products-hero"><div className="products-hero-grid"/><div className="products-aurora a-one"/><div className="products-aurora a-two"/><div className="products-hero-copy"><span className="products-kicker"><i/> PRODUCTS BY MIKENIUM <b>9 PRODUCTS · ONE ECOSYSTEM</b></span><h1>Useful software.<br/>Designed to make<br/><span>work feel lighter.</span></h1><p>From insight to execution, our products solve real operational problems with thoughtful design, dependable engineering, and room to grow.</p><div className="products-hero-actions"><SiteButton href="#catalog">Explore the suite</SiteButton><a href="/#contact">Build something new <I.ArrowUpRight/></a></div><div className="products-principles">{[[I.Layers3,'Scales with you','Modern, flexible foundations'],[I.ShieldCheck,'Built to be trusted','Secure from day one'],[I.Zap,'Easy from the start','Clear, focused experiences']].map(([Icon,title,copy])=><span key={title}><Icon/><span><b>{title}</b><small>{copy}</small></span></span>)}</div></div><div className="products-hero-art"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><HeroDashboard/></div></section>

    <section className="product-catalog" id="catalog"><div className="catalog-intro reveal"><span className="catalog-kicker">THE MIKENIUM PRODUCT SUITE</span><div><h2>Tools that turn<br/><span>momentum into growth.</span></h2><p>Purpose-built products for modern teams. Pick the tools you need today and add more as your business evolves.</p></div></div><div className="catalog-toolbar"><div className="category-tabs" role="tablist" aria-label="Product categories">{categories.map(([label,value])=><button role="tab" aria-selected={active===value} className={active===value?'active':''} onClick={()=>setActive(value)} key={value}>{label}</button>)}</div><label className="catalog-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..." aria-label="Search products"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><I.X/></button>}</label></div><div className="catalog-result"><span><b>{visible.length}</b> products ready to explore</span><i/></div><div className="catalog-grid">{visible.map((product,index)=><ProductCard product={product} index={index} key={product.name}/>)}</div>{visible.length===0&&<div className="empty-products"><I.SearchX/><h3>No products found</h3><p>Try a different search or browse another category.</p><button onClick={()=>{setQuery('');setActive('all')}}>Show all products</button></div>}
    </section>

    <section className="product-idea reveal"><div className="idea-copy"><span>HAVE AN IDEA?</span><h2>Your next product<br/>could start <em>right here.</em></h2><p>Tell us what is slowing your team down. We’ll help shape, design, and build the software that changes it.</p><SiteButton>Start a product conversation</SiteButton></div><div className="idea-stats">{[[I.Box,'10+','Products launched'],[I.UsersRound,'5K+','Happy users'],[I.Download,'50K+','Downloads'],[I.Star,'98%','Customer satisfaction']].map(([Icon,n,label])=><span key={label}><Icon/><b>{n}</b><small>{label}</small></span>)}</div><div className="idea-glow"/></section>
  </main><Footer/></div>;
}
