import React,{useEffect,useMemo,useState} from 'react';
import * as I from 'lucide-react';
import {getPublicBlog,getPublicBlogs} from '../../services/public-api';
import '../../styles/single-blog-page.css';
import {companyContact,footerNavigation} from '../../config/site-contact';

const date=value=>new Date(value).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'});
const initials=name=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function Logo(){return <a className="public-logo" href="/"><img src={companyContact.logoUrl} alt={companyContact.logoAlt}/></a>}
function Header({menu,setMenu,scrolled}){return <header className={'public-header '+(scrolled?'scrolled ':'')+(menu?'menu-open':'')}><Logo/><div className="nav-center"><nav className={menu?'open':''}>{[['Home','/'],['Services','/services'],['Portfolio','/portfolio'],['Products','/products'],['Pricing','/pricing'],['Blog','/blog'],['About','/about']].map(([label,href],i)=><a className={label==='Blog'?'active':''} href={href} key={label}><span>0{i+1}</span>{label}</a>)}</nav></div><div className="nav-actions"><a className="nav-contact" href="/contact">Start a Project<I.ArrowUpRight/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)}>{menu?<I.X/>:<I.Menu/>}</button></div></header>}
function Footer(){return <footer id="contact"><div className="footer-glow"/><div className="cta"><div><span className="cta-label"><i/> LET’S CREATE TOGETHER</span><h2>Ready to build software<br/>that moves your business?</h2><p>Bring us the challenge. We’ll bring the strategy, design, and engineering to turn it into a product people value.</p></div><div className="cta-actions"><a className="site-button" href="/contact">Start a Conversation<I.ArrowRight/></a><a href={companyContact.emailHref}>{companyContact.email} <I.ArrowUpRight/></a></div></div><div className="footer-main"><div className="footer-about"><img src="/assets/mikenium-logo-transparent.png" alt="Mikenium — Building Smarter Software"/><p>We design and engineer secure digital products that help ambitious businesses grow with confidence.</p><span className="footer-socials">{companyContact.socialLinks.map(item=>{const Icon=item.Icon;return <a href={item.href} target="_blank" rel="noreferrer" aria-label={item.label} title={item.label} key={item.label}><Icon/></a>})}</span></div><div className="footer-links">{footerNavigation.map(section=><div key={section.title}><h4>{section.title}</h4>{section.links.map(link=><a href={link.href} key={link.label}>{link.label}</a>)}</div>)}</div><div className="footer-contact"><span><I.MapPin/></span><div><h4>Let’s talk about your next idea.</h4><a href={companyContact.emailHref}>{companyContact.email}</a>{companyContact.phones.map(phone=><a href={phone.href} key={phone.href}>{phone.label}</a>)}<small>{companyContact.address}</small></div></div></div><div className="footer-bottom"><p>© 2026 Mikenium. All rights reserved.</p><nav><a href="/">Privacy Policy</a><a href="/">Terms of Service</a><a href="/">Cookie Policy</a></nav><span><i/> All systems operational</span></div></footer>}

function Block({block,index}){
  if(block.type==='heading')return <section id={block.id} className="article-section reveal"><span className="section-count">{String(index+1).padStart(2,'0')}</span><div><span className="article-kicker">{block.eyebrow}</span><h2>{block.title}</h2></div></section>;
  if(block.type==='paragraph')return <div className={`article-content-block reveal ${block.lead?'lead-block':''}`}><p>{block.text}</p></div>;
  if(block.type==='quote')return <div className="article-content-block reveal"><blockquote><I.Quote/><p>{block.text}</p>{block.cite&&<cite>— {block.cite}</cite>}</blockquote></div>;
  if(block.type==='list')return <div className="article-content-block reveal">{block.title&&<h3>{block.title}</h3>}<ul className="prepare-list">{block.items.map(item=><li key={item}><I.CircleCheck/><span>{item}</span></li>)}</ul></div>;
  if(block.type==='image')return <figure className="article-inline-image reveal"><img src={block.url} alt={block.alt}/>{block.caption&&<figcaption>{block.caption}</figcaption>}</figure>;
  if(block.type==='featureGrid')return <div className="article-content-block reveal">{block.title&&<h3>{block.title}</h3>}<div className="technology-grid">{block.items.map((item,i)=><article key={`${item.title}-${i}`}><span><I.Sparkles/></span><small>0{i+1}</small><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div>;
  if(block.type==='callout')return <div className="article-content-block reveal"><div className="article-cta"><span><I.Send/></span><div><small>{block.eyebrow}</small><h3>{block.title}</h3><p>{block.text}</p></div><a className="site-button" href={block.buttonUrl}>{block.buttonLabel}<I.ArrowRight/></a></div></div>;
  return null;
}

export default function SingleBlogPage(){
  const slug=decodeURIComponent(location.pathname.split('/blog/')[1]||'');
  const [post,setPost]=useState(null),[related,setRelated]=useState([]),[loading,setLoading]=useState(true),[menu,setMenu]=useState(false),[scrolled,setScrolled]=useState(false),[progress,setProgress]=useState(0),[active,setActive]=useState(''),[copied,setCopied]=useState(false);
  const headings=useMemo(()=>post?.blocks.filter(x=>x.type==='heading')||[],[post]);
  useEffect(()=>{let mounted=true;Promise.all([getPublicBlog(slug),getPublicBlogs()]).then(([blog,all])=>{if(!mounted)return;setPost(blog);setRelated(all.filter(x=>x.slug!==slug).slice(0,3));document.title=blog.seoTitle||`${blog.title} | Mikenium`;document.querySelector('meta[name="description"]')?.setAttribute('content',blog.seoDescription||blog.excerpt)}).catch(()=>mounted&&setPost(null)).finally(()=>mounted&&setLoading(false));return()=>{mounted=false}},[slug]);
  useEffect(()=>{const scroll=()=>{setScrolled(scrollY>20);const h=document.documentElement.scrollHeight-innerHeight;setProgress(h?Math.min(100,scrollY/h*100):0)};scroll();addEventListener('scroll',scroll,{passive:true});const reveal=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('is-visible')),{threshold:.06});document.querySelectorAll('.single-blog-page .reveal').forEach(el=>reveal.observe(el));const watch=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:'-25% 0px -60%'});headings.forEach(x=>{const el=document.getElementById(x.id);if(el)watch.observe(el)});return()=>{removeEventListener('scroll',scroll);reveal.disconnect();watch.disconnect()}},[post,headings]);
  const share=async()=>{try{if(navigator.share)await navigator.share({title:post.title,url:location.href});else{await navigator.clipboard.writeText(location.href);setCopied(true);setTimeout(()=>setCopied(false),1800)}}catch{}};
  if(loading)return <div className="single-blog-state"><I.LoaderCircle className="spin"/> Loading article...</div>;
  if(!post)return <div className="single-blog-state"><I.FileQuestion/><h1>Article not found</h1><a href="/blog">Return to the journal</a></div>;
  return <div className="public-site single-blog-page"><div className="reading-progress" style={{transform:`scaleX(${progress/100})`}}/><Header menu={menu} setMenu={setMenu} scrolled={scrolled}/><main>
    <section className="article-hero"><div className="article-grid"/><div className="article-glow one"/><div className="article-glow two"/><div className="article-hero-inner"><nav className="breadcrumbs"><a href="/">Home</a><I.ChevronRight/><a href="/blog">Journal</a><I.ChevronRight/><span>{post.category}</span></nav><div className="article-eyebrow"><span><I.Code2/> {post.category.toUpperCase()}</span><i/> {date(post.publishedAt).toUpperCase()}</div><h1>{post.title}</h1><p>{post.excerpt}</p><div className="article-byline">{post.authorAvatarUrl?<img className="author-avatar image" src={post.authorAvatarUrl} alt={post.authorName}/>:<span className="author-avatar">{initials(post.authorName)}</span>}<div><b>{post.authorName}</b><small>{post.authorTitle}</small></div><span className="meta-divider"/><span><I.Clock3/> {post.readingMinutes} min read</span><span><I.CalendarDays/> {date(post.publishedAt)}</span><button onClick={share}>{copied?<I.Check/>:<I.Share2/>}{copied?'Link copied':'Share article'}</button></div></div></section>
    <div className="article-shell"><article className="article-body">{post.coverImageUrl&&<figure className="article-cover reveal" style={{backgroundImage:`linear-gradient(180deg,#04163120,#030c1dcf),url("${post.coverImageUrl}")`,backgroundSize:'cover',backgroundPosition:'center'}}><figcaption><span>{post.coverCaption||'MIKENIUM / JOURNAL'}</span><span>{post.category.toUpperCase()}</span></figcaption></figure>}<div className="article-intro reveal"><p className="lead">{post.excerpt}</p></div>{post.blocks.map((block,index)=><Block block={block} index={index} key={block.id}/>)}</article>
      <aside className="article-sidebar">{headings.length>0&&<div className="toc-card"><span className="side-label">IN THIS ARTICLE</span><div className="toc-line">{headings.map((item,i)=><a className={active===item.id?'active':''} href={`#${item.id}`} key={item.id}><i/><span>0{i+1}</span>{item.title}</a>)}</div><div className="read-status"><span style={{width:`${progress}%`}}/><small>{Math.round(progress)}% read</small></div></div>}<div className="author-card"><div className="author-top"><span>{initials(post.authorName)}</span><div><small>WRITTEN BY</small><h3>{post.authorName}</h3><p>{post.authorTitle}</p></div></div><p>{post.authorBio}</p></div>{related.length>0&&<div className="related-card"><span className="side-label">KEEP EXPLORING</span><h3>Related insights</h3>{related.map(item=><a href={`/blog/${item.slug}`} key={item.id}><span className="related-thumb" style={item.coverImageUrl?{backgroundImage:`linear-gradient(#04162a44,#04162a99),url("${item.coverImageUrl}")`,backgroundSize:'cover'}:undefined}><I.ArrowUpRight/></span><div><small>{item.category} · {item.readingMinutes} min</small><b>{item.title}</b></div></a>)}</div>}</aside>
    </div>
  </main><Footer/></div>;
}
