import React, { useMemo, useState } from 'react';
import * as I from 'lucide-react';

const pageSeed=[
  {name:'Home',description:'Homepage',slug:'/',type:'System',status:'Published',updated:'May 21, 2024 10:30 AM',updater:'Super Admin',tone:'amber'},
  {name:'About Us',description:'About our company',slug:'/about-us',type:'Custom',status:'Published',updated:'May 20, 2024 09:15 AM',updater:'Sarah Johnson',tone:'rose'},
  {name:'Services',description:'Our services',slug:'/services',type:'System',status:'Published',updated:'May 19, 2024 04:45 PM',updater:'Michael Brown',tone:'blue'},
  {name:'Service Details',description:'Single service page',slug:'/services-details',type:'System',status:'Published',updated:'May 18, 2024 11:20 AM',updater:'Super Admin',tone:'amber'},
  {name:'Projects',description:'Our latest projects',slug:'/projects',type:'System',status:'Published',updated:'May 17, 2024 02:30 PM',updater:'Emily Davis',tone:'rose'},
  {name:'Pricing',description:'Pricing plans',slug:'/pricing',type:'Custom',status:'Draft',updated:'May 16, 2024 03:10 PM',updater:'David Wilson',tone:'blue'},
  {name:'Blog',description:'Latest news & insights',slug:'/blog',type:'System',status:'Published',updated:'May 16, 2024 09:00 AM',updater:'Olivia Anderson',tone:'rose'},
  {name:'Contact Us',description:'Get in touch with us',slug:'/contact-us',type:'System',status:'Published',updated:'May 15, 2024 05:20 PM',updater:'James Taylor',tone:'amber'},
  {name:'Careers',description:'Join our team',slug:'/careers',type:'Custom',status:'Hidden',updated:'May 14, 2024 02:15 PM',updater:'Laura Martinez',tone:'rose'},
  {name:'FAQ',description:'Frequently asked questions',slug:'/faq',type:'Custom',status:'Published',updated:'May 14, 2024 10:40 AM',updater:'Super Admin',tone:'amber'}
];

const pageStats=[['Total Pages','24','14.3%',I.Files,'blue',true],['Published','18','12.5%',I.CircleCheckBig,'green',true],['Draft','4','20.0%',I.Clock3,'orange',false],['Hidden','2','0%',I.EyeOff,'purple',null],['Trash','2','33.3%',I.Trash2,'pink',false]];

function PageModal({onClose,onSave}){const [form,setForm]=useState({name:'',description:'',slug:'',type:'Custom',status:'Draft'});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal page-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Page</h2><p>Create a CMS page and configure its visibility.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label className="wide">Page name<input name="name" required autoFocus value={form.name} onChange={change} placeholder="e.g. Our Team"/></label><label className="wide">Description<input name="description" required value={form.description} onChange={change} placeholder="Short page description"/></label><label className="wide">Slug<input name="slug" required value={form.slug} onChange={change} placeholder="/our-team"/></label><label>Type<select name="type" value={form.type} onChange={change}><option>Custom</option><option>System</option></select></label><label>Status<select name="status" value={form.status} onChange={change}><option>Draft</option><option>Published</option><option>Hidden</option></select></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Page</button></div></form></div>}

export function PagesAdminPage(){
  const [pages,setPages]=useState(pageSeed),[query,setQuery]=useState(''),[status,setStatus]=useState('All Status'),[type,setType]=useState('All Types'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]),[perPage,setPerPage]=useState('10');
  const filtered=useMemo(()=>pages.filter(p=>[p.name,p.description,p.slug,p.updater].join(' ').toLowerCase().includes(query.toLowerCase())&&(status==='All Status'||p.status===status)&&(type==='All Types'||p.type===type)),[pages,query,status,type]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addPage=form=>{setPages([{...form,updated:'Jul 14, 2026 12:00 PM',updater:'Super Admin',tone:'amber'},...pages]);setModal(false);flash('Page added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(p=>selected.includes(p.slug))?selected.filter(id=>!filtered.some(p=>p.slug===id)):[...new Set([...selected,...filtered.map(p=>p.slug)])]);
  const exportPages=()=>{const header='Page,Description,Slug,Type,Status,Last Updated,Updated By';const rows=filtered.map(p=>[p.name,p.description,p.slug,p.type,p.status,p.updated,p.updater].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-pages.csv';a.click();URL.revokeObjectURL(url);flash('Page list exported')};
  return <div className="users-page pages-admin-page">
    <div className="users-heading"><div><h1>Pages</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Pages</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Page</button></div>
    <div className="user-stats">{pageStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up===false?'down':'up'}>{up===true&&<I.ArrowUp/>}{up===false&&<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
    <div className="card users-table-card"><div className="users-toolbar"><div className="users-search page-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pages..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Published</option><option>Draft</option><option>Hidden</option></select><select value={type} onChange={e=>setType(e.target.value)}><option>All Types</option><option>System</option><option>Custom</option></select><div className="toolbar-spacer"/><button className="date-button"><I.CalendarDays/> May 15, 2024 - May 21, 2024 <I.ChevronDown/></button><button><I.ListFilter/> Filter</button><button onClick={exportPages}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table pages-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(p=>selected.includes(p.slug))} onChange={toggleAll}/></th><th>Page</th><th>Slug</th><th>Type</th><th>Status</th><th>Last Updated <I.RotateCw/></th><th>Updated By <I.RotateCw/></th><th>Actions</th></tr></thead><tbody>{filtered.map(p=><tr key={p.slug}><td><input type="checkbox" checked={selected.includes(p.slug)} onChange={()=>toggle(p.slug)}/></td><td><div className="page-identity"><i><I.FileText/></i><span><b>{p.name}</b><small>{p.description}</small></span></div></td><td className="page-slug">{p.slug}</td><td><span className={`page-type ${p.type.toLowerCase()}`}>{p.type}</span></td><td><span className={`page-status ${p.status.toLowerCase()}`}>{p.status}</span></td><td>{p.updated}</td><td><span className="page-updater"><i className={p.tone}>{p.updater.split(' ').map(x=>x[0]).join('')}</i>{p.updater}</span></td><td><div className="user-actions"><button title="Edit page" onClick={()=>flash(`Editing ${p.name}`)}><I.Pencil/></button><button title="Preview page" onClick={()=>flash(`Previewing ${p.name}`)}><I.Eye/></button><button className="more"><I.EllipsisVertical/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No pages found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer pages-footer"><span>Showing 1 to {Math.min(Number(perPage),filtered.length)} of 24 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button aria-label="Next"><I.ChevronRight/></button><select value={perPage} onChange={e=>setPerPage(e.target.value)}><option value="10">10 / page</option><option value="20">20 / page</option><option value="50">50 / page</option></select></div></div>
    </div>{modal&&<PageModal onClose={()=>setModal(false)} onSave={addPage}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}
