import React, { useMemo, useRef, useState } from 'react';
import * as I from 'lucide-react';
import { Heading, Stats, Toast } from '../shared/CmsShared';

const folders=[['All Files',1248],['Blog Images',245],['Project Images',189],['Service Icons',96],['Testimonials',58],['Clients',72],['Team Members',34],['General',112],['Documents',128],['Videos',156],['Audio',69],['Others',89]];
const mediaSeed=[
  {name:'office-interior.jpg',type:'JPG',size:'2.4 MB',folder:'General',asset:'/assets/about-team-studio-v2.png',kind:'image'},
  {name:'building.jpg',type:'JPG',size:'1.8 MB',folder:'Project Images',asset:'/assets/portfolio-showcase.png',kind:'image'},
  {name:'Project-Proposal.pdf',type:'PDF',size:'1.2 MB',folder:'Documents',kind:'pdf'},
  {name:'product-demo.mp4',type:'MP4',size:'12.6 MB',folder:'Videos',asset:'/assets/blog-showcase.png',kind:'video'},
  {name:'team-meeting.jpg',type:'JPG',size:'3.1 MB',folder:'Team Members',asset:'/assets/about-team-studio-v2.png',kind:'image'},
  {name:'service-icon-1.png',type:'PNG',size:'45 KB',folder:'Service Icons',asset:'/assets/mikenium-logo-transparent.png',kind:'image'},
  {name:'hero-banner.jpg',type:'JPG',size:'1.6 MB',folder:'Blog Images',asset:'/assets/blog-showcase.png',kind:'image'},
  {name:'company-brochure.pdf',type:'PDF',size:'3.7 MB',folder:'Documents',kind:'pdf'},
  {name:'mikenium-logo.png',type:'PNG',size:'98 KB',folder:'General',asset:'/assets/mikenium-logo-transparent.png',kind:'image'},
  {name:'john-smith.jpg',type:'JPG',size:'580 KB',folder:'Clients',asset:'/assets/about-team-studio-v2.png',kind:'image'},
  {name:'background-music.mp3',type:'MP3',size:'4.2 MB',folder:'Audio',kind:'audio'},
  {name:'analytics-chart.jpg',type:'JPG',size:'1.3 MB',folder:'Blog Images',asset:'/assets/blog-showcase.png',kind:'image'},
  {name:'Terms & Conditions.docx',type:'DOCX',size:'32 KB',folder:'Documents',kind:'doc'},
  {name:'project-discussion.jpg',type:'JPG',size:'2.7 MB',folder:'Project Images',asset:'/assets/about-team-studio-v2.png',kind:'image'},
  {name:'client-testimonial.mp4',type:'MP4',size:'8.9 MB',folder:'Testimonials',asset:'/assets/portfolio-showcase.png',kind:'video'}
];

function MediaVisual({item}){if(item.asset)return <div className="media-visual image" style={{backgroundImage:`url('${item.asset}')`}}>{item.kind==='video'&&<I.PlayCircle/>}</div>;const Icon=item.kind==='audio'?I.Music2:I.FileText;return <div className={`media-visual ${item.kind}`}><Icon/><b>{item.type}</b></div>}
export function MediaLibraryPage(){
  const [media,setMedia]=useState(mediaSeed),[query,setQuery]=useState(''),[type,setType]=useState('All Types'),[folder,setFolder]=useState('All Files'),[view,setView]=useState('grid'),[toast,setToast]=useState('');const fileRef=useRef(null);const flash=t=>{setToast(t);setTimeout(()=>setToast(''),2200)};
  const filtered=useMemo(()=>media.filter(m=>m.name.toLowerCase().includes(query.toLowerCase())&&(type==='All Types'||m.kind===type)&&(folder==='All Files'||m.folder===folder)),[media,query,type,folder]);
  const upload=e=>{const files=[...e.target.files];if(!files.length)return;setMedia([...files.map(f=>({name:f.name,type:f.name.split('.').pop().toUpperCase(),size:`${Math.max(1,Math.round(f.size/1024))} KB`,folder:'All Files',kind:f.type.startsWith('image')?'image':f.type.startsWith('video')?'video':'doc'})),...media]);flash(`${files.length} file${files.length>1?'s':''} uploaded`)};
  return <div className="users-page media-page"><Heading title="Media Library" action="Upload Files" icon={I.CloudUpload} onAction={()=>fileRef.current?.click()}/><input hidden ref={fileRef} type="file" multiple onChange={upload}/><Stats items={[["Total Files","1,248","All time",I.Folder,"blue"],["Images","895","72% of total",I.Image,"green"],["Documents","128","10% of total",I.FileText,"purple"],["Videos","156","13% of total",I.CirclePlay,"orange"],["Audio","69","5% of total",I.Music2,"pink"]]}/><div className="card media-shell"><div className="media-toolbar"><div className="users-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search media..."/></div><select value={type} onChange={e=>setType(e.target.value)}><option>All Types</option><option value="image">Images</option><option value="video">Videos</option><option value="pdf">PDF</option><option value="doc">Documents</option><option value="audio">Audio</option></select><select value={folder} onChange={e=>setFolder(e.target.value)}>{folders.map(([n])=><option key={n}>{n}</option>)}</select><span/><button><I.CalendarDays/>May 15, 2024 - May 21, 2024<I.ChevronDown/></button><button><I.ListFilter/>Filter</button><select><option>Sort by: Newest</option><option>Sort by: Name</option></select><div className="media-view"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')}><I.LayoutGrid/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')}><I.List/></button></div></div><div className="media-body"><aside className="folder-panel"><div><h3>Folders</h3><button onClick={()=>flash('New folder created')}><I.Plus/>New Folder</button></div>{folders.map(([name,count])=><button className={folder===name?'active':''} key={name} onClick={()=>setFolder(name)}><I.Folder/>{name}<span>{count}</span><I.EllipsisVertical/></button>)}<div className="storage"><b>Storage Usage</b><p>2.45 GB / 10 GB used</p><i><span/></i><em>24.5%</em></div></aside><section className={`media-content ${view}`}><h3>{filtered.length===media.length?'1,248':filtered.length} files found</h3><div>{filtered.map((m,index)=><article key={`${m.name}-${index}`}><input type="checkbox"/><MediaVisual item={m}/><footer><span className={`media-kind ${m.kind}`}><I.File/></span><p><b>{m.name}</b><small>{m.type} · {m.size}</small></p><button><I.EllipsisVertical/></button></footer></article>)}</div></section></div><div className="media-footer"><span>Showing 1 to {filtered.length} of 1,248 files</span><div><button><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>52</button><button><I.ChevronRight/></button></div></div></div><Toast text={toast}/></div>
}
