import React,{useEffect,useMemo,useState} from 'react';
import * as I from 'lucide-react';
import {createTestimonial,deleteTestimonial,getTestimonials,updateTestimonial,uploadTestimonialAvatar} from '../../../services/admin/admin-api';

const labels={PUBLISHED:'Published',PENDING:'Pending',HIDDEN:'Hidden',ARCHIVED:'Archived'};
const blank={clientName:'',clientTitle:'',company:'',text:'',service:'Web Development',result:'',rating:5,avatarUrl:'',verified:true,featured:false,status:'PENDING',order:0};
const initials=name=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const date=value=>value?new Date(value).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'2-digit'}):'—';

function TestimonialModal({testimonial,onClose,onSave,saving,error}){
  const [form,setForm]=useState(testimonial||blank),[uploading,setUploading]=useState(false);
  const change=e=>{const{name,value,type,checked}=e.target;setForm(f=>({...f,[name]:type==='checkbox'?checked:value}))};
  const upload=async file=>{setUploading(true);try{const{imageUrl}=await uploadTestimonialAvatar(file);setForm(f=>({...f,avatarUrl:imageUrl}))}finally{setUploading(false)}};
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal testimonial-modal testimonial-crud-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave({...form,rating:Number(form.rating),order:Number(form.order)})}}><div className="modal-head"><div><h2>{testimonial?'Edit Testimonial':'Add New Testimonial'}</h2><p>Published testimonials appear in the public client stories section.</p></div><button type="button" onClick={onClose}><I.X/></button></div>{error&&<div className="blog-editor-error"><I.CircleAlert/><span><b>Unable to save</b>{error}</span></div>}<div className="client-form-grid">
    <label>Client name<input required autoFocus name="clientName" value={form.clientName} onChange={change}/></label><label>Company<input required name="company" value={form.company} onChange={change}/></label><label>Client job title<input name="clientTitle" value={form.clientTitle} onChange={change} placeholder="CEO, CTO, Founder..."/></label><label>Service / project label<input required name="service" value={form.service} onChange={change}/></label>
    <label className="wide">Testimonial<textarea required minLength="20" name="text" value={form.text} onChange={change}/></label><label className="wide">Project result<input name="result" value={form.result} onChange={change} placeholder="38% faster operations"/></label>
    <label>Rating<select name="rating" value={form.rating} onChange={change}>{[5,4.5,4,3.5,3,2.5,2,1.5,1].map(x=><option value={x} key={x}>{x} stars</option>)}</select></label><label>Status<select name="status" value={form.status} onChange={change}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Display order<input type="number" min="0" name="order" value={form.order} onChange={change}/></label>
    <label className="wide">Client image URL<input name="avatarUrl" value={form.avatarUrl} onChange={change}/></label><label className="wide project-image-upload"><span>Upload client image</span><input id="testimonial-avatar" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files[0]&&upload(e.target.files[0])}/><label className="project-upload-box" htmlFor="testimonial-avatar">{form.avatarUrl?<img src={form.avatarUrl} alt="Client preview"/>:<><I.UploadCloud/><b>{uploading?'Uploading...':'Choose client image'}</b><small>JPG, PNG or WebP · max 5 MB</small></>}</label></label>
    <label className="blog-check"><input type="checkbox" name="verified" checked={form.verified} onChange={change}/> Verified client</label><label className="blog-check"><input type="checkbox" name="featured" checked={form.featured} onChange={change}/> Featured testimonial</label>
  </div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving||uploading}>{saving?<I.LoaderCircle className="spin"/>:<I.Save/>}{saving?'Saving...':'Save testimonial'}</button></div></form></div>;
}

export function TestimonialsPage(){
  const [testimonials,setTestimonials]=useState([]),[stats,setStats]=useState({}),[query,setQuery]=useState(''),[status,setStatus]=useState('All Status'),[rating,setRating]=useState('All Ratings'),[service,setService]=useState('All Services'),[modal,setModal]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const data=await getTestimonials();setTestimonials(data.testimonials);setStats(data.stats)}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
  const services=[...new Set(testimonials.map(x=>x.service))];
  const filtered=useMemo(()=>testimonials.filter(x=>`${x.clientName} ${x.company} ${x.text} ${x.service}`.toLowerCase().includes(query.toLowerCase())&&(status==='All Status'||x.status===status)&&(rating==='All Ratings'||x.rating===Number(rating))&&(service==='All Services'||x.service===service)),[testimonials,query,status,rating,service]);
  const flash=text=>{setToast(text);setTimeout(()=>setToast(''),2500)};
  const save=async form=>{setSaving(true);setError('');try{modal?.id?await updateTestimonial(modal.id,form):await createTestimonial(form);setModal(null);await load();flash('Testimonial saved')}catch(e){setError(e.message)}finally{setSaving(false)}};
  const remove=async item=>{if(!confirm(`Delete testimonial from ${item.clientName}?`))return;try{await deleteTestimonial(item.id);await load();flash('Testimonial deleted')}catch(e){setError(e.message)}};
  const cards=[['Total Testimonials',stats.total,I.MessageSquareText,'blue'],['Published',stats.published,I.SquareCheckBig,'green'],['Pending',stats.pending,I.Clock3,'orange'],['Hidden',stats.hidden,I.EyeOff,'purple'],['Archived',stats.archived,I.Archive,'pink']];
  return <div className="users-page testimonials-page"><div className="users-heading"><div><h1>Testimonials</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Testimonials</span></div></div><button className="users-add" onClick={()=>{setError('');setModal({})}}><I.Plus/> Add New Testimonial</button></div><div className="user-stats">{cards.map(([title,value,Icon,color])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{Number(value||0).toLocaleString()}</b><p>Live database total</p></div></div>)}</div>
    {error&&!modal&&<div className="admin-inline-error"><I.CircleAlert/>{error}<button onClick={()=>setError('')}><I.X/></button></div>}<div className="card users-table-card"><div className="users-toolbar"><div className="users-search testimonial-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search testimonials..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select value={rating} onChange={e=>setRating(e.target.value)}><option>All Ratings</option><option value="5">5 Stars</option><option value="4.5">4.5 Stars</option><option value="4">4 Stars</option></select><select value={service} onChange={e=>setService(e.target.value)}><option>All Services</option>{services.map(x=><option key={x}>{x}</option>)}</select><div className="toolbar-spacer"/><button onClick={load}><I.RefreshCw/> Refresh</button></div>
      <div className="users-table-wrap"><table className="users-table testimonials-table"><thead><tr><th>Client</th><th>Testimonial</th><th>Service</th><th>Rating</th><th>Status</th><th>Published</th><th>Actions</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><div className="testimonial-client">{item.avatarUrl?<img className="testimonial-avatar" src={item.avatarUrl} alt=""/>:<i className="blue">{initials(item.clientName)}</i>}<span><b>{item.clientName}</b><small>{item.clientTitle?`${item.clientTitle}, `:''}{item.company}</small></span></div></td><td><p className="testimonial-copy">{item.text}</p></td><td><span className="testimonial-service web-development">{item.service}</span></td><td><span className="testimonial-rating">{Array.from({length:5},(_,i)=><I.Star key={i} className={i<Math.round(item.rating)?'filled':''} fill={i<Math.round(item.rating)?'currentColor':'none'}/>)}</span></td><td><span className={`testimonial-status ${item.status.toLowerCase()}`}>{labels[item.status]}</span></td><td>{date(item.publishedAt)}</td><td><div className="user-actions"><button onClick={()=>{setError('');setModal(item)}}><I.Pencil/></button><button className="danger" onClick={()=>remove(item)}><I.Trash2/></button></div></td></tr>)}</tbody></table>{loading?<div className="empty"><I.LoaderCircle className="spin"/><b>Loading testimonials...</b></div>:!filtered.length&&<div className="empty"><I.SearchX/><b>No testimonials found</b><span>Add client feedback to the database.</span></div>}</div><div className="users-footer"><span>Showing {filtered.length} of {Number(stats.total||0)} database testimonials</span></div></div>
    {modal&&<TestimonialModal testimonial={modal.id?modal:null} onClose={()=>setModal(null)} onSave={save} saving={saving} error={error}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}</div>;
}
