import React, { useMemo, useState } from 'react';
import * as I from 'lucide-react';

const testimonialSeed=[
  {client:'John Smith',company:'TechSolutions Inc.',text:'Mikenium delivered an exceptional product that exceeded our expectations. Their team was professional, responsive, and highly skilled.',service:'Web Development',rating:5,status:'Published',date:'May 21, 2024',time:'10:30 AM',tone:'amber'},
  {client:'Sarah Johnson',company:'HealthCare Plus',text:'Great experience working with the Mikenium team. They understood our requirements perfectly and delivered on time.',service:'Mobile App',rating:5,status:'Published',date:'May 20, 2024',time:'09:15 AM',tone:'rose'},
  {client:'Michael Brown',company:'MarketHub Ltd.',text:'The design and functionality are outstanding. Mikenium is our go-to partner for all our digital needs.',service:'UI/UX Design',rating:4.5,status:'Published',date:'May 18, 2024',time:'02:45 PM',tone:'blue'},
  {client:'Emily Davis',company:'CloudNova',text:'Very talented team! They provided innovative solutions that helped us grow our business.',service:'Cloud Solutions',rating:5,status:'Published',date:'May 17, 2024',time:'01:20 PM',tone:'rose'},
  {client:'David Wilson',company:'FinSoft Systems',text:'Professional, reliable, and supportive throughout the entire project. Highly recommend Mikenium!',service:'Web Development',rating:5,status:'Pending',date:'—',time:'',tone:'amber'},
  {client:'Laura Martinez',company:'EduTech Solutions',text:'They transformed our ideas into a beautiful product. Excellent communication and support.',service:'E-learning Platform',rating:4.5,status:'Pending',date:'—',time:'',tone:'rose'},
  {client:'James Taylor',company:'DesignHub Studio',text:'Good work and great support. Will definitely work with them again.',service:'UI/UX Design',rating:5,status:'Hidden',date:'May 10, 2024',time:'04:10 PM',tone:'amber'},
  {client:'Olivia Anderson',company:'AutoDrive Co.',text:'Amazing team with strong technical expertise. Very happy with the results!',service:'Mobile App',rating:4.5,status:'Hidden',date:'May 09, 2024',time:'11:30 AM',tone:'rose'}
];

const testimonialStats=[['Total Testimonials','86','12.8%',I.MessageSquareText,'blue',true],['Published','71','14.3%',I.SquareCheckBig,'green',true],['Pending','9','10.0%',I.Clock3,'orange',false],['Hidden','4','0%',I.EyeOff,'purple',null],['Trash','2','33.3%',I.Trash2,'pink',false]];

function TestimonialModal({onClose,onSave}){const [form,setForm]=useState({client:'',company:'',text:'',service:'Web Development',rating:'5',status:'Pending'});const change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal testimonial-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><div><h2>Add New Testimonial</h2><p>Add client feedback for review or publication.</p></div><button type="button" onClick={onClose} aria-label="Close"><I.X/></button></div><div className="client-form-grid"><label>Client name<input name="client" required autoFocus value={form.client} onChange={change} placeholder="Full name"/></label><label>Company<input name="company" required value={form.company} onChange={change} placeholder="Company name"/></label><label className="wide">Testimonial<textarea name="text" required value={form.text} onChange={change} placeholder="Client feedback"/></label><label>Service<select name="service" value={form.service} onChange={change}>{[...new Set(testimonialSeed.map(t=>t.service))].map(x=><option key={x}>{x}</option>)}</select></label><label>Rating<select name="rating" value={form.rating} onChange={change}><option value="5">5 stars</option><option value="4.5">4.5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option></select></label><label className="wide">Status<select name="status" value={form.status} onChange={change}><option>Pending</option><option>Published</option><option>Hidden</option></select></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary"><I.Plus/> Add Testimonial</button></div></form></div>}

export function TestimonialsPage(){
  const [testimonials,setTestimonials]=useState(testimonialSeed),[query,setQuery]=useState(''),[status,setStatus]=useState('All Status'),[rating,setRating]=useState('All Ratings'),[service,setService]=useState('All Services'),[client,setClient]=useState('All Clients'),[modal,setModal]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState([]);
  const filtered=useMemo(()=>testimonials.filter(t=>[t.client,t.company,t.text,t.service].join(' ').toLowerCase().includes(query.toLowerCase())&&(status==='All Status'||t.status===status)&&(rating==='All Ratings'||t.rating===Number(rating))&&(service==='All Services'||t.service===service)&&(client==='All Clients'||t.client===client)),[testimonials,query,status,rating,service,client]);
  const flash=message=>{setToast(message);setTimeout(()=>setToast(''),2500)};
  const addTestimonial=form=>{setTestimonials([{...form,rating:Number(form.rating),date:form.status==='Published'?'Jul 14, 2026':'—',time:form.status==='Published'?'Just now':'',tone:'blue'},...testimonials]);setModal(false);flash('Testimonial added successfully')};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
  const toggleAll=()=>setSelected(filtered.length&&filtered.every(t=>selected.includes(t.client))?selected.filter(id=>!filtered.some(t=>t.client===id)):[...new Set([...selected,...filtered.map(t=>t.client)])]);
  const exportTestimonials=()=>{const header='Client,Company,Testimonial,Service,Rating,Status,Published On';const rows=filtered.map(t=>[t.client,t.company,t.text,t.service,t.rating,t.status,`${t.date} ${t.time}`].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mikenium-testimonials.csv';a.click();URL.revokeObjectURL(url);flash('Testimonial list exported')};
  return <div className="users-page testimonials-page">
    <div className="users-heading"><div><h1>Testimonials</h1><div className="users-crumb">Dashboard <I.ChevronRight/> <span>Testimonials</span></div></div><button className="users-add" onClick={()=>setModal(true)}><I.Plus/> Add New Testimonial</button></div>
    <div className="user-stats">{testimonialStats.map(([title,value,change,Icon,color,up])=><div className="card user-stat" key={title}><span className={`user-stat-icon ${color}`}><Icon/></span><div><small>{title}</small><b>{value}</b><p className={up===false?'down':'up'}>{up===true&&<I.ArrowUp/>}{up===false&&<I.ArrowDown/>}{change}<span>vs last 7 days</span></p></div></div>)}</div>
    <div className="card users-table-card"><div className="users-toolbar"><div className="users-search testimonial-search"><I.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search testimonials..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Published</option><option>Pending</option><option>Hidden</option></select><select value={rating} onChange={e=>setRating(e.target.value)}><option>All Ratings</option><option value="5">5 Stars</option><option value="4.5">4.5 Stars</option></select><select value={service} onChange={e=>setService(e.target.value)}><option>All Services</option>{[...new Set(testimonialSeed.map(t=>t.service))].map(x=><option key={x}>{x}</option>)}</select><select value={client} onChange={e=>setClient(e.target.value)}><option>All Clients</option>{[...new Set(testimonialSeed.map(t=>t.client))].map(x=><option key={x}>{x}</option>)}</select><div className="toolbar-spacer"/><button className="date-button"><I.CalendarDays/> May 15, 2024 - May 21, 2024 <I.ChevronDown/></button><button><I.ListFilter/> Filter</button><button onClick={exportTestimonials}><I.Download/> Export</button></div>
      <div className="users-table-wrap"><table className="users-table testimonials-table"><thead><tr><th><input type="checkbox" checked={filtered.length>0&&filtered.every(t=>selected.includes(t.client))} onChange={toggleAll}/></th><th>Client</th><th>Testimonial</th><th>Service</th><th>Rating</th><th>Status</th><th>Published On <I.RotateCw/></th><th>Actions</th></tr></thead><tbody>{filtered.map(t=><tr key={t.client}><td><input type="checkbox" checked={selected.includes(t.client)} onChange={()=>toggle(t.client)}/></td><td><div className="testimonial-client"><i className={t.tone}>{t.client.split(' ').map(x=>x[0]).join('')}</i><span><b>{t.client}</b><small>{t.company}</small></span></div></td><td><p className="testimonial-copy">{t.text}</p></td><td><span className={`testimonial-service ${t.service.toLowerCase().replaceAll(/[^a-z]+/g,'-')}`}>{t.service}</span></td><td><span className="testimonial-rating">{Array.from({length:5},(_,i)=>i+.5===t.rating?<I.StarHalf key={i} fill="currentColor"/>:<I.Star key={i} className={i<t.rating?'filled':''} fill={i<t.rating?'currentColor':'none'}/>)}</span></td><td><span className={`testimonial-status ${t.status.toLowerCase()}`}>{t.status}</span></td><td><span className="created-date">{t.date}<small>{t.time}</small></span></td><td><div className="user-actions"><button title="View testimonial" onClick={()=>flash(`Viewing ${t.client}'s testimonial`)}><I.Eye/></button><button title="Edit testimonial" onClick={()=>flash(`Editing ${t.client}'s testimonial`)}><I.Pencil/></button><button className="more"><I.EllipsisVertical/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><I.SearchX/><b>No testimonials found</b><span>Try changing the search or filters.</span></div>}</div>
      <div className="users-footer"><span>Showing 1 to {filtered.length} of 86 results</span><div><button aria-label="Previous"><I.ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>11</button><button aria-label="Next"><I.ChevronRight/></button></div></div>
    </div>{modal&&<TestimonialModal onClose={()=>setModal(false)} onSave={addTestimonial}/>} {toast&&<div className="toast"><I.CircleCheck/>{toast}</div>}
  </div>
}
